export enum TimelineEventType {
  ORDER_CREATED = 'order_created',
  PAYMENT_COMPLETED = 'payment_completed',
  SELECTION_CONFIRMED = 'selection_confirmed',
  DELIVERY_SUBMITTED = 'delivery_submitted',
  DELIVERY_ACCEPTED = 'delivery_accepted',
  DELIVERY_REJECTED = 'delivery_rejected',
  REVISION_STARTED = 'revision_started',
  REVISION_COMPLETED = 'revision_completed',
  SETTLEMENT_CREATED = 'settlement_created',
  SETTLEMENT_PAID = 'settlement_paid',
  EXCEPTION_RAISED = 'exception_raised',
  EXCEPTION_HANDLED = 'exception_handled',
  ORDER_COMPLETED = 'order_completed',
  REMARK_ADDED = 'remark_added',
  STATUS_CHANGED = 'status_changed',
  OTHER = 'other',
}
