# Generated by Django 5.0.1 on 2026-06-11 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True, verbose_name='日期')),
                ('total_conversations', models.IntegerField(default=0, verbose_name='总会话数')),
                ('total_messages', models.IntegerField(default=0, verbose_name='总消息数')),
                ('ai_suggestion_count', models.IntegerField(default=0, verbose_name='AI建议数')),
                ('ai_adoption_count', models.IntegerField(default=0, verbose_name='AI采纳数')),
                ('ai_adoption_rate', models.FloatField(default=0, verbose_name='AI采纳率')),
                ('total_reviews', models.IntegerField(default=0, verbose_name='总审核数')),
                ('approved_reviews', models.IntegerField(default=0, verbose_name='通过审核数')),
                ('rejected_reviews', models.IntegerField(default=0, verbose_name='拒绝审核数')),
                ('pending_reviews', models.IntegerField(default=0, verbose_name='待审核数')),
                ('total_risks', models.IntegerField(default=0, verbose_name='总风险数')),
                ('resolved_risks', models.IntegerField(default=0, verbose_name='已解决风险数')),
                ('avg_response_time', models.FloatField(default=0, verbose_name='平均响应时间(秒)')),
                ('total_tokens', models.BigIntegerField(default=0, verbose_name='总Token数')),
                ('total_cost', models.DecimalField(decimal_places=6, default=0.0, max_digits=12, verbose_name='总费用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '日统计',
                'verbose_name_plural': '日统计',
                'db_table': 'daily_stats',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AccuracyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='日期')),
                ('sales_operation', models.CharField(db_index=True, max_length=50, verbose_name='销售运营分组')),
                ('prompt_version', models.CharField(db_index=True, max_length=50, verbose_name='提示词版本')),
                ('total_calls', models.IntegerField(default=0, verbose_name='总调用次数')),
                ('accurate_calls', models.IntegerField(default=0, verbose_name='准确次数')),
                ('accuracy_rate', models.FloatField(default=0, verbose_name='准确率')),
                ('error_timeout', models.IntegerField(default=0, verbose_name='超时错误数')),
                ('error_rate_limit', models.IntegerField(default=0, verbose_name='限流错误数')),
                ('error_api_error', models.IntegerField(default=0, verbose_name='API错误数')),
                ('error_content_filter', models.IntegerField(default=0, verbose_name='内容过滤错误数')),
                ('error_other', models.IntegerField(default=0, verbose_name='其他错误数')),
                ('avg_response_time', models.FloatField(default=0, verbose_name='平均响应时间(秒)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '准确率统计',
                'verbose_name_plural': '准确率统计',
                'db_table': 'accuracy_stats',
                'ordering': ['-date'],
                'unique_together': {('date', 'sales_operation', 'prompt_version')},
            },
        ),
        migrations.CreateModel(
            name='TokenUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='日期')),
                ('model', models.CharField(db_index=True, max_length=100, verbose_name='模型名称')),
                ('prompt_tokens', models.IntegerField(default=0, verbose_name='提示Token数')),
                ('completion_tokens', models.IntegerField(default=0, verbose_name='补全Token数')),
                ('total_tokens', models.IntegerField(default=0, verbose_name='总Token数')),
                ('cost', models.DecimalField(decimal_places=6, default=0.0, max_digits=10, verbose_name='费用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_usage', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'Token使用记录',
                'verbose_name_plural': 'Token使用记录',
                'db_table': 'token_usage',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UsageStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='日期')),
                ('total_conversations', models.IntegerField(default=0, verbose_name='总会话数')),
                ('total_messages', models.IntegerField(default=0, verbose_name='总消息数')),
                ('total_tokens', models.BigIntegerField(default=0, verbose_name='总Token数')),
                ('active_users', models.IntegerField(default=0, verbose_name='活跃用户数')),
                ('new_users', models.IntegerField(default=0, verbose_name='新增用户数')),
                ('api_calls', models.IntegerField(default=0, verbose_name='API调用次数')),
                ('avg_response_time', models.FloatField(default=0.0, verbose_name='平均响应时间(秒)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '使用统计',
                'verbose_name_plural': '使用统计',
                'db_table': 'usage_stats',
                'ordering': ['-date'],
                'unique_together': {('date',)},
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', '登录'), ('logout', '登出'), ('create_conversation', '创建会话'), ('send_message', '发送消息'), ('create_prompt', '创建提示词'), ('review_content', '审核内容')], db_index=True, max_length=50, verbose_name='活动类型')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='用户代理')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户活动',
                'verbose_name_plural': '用户活动',
                'db_table': 'user_activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
