// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
    }
    '/api/auth/logout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/logout.post').default>>>>
    }
    '/api/auth/me': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/me.get').default>>>>
    }
    '/api/points/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/points/[id].get').default>>>>
    }
    '/api/points': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/points/index.get').default>>>>
    }
    '/api/seed': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/seed.post').default>>>>
    }
    '/api/stats/export': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/stats/export.get').default>>>>
    }
    '/api/stats/overview': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/stats/overview.get').default>>>>
    }
    '/api/stats/public': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/stats/public.get').default>>>>
    }
    '/api/tasks/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tasks/[id].get').default>>>>
    }
    '/api/tasks/:id/cancel': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tasks/[id]/cancel.post').default>>>>
    }
    '/api/tasks/:id/claim': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tasks/[id]/claim.post').default>>>>
    }
    '/api/tasks/:id/escalate': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tasks/[id]/escalate.post').default>>>>
    }
    '/api/tasks/:id/review': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tasks/[id]/review.post').default>>>>
    }
    '/api/tasks/:id/submit-fix': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tasks/[id]/submit-fix.post').default>>>>
    }
    '/api/tasks': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tasks/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tasks/index.post').default>>>>
    }
    '/api/uploads/photo': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/uploads/photo.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}