# Generated by Django 4.2.7 on 2026-06-05 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('role', models.CharField(choices=[('director', '导演'), ('actor', '演员'), ('crew', '剧务'), ('admin', '管理员')], max_length=20, verbose_name='角色')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='电话')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '成员',
                'verbose_name_plural': '成员',
            },
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='剧目名称')),
                ('description', models.TextField(blank=True, verbose_name='剧目描述')),
                ('performance_date', models.DateField(blank=True, null=True, verbose_name='演出日期')),
                ('status', models.CharField(choices=[('preparing', '筹备中'), ('rehearsing', '排练中'), ('performing', '演出周'), ('completed', '已完成')], default='preparing', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('cast', models.ManyToManyField(blank=True, related_name='plays', to='rehearsal.member', verbose_name='演员阵容')),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directed_plays', to='rehearsal.member', verbose_name='导演')),
            ],
            options={
                'verbose_name': '剧目',
                'verbose_name_plural': '剧目',
            },
        ),
        migrations.CreateModel(
            name='Prop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='道具名称')),
                ('category', models.CharField(choices=[('furniture', '家具'), ('weapon', '兵器'), ('clothing', '服装'), ('daily', '日常用品'), ('other', '其他')], max_length=20, verbose_name='道具分类')),
                ('quantity', models.IntegerField(default=1, verbose_name='库存数量')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('image', models.ImageField(blank=True, null=True, upload_to='props/', verbose_name='图片')),
            ],
            options={
                'verbose_name': '道具',
                'verbose_name_plural': '道具',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='排练室名称')),
                ('capacity', models.IntegerField(verbose_name='容纳人数')),
                ('has_lighting', models.BooleanField(default=False, verbose_name='有灯光设备')),
                ('has_sound', models.BooleanField(default=False, verbose_name='有音响设备')),
                ('has_stage', models.BooleanField(default=False, verbose_name='有舞台')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_available', models.BooleanField(default=True, verbose_name='可用')),
            ],
            options={
                'verbose_name': '排练室',
                'verbose_name_plural': '排练室',
            },
        ),
        migrations.CreateModel(
            name='RoomMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='维修标题')),
                ('description', models.TextField(verbose_name='维修描述')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('status', models.CharField(choices=[('scheduled', '计划中'), ('ongoing', '进行中'), ('completed', '已完成')], default='scheduled', max_length=20, verbose_name='状态')),
                ('props_released', models.BooleanField(default=False, verbose_name='道具已释放')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rehearsal.member', verbose_name='创建人')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='rehearsal.room', verbose_name='排练室')),
            ],
            options={
                'verbose_name': '排练室维修',
                'verbose_name_plural': '排练室维修',
            },
        ),
        migrations.CreateModel(
            name='Rehearsal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='排练日期')),
                ('start_time', models.TimeField(verbose_name='开始时间')),
                ('end_time', models.TimeField(verbose_name='结束时间')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已通过'), ('rejected', '已拒绝'), ('ongoing', '进行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('need_lighting', models.BooleanField(default=False, verbose_name='需要灯光')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rehearsals', to='rehearsal.member', verbose_name='创建人')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directed_rehearsals', to='rehearsal.member', verbose_name='导演')),
                ('members', models.ManyToManyField(related_name='rehearsals', to='rehearsal.member', verbose_name='参与成员')),
                ('play', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rehearsals', to='rehearsal.play', verbose_name='剧目')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rehearsals', to='rehearsal.room', verbose_name='排练室')),
            ],
            options={
                'verbose_name': '排练安排',
                'verbose_name_plural': '排练安排',
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='PropUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='使用数量')),
                ('returned', models.BooleanField(default=False, verbose_name='已归还')),
                ('returned_at', models.DateTimeField(blank=True, null=True, verbose_name='归还时间')),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='rehearsal.prop', verbose_name='道具')),
                ('rehearsal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prop_usages', to='rehearsal.rehearsal', verbose_name='排练')),
            ],
            options={
                'verbose_name': '道具使用',
                'verbose_name_plural': '道具使用',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('info', '通知'), ('warning', '警告'), ('change', '变动通知'), ('cancel', '取消通知')], default='info', max_length=20, verbose_name='消息类型')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('read_by', models.ManyToManyField(blank=True, related_name='read_messages', to='rehearsal.member', verbose_name='已读人员')),
                ('recipients', models.ManyToManyField(related_name='received_messages', to='rehearsal.member', verbose_name='接收人')),
                ('rehearsal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='rehearsal.rehearsal', verbose_name='相关排练')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to='rehearsal.member', verbose_name='发送人')),
            ],
            options={
                'verbose_name': '消息',
                'verbose_name_plural': '消息',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='设备名称')),
                ('type', models.CharField(choices=[('lighting', '灯光设备'), ('sound', '音响设备'), ('other', '其他设备')], max_length=20, verbose_name='设备类型')),
                ('is_working', models.BooleanField(default=True, verbose_name='正常工作')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='rehearsal.room', verbose_name='所属排练室')),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备',
            },
        ),
        migrations.CreateModel(
            name='CancelRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='取消理由')),
                ('cancelled_at', models.DateTimeField(auto_now_add=True, verbose_name='取消时间')),
                ('cancelled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rehearsal.member', verbose_name='取消人')),
                ('rehearsal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancel_records', to='rehearsal.rehearsal', verbose_name='排练')),
            ],
            options={
                'verbose_name': '取消记录',
                'verbose_name_plural': '取消记录',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', '准时'), ('late', '迟到'), ('absent', '缺席')], default='present', max_length=20, verbose_name='出勤状态')),
                ('check_in_time', models.DateTimeField(blank=True, null=True, verbose_name='签到时间')),
                ('late_minutes', models.IntegerField(default=0, verbose_name='迟到分钟数')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='rehearsal.member', verbose_name='成员')),
                ('rehearsal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='rehearsal.rehearsal', verbose_name='排练')),
            ],
            options={
                'verbose_name': '出勤记录',
                'verbose_name_plural': '出勤记录',
                'unique_together': {('rehearsal', 'member')},
            },
        ),
    ]
