import type {
  User,
  MeetingListItem,
  Meeting,
  ActionItem,
  Milestone,
  ModelVersion,
  EvaluationReport,
  MaskingRule,
  ApiCallLog,
  Speaker,
  TranscriptSegment,
  VersionHistory,
} from '#shared/types';

export const mockUsers: User[] = [
  { id: '1', email: 'admin@demo.com', name: '系统管理员', role: 'admin' },
  { id: '2', email: 'manager@demo.com', name: '项目经理', role: 'manager' },
  { id: '3', email: 'reviewer@demo.com', name: '质量审核员', role: 'reviewer' },
  { id: '4', email: 'zhangsan@demo.com', name: '张三', role: 'member' },
  { id: '5', email: 'zhaoliu@demo.com', name: '赵六', role: 'member' },
];

export const mockSpeakers: Speaker[] = [
  { id: 's1', name: '李明', role: '产品经理', color: '#3b82f6' },
  { id: 's2', name: '王芳', role: '技术负责人', color: '#10b981' },
  { id: 's3', name: '张伟', role: '设计师', color: '#f59e0b' },
  { id: 's4', name: '刘洋', role: '测试工程师', color: '#ef4444' },
  { id: 's5', name: '陈静', role: '运营', color: '#8b5cf6' },
];

const generateTranscript = (): TranscriptSegment[] => [
  { id: 't1', speakerId: 's1', startTime: '00:00:00', endTime: '00:02:15', text: '大家好，今天我们来讨论Q3产品迭代计划，首先我来介绍一下整体目标。我们需要在8月底之前完成用户中心的重构，提升用户体验。' },
  { id: 't2', speakerId: 's2', startTime: '00:02:15', endTime: '00:05:30', text: '技术方面我来确认一下，用户中心重构涉及到API的重新设计，我这边安排张三负责后端接口开发，截止日期定在7月15日可以吗？' },
  { id: 't3', speakerId: 's4', startTime: '00:05:30', endTime: '00:07:45', text: '测试这边我需要在7月20日拿到提测版本，这样我们有两周时间进行完整测试。赵六可以配合做自动化测试脚本的编写。' },
  { id: 't4', speakerId: 's3', startTime: '00:07:45', endTime: '00:10:00', text: '设计稿我会在本周内完成，最迟周五下午发给大家评审。新的UI风格会更简洁现代。' },
  { id: 't5', speakerId: 's5', startTime: '00:10:00', endTime: '00:12:30', text: '运营这边需要配合做用户调研，我这边安排下周三前完成100份用户访谈问卷的收集。' },
  { id: 't6', speakerId: 's1', startTime: '00:12:30', endTime: '00:15:00', text: '好的，那就这么定了。大家要注意时间节点，有问题及时同步。另外，安全审计的事情也不能忘，张伟你和安全部门对接一下，P0优先级，月底前完成。' },
];

export const mockMeetings: MeetingListItem[] = [
  {
    id: 'm1',
    title: 'Q3产品迭代规划会议',
    date: '2026-06-08',
    projectId: 'p1',
    speakers: mockSpeakers.slice(0, 5),
    topics: ['产品规划', '技术方案', '排期'],
    maskingApplied: true,
    status: 'extracted',
    actionItemCount: 5,
    createdAt: '2026-06-08T10:00:00Z',
    createdBy: '1',
  },
  {
    id: 'm2',
    title: '用户中心重构技术评审',
    date: '2026-06-09',
    projectId: 'p1',
    speakers: mockSpeakers.slice(0, 3),
    topics: ['技术架构', 'API设计'],
    maskingApplied: true,
    status: 'extracted',
    actionItemCount: 3,
    createdAt: '2026-06-09T14:00:00Z',
    createdBy: '2',
  },
  {
    id: 'm3',
    title: '每周站会',
    date: '2026-06-10',
    projectId: 'p1',
    speakers: mockSpeakers.slice(0, 4),
    topics: ['进度同步', '风险点'],
    maskingApplied: false,
    status: 'extracting',
    actionItemCount: 0,
    createdAt: '2026-06-10T09:30:00Z',
    createdBy: '2',
  },
  {
    id: 'm4',
    title: '安全合规讨论会',
    date: '2026-06-07',
    projectId: 'p2',
    speakers: [mockSpeakers[1], mockSpeakers[3]],
    topics: ['安全审计', '数据脱敏'],
    maskingApplied: true,
    status: 'failed',
    extractionError: '模型调用超时',
    actionItemCount: 0,
    createdAt: '2026-06-07T15:00:00Z',
    createdBy: '3',
  },
  {
    id: 'm5',
    title: '新功能需求评审',
    date: '2026-06-05',
    projectId: 'p2',
    speakers: mockSpeakers,
    topics: ['需求分析', '交互设计'],
    maskingApplied: true,
    status: 'created',
    actionItemCount: 0,
    createdAt: '2026-06-05T11:00:00Z',
    createdBy: '4',
  },
];

export const getMeetingDetail = (id: string): Meeting | undefined => {
  const meeting = mockMeetings.find((m) => m.id === id);
  if (!meeting) return undefined;
  return {
    ...meeting,
    transcript: generateTranscript(),
  };
};

export const mockActionItems: ActionItem[] = [
  {
    id: 'ai1',
    meetingId: 'm1',
    content: '完成用户中心重构的后端API接口开发',
    assignee: '4',
    assigneeStatus: 'ai_suggested',
    dueDate: '2026-07-15',
    topic: '技术方案',
    milestoneId: 'ms2',
    priority: 'P0',
    status: 'pending',
    fieldConfidences: [
      { field: 'content', confidence: 0.95, level: 'high' },
      { field: 'assignee', confidence: 0.62, level: 'medium', reason: '上下文提及"张三"，但未明确指定' },
      { field: 'dueDate', confidence: 0.98, level: 'high' },
      { field: 'topic', confidence: 0.88, level: 'high' },
      { field: 'priority', confidence: 0.75, level: 'medium' },
    ],
    evidence: [{ segmentId: 't2', startChar: 20, endChar: 45, quotedText: '张三负责后端接口开发' }],
    modelVersion: 'v1.2.0',
    missingFields: [],
    lowConfidenceFields: ['assignee'],
    remarks: '',
    version: 1,
    createdAt: '2026-06-08T11:00:00Z',
    updatedAt: '2026-06-08T11:00:00Z',
    updatedBy: 'system',
  },
  {
    id: 'ai2',
    meetingId: 'm1',
    content: '完成测试用例编写并准备自动化测试脚本',
    assignee: '5',
    assigneeStatus: 'confirmed',
    dueDate: '2026-07-20',
    topic: '质量保障',
    milestoneId: 'ms2',
    priority: 'P1',
    status: 'pending',
    fieldConfidences: [
      { field: 'content', confidence: 0.92, level: 'high' },
      { field: 'assignee', confidence: 0.96, level: 'high' },
      { field: 'dueDate', confidence: 0.89, level: 'high' },
      { field: 'topic', confidence: 0.71, level: 'medium' },
      { field: 'priority', confidence: 0.55, level: 'low', reason: '未明确提及优先级' },
    ],
    evidence: [{ segmentId: 't3', startChar: 10, endChar: 35, quotedText: '赵六配合做自动化测试脚本' }],
    modelVersion: 'v1.2.0',
    missingFields: [],
    lowConfidenceFields: ['priority'],
    remarks: '需要配合接口联调时间',
    version: 2,
    createdAt: '2026-06-08T11:00:00Z',
    updatedAt: '2026-06-09T09:00:00Z',
    updatedBy: '3',
  },
  {
    id: 'ai3',
    meetingId: 'm1',
    content: '完成用户中心新UI设计稿并组织评审',
    assignee: null,
    assigneeStatus: 'pending_assignment',
    dueDate: '2026-06-13',
    topic: '交互设计',
    milestoneId: 'ms1',
    priority: 'P1',
    status: 'pending',
    fieldConfidences: [
      { field: 'content', confidence: 0.94, level: 'high' },
      { field: 'assignee', confidence: 0.35, level: 'low', reason: '只提到"张伟"，但未确认参与人员' },
      { field: 'dueDate', confidence: 0.97, level: 'high' },
      { field: 'topic', confidence: 0.93, level: 'high' },
      { field: 'priority', confidence: 0.82, level: 'high' },
    ],
    evidence: [{ segmentId: 't4', startChar: 0, endChar: 25, quotedText: '设计稿本周内完成，最迟周五' }],
    modelVersion: 'v1.2.0',
    missingFields: ['assignee'],
    lowConfidenceFields: ['assignee'],
    remarks: '',
    version: 1,
    createdAt: '2026-06-08T11:00:00Z',
    updatedAt: '2026-06-08T11:00:00Z',
    updatedBy: 'system',
  },
  {
    id: 'ai4',
    meetingId: 'm1',
    content: '完成用户访谈问卷收集，至少100份有效样本',
    assignee: '5',
    assigneeStatus: 'ai_suggested',
    dueDate: '2026-06-17',
    topic: '用户研究',
    milestoneId: 'ms1',
    priority: 'P2',
    status: 'in_progress',
    fieldConfidences: [
      { field: 'content', confidence: 0.86, level: 'high' },
      { field: 'assignee', confidence: 0.48, level: 'low', reason: '未明确具体负责人' },
      { field: 'dueDate', confidence: 0.91, level: 'high' },
      { field: 'topic', confidence: 0.67, level: 'medium' },
      { field: 'priority', confidence: 0.63, level: 'medium' },
    ],
    evidence: [{ segmentId: 't5', startChar: 5, endChar: 30, quotedText: '下周三前完成100份用户访谈' }],
    modelVersion: 'v1.2.0',
    missingFields: [],
    lowConfidenceFields: ['assignee'],
    remarks: '',
    version: 1,
    createdAt: '2026-06-08T11:00:00Z',
    updatedAt: '2026-06-08T11:00:00Z',
    updatedBy: 'system',
  },
  {
    id: 'ai5',
    meetingId: 'm1',
    content: '对接安全部门完成安全审计工作',
    assignee: '4',
    assigneeStatus: 'pending_assignment',
    dueDate: '2026-06-30',
    topic: '安全合规',
    milestoneId: 'ms3',
    priority: 'P0',
    status: 'pending',
    fieldConfidences: [
      { field: 'content', confidence: 0.98, level: 'high' },
      { field: 'assignee', confidence: 0.42, level: 'low', reason: '"张伟"上下文不明确' },
      { field: 'dueDate', confidence: 0.99, level: 'high' },
      { field: 'topic', confidence: 0.96, level: 'high' },
      { field: 'priority', confidence: 0.98, level: 'high' },
    ],
    evidence: [{ segmentId: 't6', startChar: 50, endChar: 75, quotedText: '安全审计的事情，月底前完成' }],
    modelVersion: 'v1.2.0',
    missingFields: [],
    lowConfidenceFields: ['assignee'],
    remarks: 'P0优先级，必须按时完成',
    version: 1,
    createdAt: '2026-06-08T11:00:00Z',
    updatedAt: '2026-06-08T11:00:00Z',
    updatedBy: 'system',
  },
  {
    id: 'ai6',
    meetingId: 'm2',
    content: '完成数据库迁移方案设计',
    assignee: '4',
    assigneeStatus: 'confirmed',
    dueDate: '2026-06-20',
    topic: '技术方案',
    milestoneId: 'ms2',
    priority: 'P1',
    status: 'confirmed',
    fieldConfidences: [
      { field: 'content', confidence: 0.97, level: 'high' },
      { field: 'assignee', confidence: 0.95, level: 'high' },
      { field: 'dueDate', confidence: 0.94, level: 'high' },
      { field: 'topic', confidence: 0.92, level: 'high' },
      { field: 'priority', confidence: 0.90, level: 'high' },
    ],
    evidence: [],
    modelVersion: 'v1.2.0',
    missingFields: [],
    lowConfidenceFields: [],
    remarks: '',
    version: 3,
    createdAt: '2026-06-09T16:00:00Z',
    updatedAt: '2026-06-09T18:00:00Z',
    updatedBy: '2',
  },
  {
    id: 'ai7',
    meetingId: 'm2',
    content: '编写接口文档并同步给前端团队',
    assignee: '4',
    assigneeStatus: 'confirmed',
    dueDate: '2026-06-25',
    topic: '文档',
    milestoneId: 'ms2',
    priority: 'P2',
    status: 'assigned',
    fieldConfidences: [
      { field: 'content', confidence: 0.91, level: 'high' },
      { field: 'assignee', confidence: 0.93, level: 'high' },
      { field: 'dueDate', confidence: 0.88, level: 'high' },
      { field: 'topic', confidence: 0.79, level: 'medium' },
      { field: 'priority', confidence: 0.85, level: 'high' },
    ],
    evidence: [],
    modelVersion: 'v1.2.0',
    missingFields: [],
    lowConfidenceFields: [],
    remarks: '',
    version: 2,
    createdAt: '2026-06-09T16:00:00Z',
    updatedAt: '2026-06-09T17:30:00Z',
    updatedBy: '2',
  },
  {
    id: 'ai8',
    meetingId: 'm2',
    content: '准备技术评审PPT材料',
    assignee: '2',
    assigneeStatus: 'confirmed',
    dueDate: '2026-06-12',
    topic: '评审材料',
    milestoneId: 'ms1',
    priority: 'P1',
    status: 'completed',
    fieldConfidences: [
      { field: 'content', confidence: 0.94, level: 'high' },
      { field: 'assignee', confidence: 0.98, level: 'high' },
      { field: 'dueDate', confidence: 0.96, level: 'high' },
      { field: 'topic', confidence: 0.87, level: 'high' },
      { field: 'priority', confidence: 0.91, level: 'high' },
    ],
    evidence: [],
    modelVersion: 'v1.2.0',
    missingFields: [],
    lowConfidenceFields: [],
    remarks: '',
    version: 1,
    createdAt: '2026-06-09T16:00:00Z',
    updatedAt: '2026-06-11T10:00:00Z',
    updatedBy: '2',
  },
];

export const mockMilestones: Milestone[] = [
  {
    id: 'ms1',
    projectId: 'p1',
    title: '设计与规划阶段',
    description: '完成需求分析、UI设计、技术方案评审',
    dueDate: '2026-06-20',
    status: 'in_progress',
    actionItemIds: ['ai3', 'ai4', 'ai8'],
    createdAt: '2026-06-01T00:00:00Z',
  },
  {
    id: 'ms2',
    projectId: 'p1',
    title: '开发与测试阶段',
    description: '前后端开发、接口联调、测试执行',
    dueDate: '2026-07-30',
    status: 'at_risk',
    actionItemIds: ['ai1', 'ai2', 'ai6', 'ai7'],
    createdAt: '2026-06-01T00:00:00Z',
  },
  {
    id: 'ms3',
    projectId: 'p1',
    title: '安全合规审计',
    description: '完成安全审计、数据脱敏、合规检查',
    dueDate: '2026-06-30',
    status: 'planned',
    actionItemIds: ['ai5'],
    createdAt: '2026-06-01T00:00:00Z',
  },
  {
    id: 'ms4',
    projectId: 'p1',
    title: '上线准备',
    description: '灰度发布、全量上线、运维监控',
    dueDate: '2026-08-15',
    status: 'planned',
    actionItemIds: [],
    createdAt: '2026-06-01T00:00:00Z',
  },
  {
    id: 'ms5',
    projectId: 'p2',
    title: 'V2版本功能开发',
    description: '完成新功能开发与测试',
    dueDate: '2026-05-20',
    status: 'completed',
    actionItemIds: [],
    createdAt: '2026-04-01T00:00:00Z',
  },
  {
    id: 'ms6',
    projectId: 'p2',
    title: '历史遗留系统迁移',
    description: '旧系统数据迁移与功能下线',
    dueDate: '2026-04-10',
    status: 'cancelled',
    actionItemIds: [],
    createdAt: '2026-03-01T00:00:00Z',
  },
];

export const mockModelVersions: ModelVersion[] = [
  {
    id: 'mv1',
    name: 'v1.2.0',
    openaiFinetuneId: 'ft:gpt-4o-mini-2024-07-18:org::abc123',
    baseModel: 'gpt-4o-mini-2024-07-18',
    status: 'ready',
    isActive: true,
    metrics: { precision: 0.892, recall: 0.861, f1: 0.876 },
    createdAt: '2026-05-20T10:00:00Z',
  },
  {
    id: 'mv2',
    name: 'v1.1.0',
    openaiFinetuneId: 'ft:gpt-4o-mini-2024-07-18:org::def456',
    baseModel: 'gpt-4o-mini-2024-07-18',
    status: 'ready',
    isActive: false,
    metrics: { precision: 0.845, recall: 0.823, f1: 0.834 },
    createdAt: '2026-04-15T10:00:00Z',
  },
  {
    id: 'mv3',
    name: 'v1.3.0-experimental',
    baseModel: 'gpt-4o-2024-08-06',
    status: 'running',
    isActive: false,
    createdAt: '2026-06-09T08:00:00Z',
  },
  {
    id: 'mv4',
    name: 'v1.0.0',
    openaiFinetuneId: 'ft:gpt-4o-mini-2024-07-18:org::ghi789',
    baseModel: 'gpt-4o-mini-2024-07-18',
    status: 'ready',
    isActive: false,
    metrics: { precision: 0.786, recall: 0.751, f1: 0.768 },
    createdAt: '2026-03-01T10:00:00Z',
  },
  {
    id: 'mv5',
    name: 'v1.2.1-hotfix',
    baseModel: 'gpt-4o-mini-2024-07-18',
    status: 'failed',
    isActive: false,
    createdAt: '2026-06-05T14:00:00Z',
  },
];

export const mockEvaluationReport: EvaluationReport = {
  generatedAt: '2026-06-10T08:00:00Z',
  totalSamples: 1248,
  overall: { precision: 0.892, recall: 0.861, f1: 0.876 },
  perField: {
    content: { precision: 0.945, recall: 0.928, f1: 0.936, accuracy: 0.941 },
    assignee: { precision: 0.821, recall: 0.785, f1: 0.803, accuracy: 0.812 },
    dueDate: { precision: 0.912, recall: 0.889, f1: 0.900, accuracy: 0.905 },
    topic: { precision: 0.856, recall: 0.812, f1: 0.833, accuracy: 0.841 },
    priority: { precision: 0.878, recall: 0.845, f1: 0.861, accuracy: 0.869 },
  },
  errorDistribution: {
    missing: 124,
    lowConfidence: 256,
    wrongAssignee: 89,
    wrongDate: 67,
    other: 53,
  },
  modelVersion: 'v1.2.0',
};

export const mockMaskingRules: MaskingRule[] = [
  { id: 'mr1', name: '手机号脱敏', type: 'regex', pattern: '1[3-9]\\d{9}', replacement: '[PHONE]', enabled: true },
  { id: 'mr2', name: '邮箱脱敏', type: 'regex', pattern: '[\\w.-]+@[\\w.-]+\\.\\w+', replacement: '[EMAIL]', enabled: true },
  { id: 'mr3', name: '身份证号', type: 'regex', pattern: '\\d{17}[\\dXx]', replacement: '[ID_CARD]', enabled: true },
  { id: 'mr4', name: '银行卡号', type: 'regex', pattern: '\\d{16,19}', replacement: '[BANK_CARD]', enabled: false },
  { id: 'mr5', name: '内部代号ProjectX', type: 'keyword', pattern: 'ProjectX', replacement: '[CONFIDENTIAL_PROJECT]', enabled: true },
  { id: 'mr6', name: '客户公司名称', type: 'keyword', pattern: 'Acme Corp', replacement: '[CLIENT_A]', enabled: true },
];

const now = new Date();
export const mockApiCallLogs: ApiCallLog[] = Array.from({ length: 50 }, (_, i) => {
  const t = new Date(now.getTime() - (49 - i) * 30 * 60 * 1000);
  const endpoints = ['/api/meetings/:id/extract', '/api/action-items/batch', '/api/auth/login', '/api/meetings'];
  const models = ['gpt-4o-mini-2024-07-18', 'gpt-4o-2024-08-06', 'ft:gpt-4o-mini:org::abc123'];
  return {
    id: `log${i}`,
    endpoint: endpoints[i % 4],
    model: models[i % 3],
    promptTokens: 800 + Math.floor(Math.random() * 2000),
    completionTokens: 200 + Math.floor(Math.random() * 800),
    totalTokens: 1000 + Math.floor(Math.random() * 2500),
    latencyMs: 300 + Math.floor(Math.random() * 2500),
    statusCode: Math.random() > 0.08 ? 200 : (Math.random() > 0.5 ? 429 : 500),
    userId: ['1', '2', '3', '4', '5'][i % 5],
    timestamp: t.toISOString(),
  };
});

export const mockVersionHistories: Record<string, VersionHistory[]> = {
  ai2: [
    {
      id: 'vh1',
      actionItemId: 'ai2',
      version: 1,
      snapshot: { status: 'pending', remarks: '' },
      diff: { status: { old: 'draft', new: 'pending' } },
      operatorId: 'system',
      operatorName: '系统自动提取',
      timestamp: '2026-06-08T11:00:00Z',
      remark: '初始版本',
    },
    {
      id: 'vh2',
      actionItemId: 'ai2',
      version: 2,
      snapshot: { assigneeStatus: 'confirmed', remarks: '需要配合接口联调时间', updatedBy: '3' },
      diff: {
        assigneeStatus: { old: 'ai_suggested', new: 'confirmed' },
        remarks: { old: '', new: '需要配合接口联调时间' },
      },
      operatorId: '3',
      operatorName: '质量审核员',
      timestamp: '2026-06-09T09:00:00Z',
      remark: '确认负责人，添加备注',
    },
  ],
  ai6: [
    {
      id: 'vh3',
      actionItemId: 'ai6',
      version: 1,
      snapshot: { status: 'pending', version: 1 },
      diff: { status: { old: 'draft', new: 'pending' } },
      operatorId: 'system',
      operatorName: '系统自动提取',
      timestamp: '2026-06-09T16:00:00Z',
      remark: '初始版本',
    },
    {
      id: 'vh4',
      actionItemId: 'ai6',
      version: 2,
      snapshot: { assignee: '4', assigneeStatus: 'confirmed' },
      diff: { assigneeStatus: { old: 'ai_suggested', new: 'confirmed' } },
      operatorId: '2',
      operatorName: '项目经理',
      timestamp: '2026-06-09T17:00:00Z',
      remark: '确认负责人',
    },
    {
      id: 'vh5',
      actionItemId: 'ai6',
      version: 3,
      snapshot: { status: 'confirmed', version: 3 },
      diff: { status: { old: 'pending', new: 'confirmed' } },
      operatorId: '2',
      operatorName: '项目经理',
      timestamp: '2026-06-09T18:00:00Z',
      remark: '确认行动项',
    },
  ],
};
