# Generated by Django 4.2.7 on 2026-06-05 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('check_no', models.CharField(max_length=30, unique=True, verbose_name='盘点单号')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('confirmed', '已确认'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态')),
                ('check_date', models.DateTimeField(blank=True, null=True, verbose_name='盘点时间')),
                ('total_diff_quantity', models.IntegerField(default=0, verbose_name='差异总数')),
                ('total_diff_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='差异总金额')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='core.user', verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='core.user', verbose_name='更新人')),
            ],
            options={
                'verbose_name': '盘点单',
                'verbose_name_plural': '盘点单',
                'db_table': 'stock_check',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('in_no', models.CharField(max_length=30, unique=True, verbose_name='入库单号')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('confirmed', '已确认'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态')),
                ('total_quantity', models.IntegerField(default=0, verbose_name='总数量')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='总金额')),
                ('in_date', models.DateTimeField(blank=True, null=True, verbose_name='入库时间')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='core.user', verbose_name='创建人')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_ins', to='books.supplier', verbose_name='供应商')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='core.user', verbose_name='更新人')),
            ],
            options={
                'verbose_name': '入库单',
                'verbose_name_plural': '入库单',
                'db_table': 'stock_in',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('out_no', models.CharField(max_length=30, unique=True, verbose_name='出库单号')),
                ('type', models.CharField(choices=[('sale', '销售出库'), ('damage', '损坏出库'), ('lost', '丢失出库'), ('other', '其他出库')], default='sale', max_length=20, verbose_name='出库类型')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('confirmed', '已确认'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态')),
                ('total_quantity', models.IntegerField(default=0, verbose_name='总数量')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='总金额')),
                ('out_date', models.DateTimeField(blank=True, null=True, verbose_name='出库时间')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='core.user', verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='core.user', verbose_name='更新人')),
            ],
            options={
                'verbose_name': '出库单',
                'verbose_name_plural': '出库单',
                'db_table': 'stock_out',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockOutItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='小计')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_out_items', to='books.book', verbose_name='图书')),
                ('stock_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stockout', verbose_name='出库单')),
            ],
            options={
                'verbose_name': '出库明细',
                'verbose_name_plural': '出库明细',
                'db_table': 'stock_out_item',
            },
        ),
        migrations.CreateModel(
            name='StockLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('in', '入库'), ('out', '出库'), ('check', '盘点调整'), ('adjust', '手工调整')], max_length=20, verbose_name='类型')),
                ('quantity_before', models.IntegerField(verbose_name='变动前数量')),
                ('quantity_change', models.IntegerField(verbose_name='变动数量')),
                ('quantity_after', models.IntegerField(verbose_name='变动后数量')),
                ('related_type', models.CharField(blank=True, max_length=50, verbose_name='关联单据类型')),
                ('related_id', models.IntegerField(blank=True, null=True, verbose_name='关联单据ID')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_logs', to='books.book', verbose_name='图书')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_logs', to='core.user', verbose_name='操作人')),
            ],
            options={
                'verbose_name': '库存日志',
                'verbose_name_plural': '库存日志',
                'db_table': 'stock_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockInItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='进货价')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='小计')),
                ('batch_no', models.CharField(blank=True, max_length=50, verbose_name='批次号')),
                ('expire_date', models.DateField(blank=True, null=True, verbose_name='有效期')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_in_items', to='books.book', verbose_name='图书')),
                ('stock_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stockin', verbose_name='入库单')),
            ],
            options={
                'verbose_name': '入库明细',
                'verbose_name_plural': '入库明细',
                'db_table': 'stock_in_item',
            },
        ),
        migrations.CreateModel(
            name='StockCheckItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_quantity', models.IntegerField(verbose_name='系统库存')),
                ('actual_quantity', models.IntegerField(verbose_name='实际库存')),
                ('diff_quantity', models.IntegerField(verbose_name='差异数量')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='成本价')),
                ('diff_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='差异金额')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_items', to='books.book', verbose_name='图书')),
                ('stock_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stockcheck', verbose_name='盘点单')),
            ],
            options={
                'verbose_name': '盘点明细',
                'verbose_name_plural': '盘点明细',
                'db_table': 'stock_check_item',
            },
        ),
    ]
