# Generated by Django 4.2.30 on 2026-06-05 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=200, verbose_name='事件标题')),
                ('description', models.TextField(verbose_name='事件描述')),
                ('incident_time', models.DateTimeField(verbose_name='发生时间')),
                ('location', models.CharField(max_length=200, verbose_name='发生地点')),
                ('severity', models.CharField(choices=[('minor', '轻微'), ('moderate', '一般'), ('serious', '严重'), ('critical', '重大')], default='moderate', max_length=20, verbose_name='严重程度')),
                ('status', models.CharField(choices=[('reported', '已上报'), ('investigating', '调查中'), ('resolved', '已处理'), ('closed', '已归档')], default='reported', max_length=20, verbose_name='状态')),
                ('involved_people', models.TextField(blank=True, verbose_name='涉事人员')),
                ('injuries', models.TextField(blank=True, verbose_name='人员伤亡情况')),
                ('immediate_actions', models.TextField(blank=True, verbose_name='即时处理措施')),
                ('root_cause', models.TextField(blank=True, verbose_name='根本原因分析')),
                ('corrective_actions', models.TextField(blank=True, verbose_name='纠正措施')),
                ('preventive_measures', models.TextField(blank=True, verbose_name='预防措施')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='归档时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_incidents', to='equipment.equipment', verbose_name='关联设备')),
                ('investigated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigated_incidents', to=settings.AUTH_USER_MODEL, verbose_name='调查人')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_incidents', to=settings.AUTH_USER_MODEL, verbose_name='上报人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '安全事件',
                'verbose_name_plural': '安全事件',
                'ordering': ['-incident_time'],
            },
        ),
        migrations.CreateModel(
            name='SafetyAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='safety_attachments/', verbose_name='附件')),
                ('file_name', models.CharField(max_length=255, verbose_name='文件名')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='safety.safetyincident', verbose_name='安全事件')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'verbose_name': '安全附件',
                'verbose_name_plural': '安全附件',
            },
        ),
        migrations.CreateModel(
            name='SafetyTrainingRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=200, verbose_name='培训标题')),
                ('description', models.TextField(blank=True, verbose_name='培训内容')),
                ('training_date', models.DateField(verbose_name='培训日期')),
                ('trainer', models.CharField(max_length=100, verbose_name='培训师')),
                ('duration_hours', models.DecimalField(decimal_places=1, default=1.0, max_digits=4, verbose_name='时长(小时)')),
                ('passed', models.BooleanField(default=True, verbose_name='是否通过')),
                ('certificate_number', models.CharField(blank=True, max_length=50, verbose_name='证书编号')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='有效期至')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_training_records', to=settings.AUTH_USER_MODEL, verbose_name='参训人')),
            ],
            options={
                'verbose_name': '安全培训记录',
                'verbose_name_plural': '安全培训记录',
                'ordering': ['-training_date'],
                'indexes': [models.Index(fields=['user', 'training_date'], name='safety_safe_user_id_cec384_idx')],
            },
        ),
        migrations.CreateModel(
            name='SafetyInspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=200, verbose_name='检查标题')),
                ('description', models.TextField(blank=True, verbose_name='检查描述')),
                ('scheduled_date', models.DateField(verbose_name='计划日期')),
                ('performed_date', models.DateField(blank=True, null=True, verbose_name='执行日期')),
                ('status', models.CharField(choices=[('scheduled', '计划中'), ('in_progress', '进行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='scheduled', max_length=20, verbose_name='状态')),
                ('findings', models.TextField(blank=True, verbose_name='检查发现')),
                ('recommendations', models.TextField(blank=True, verbose_name='建议')),
                ('follow_up_date', models.DateField(blank=True, null=True, verbose_name='跟进日期')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_inspections', to=settings.AUTH_USER_MODEL, verbose_name='执行人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '安全检查',
                'verbose_name_plural': '安全检查',
                'ordering': ['-scheduled_date'],
                'indexes': [models.Index(fields=['status', 'scheduled_date'], name='safety_safe_status_198732_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='safetyincident',
            index=models.Index(fields=['severity', 'status'], name='safety_safe_severit_91d616_idx'),
        ),
        migrations.AddIndex(
            model_name='safetyincident',
            index=models.Index(fields=['equipment', 'incident_time'], name='safety_safe_equipme_98e4a7_idx'),
        ),
        migrations.AddIndex(
            model_name='safetyincident',
            index=models.Index(fields=['reporter', 'created_at'], name='safety_safe_reporte_7a322c_idx'),
        ),
        migrations.AddIndex(
            model_name='safetyincident',
            index=models.Index(fields=['incident_time'], name='safety_safe_inciden_01c535_idx'),
        ),
    ]
