# Generated by Django 4.2.30 on 2026-06-06 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('exhibitions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='日期')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '每日日程',
                'verbose_name_plural': '每日日程',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('info', '信息'), ('warning', '警告'), ('error', '错误'), ('success', '成功')], default='info', max_length=20, verbose_name='类型')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('message', models.TextField(verbose_name='消息内容')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='阅读时间')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('material', '物料冲突'), ('hall', '展厅冲突'), ('time_overlap', '时间重叠')], max_length=50, verbose_name='冲突类型')),
                ('severity', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('critical', '严重')], default='medium', max_length=20, verbose_name='严重程度')),
                ('conflict_date', models.DateField(verbose_name='冲突日期')),
                ('description', models.TextField(verbose_name='冲突描述')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='是否已解决')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='解决时间')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='解决备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('borrow_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conflicts', to='exhibitions.borroworder', verbose_name='借用单')),
                ('conflicting_borrow_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conflicting_orders', to='exhibitions.borroworder', verbose_name='冲突借用单')),
                ('conflicting_exhibition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conflicting_exhibitions', to='exhibitions.exhibition', verbose_name='冲突展览')),
                ('exhibition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='exhibitions.exhibition', verbose_name='展览')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conflicts', to='inventory.material', verbose_name='冲突物料')),
            ],
            options={
                'verbose_name': '日程冲突',
                'verbose_name_plural': '日程冲突',
                'ordering': ['-created_at'],
            },
        ),
    ]
