# Generated by Django 4.2.7 on 2026-06-05 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('mood', models.CharField(blank=True, choices=[('happy', '开心'), ('calm', '平静'), ('fussy', '烦躁'), ('crying', '哭闹')], default='', max_length=10, verbose_name='情绪')),
                ('appetite', models.CharField(blank=True, choices=[('good', '好'), ('normal', '一般'), ('poor', '差')], default='', max_length=10, verbose_name='食欲')),
                ('nap_start', models.TimeField(blank=True, null=True, verbose_name='午睡开始')),
                ('nap_end', models.TimeField(blank=True, null=True, verbose_name='午睡结束')),
                ('nap_quality', models.CharField(blank=True, default='', max_length=20, verbose_name='午睡质量')),
                ('breakfast', models.TextField(blank=True, default='', verbose_name='早餐')),
                ('lunch', models.TextField(blank=True, default='', verbose_name='午餐')),
                ('snack', models.TextField(blank=True, default='', verbose_name='点心')),
                ('activities', models.TextField(blank=True, default='', verbose_name='活动记录')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_records', to='children.child', verbose_name='儿童')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_daily_records', to=settings.AUTH_USER_MODEL, verbose_name='记录人')),
            ],
            options={
                'verbose_name': '每日记录',
                'verbose_name_plural': '每日记录',
                'db_table': 'daily_records_dailyrecord',
            },
        ),
        migrations.CreateModel(
            name='GrowthPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='growth_photos/%Y/%m/', verbose_name='照片')),
                ('caption', models.CharField(blank=True, default='', max_length=200, verbose_name='说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='daily_records.dailyrecord', verbose_name='每日记录')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'verbose_name': '成长照片',
                'verbose_name_plural': '成长照片',
                'db_table': 'daily_records_growthphoto',
            },
        ),
        migrations.AddIndex(
            model_name='dailyrecord',
            index=models.Index(fields=['date'], name='idx_dailyrecord_date'),
        ),
        migrations.AddIndex(
            model_name='dailyrecord',
            index=models.Index(fields=['child', 'date'], name='idx_dailyrecord_child_date'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyrecord',
            unique_together={('child', 'date')},
        ),
    ]
