# Generated by Django 4.2.7 on 2026-06-05 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('books', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('reservation_no', models.CharField(max_length=30, unique=True, verbose_name='预留单号')),
                ('contact_name', models.CharField(max_length=100, verbose_name='联系人姓名')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认'), ('completed', '已完成'), ('expired', '已过期'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('expire_at', models.DateTimeField(verbose_name='过期时间')),
                ('total_quantity', models.IntegerField(default=0, verbose_name='总数量')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='总金额')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='取消时间')),
                ('cancelled_reason', models.TextField(blank=True, verbose_name='取消原因')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='core.user', verbose_name='创建人')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='members.member', verbose_name='会员')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='core.user', verbose_name='更新人')),
            ],
            options={
                'verbose_name': '预留单',
                'verbose_name_plural': '预留单',
                'db_table': 'reservation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReservationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='小计')),
                ('picked_up', models.BooleanField(default=False, verbose_name='是否已取')),
                ('picked_up_at', models.DateTimeField(blank=True, null=True, verbose_name='取书时间')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_items', to='books.book', verbose_name='图书')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reservations.reservation', verbose_name='预留单')),
            ],
            options={
                'verbose_name': '预留明细',
                'verbose_name_plural': '预留明细',
                'db_table': 'reservation_item',
            },
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['status'], name='reservation_status_88445b_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['expire_at'], name='reservation_expire__e3a6b4_idx'),
        ),
    ]
