# Generated by Django 4.2.7 on 2026-06-05 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('target_type', models.CharField(choices=[('all', '全体'), ('class', '按班级'), ('individual', '个人')], default='all', max_length=20, verbose_name='目标类型')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='紧急')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notifications', to=settings.AUTH_USER_MODEL, verbose_name='发布人')),
                ('target_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='children.classgroup', verbose_name='目标班级')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targeted_notifications', to=settings.AUTH_USER_MODEL, verbose_name='目标用户')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'db_table': 'notifications_notification',
            },
        ),
        migrations.CreateModel(
            name='NotificationRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True, verbose_name='阅读时间')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='notifications.notification', verbose_name='通知')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_reads', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '通知已读',
                'verbose_name_plural': '通知已读',
                'db_table': 'notifications_notificationread',
                'unique_together': {('notification', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['target_type', 'created_at'], name='idx_notif_type_time'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['target_user', 'created_at'], name='idx_notif_user_time'),
        ),
    ]
