# Generated by Django 5.2.15 on 2026-06-16 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=20, verbose_name='座位号')),
                ('row', models.IntegerField(blank=True, null=True, verbose_name='行')),
                ('col', models.IntegerField(blank=True, null=True, verbose_name='列')),
                ('has_power', models.BooleanField(default=False, verbose_name='是否有电源')),
                ('has_window', models.BooleanField(default=False, verbose_name='是否靠窗')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '座位',
                'verbose_name_plural': '座位',
                'ordering': ['study_room', 'seat_number'],
            },
        ),
        migrations.CreateModel(
            name='StudyRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='自习室名称')),
                ('building', models.CharField(max_length=50, verbose_name='所在楼栋')),
                ('floor', models.IntegerField(verbose_name='楼层')),
                ('total_seats', models.IntegerField(verbose_name='总座位数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('open_time', models.TimeField(default='07:00', verbose_name='开放时间')),
                ('close_time', models.TimeField(default='22:00', verbose_name='关闭时间')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '自习室',
                'verbose_name_plural': '自习室',
                'ordering': ['building', 'floor', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SeatReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='预约日期')),
                ('start_time', models.TimeField(verbose_name='开始时间')),
                ('end_time', models.TimeField(verbose_name='结束时间')),
                ('status', models.CharField(choices=[('reserved', '已预约'), ('checked_in', '已签到'), ('cancelled', '已取消'), ('no_show', '未签到'), ('completed', '已完成')], default='reserved', max_length=20, verbose_name='状态')),
                ('reserved_at', models.DateTimeField(auto_now_add=True, verbose_name='预约时间')),
                ('checked_in_at', models.DateTimeField(blank=True, null=True, verbose_name='签到时间')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='取消时间')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_reservations', to=settings.AUTH_USER_MODEL, verbose_name='取消人')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='rooms.seat', verbose_name='座位')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_reservations', to=settings.AUTH_USER_MODEL, verbose_name='预约人')),
            ],
            options={
                'verbose_name': '座位预约',
                'verbose_name_plural': '座位预约',
                'ordering': ['-date', '-reserved_at'],
            },
        ),
        migrations.CreateModel(
            name='CheckInRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_type', models.CharField(choices=[('seat', '座位签到'), ('activity', '活动签到'), ('duty', '值班签到')], default='seat', max_length=20, verbose_name='签到类型')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='签到地点')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='签到时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to=settings.AUTH_USER_MODEL, verbose_name='签到人')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rooms.seatreservation', verbose_name='关联预约')),
            ],
            options={
                'verbose_name': '签到记录',
                'verbose_name_plural': '签到记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='seat',
            name='study_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='rooms.studyroom', verbose_name='自习室'),
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('study_room', 'seat_number')},
        ),
    ]
