/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root';
import { Route as BookImport } from './routes/book';
import { Route as AdminImport } from './routes/admin';
import { Route as IndexImport } from './routes/index';
import { Route as AdminIndexImport } from './routes/admin/index';
import { Route as AdminRescheduleImport } from './routes/admin/reschedule';
import { Route as AdminReviewsImport } from './routes/admin/reviews';
import { Route as AdminRefundsImport } from './routes/admin/refunds';
import { Route as AdminOrdersImport } from './routes/admin/orders';
import { Route as AdminTechniciansImport } from './routes/admin/technicians';
import { Route as AdminAnalyticsImport } from './routes/admin/analytics';
import { Route as AdminOrdersIdImport } from './routes/admin/orders.$id';

// Create/Update Routes

const BookRoute = BookImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRoute,
} as any);

const AdminRoute = AdminImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any);

const AdminIndexRoute = AdminIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any);

const AdminRescheduleRoute = AdminRescheduleImport.update({
  id: '/reschedule',
  path: '/reschedule',
  getParentRoute: () => AdminRoute,
} as any);

const AdminReviewsRoute = AdminReviewsImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any);

const AdminRefundsRoute = AdminRefundsImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => AdminRoute,
} as any);

const AdminOrdersRoute = AdminOrdersImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any);

const AdminTechniciansRoute = AdminTechniciansImport.update({
  id: '/technicians',
  path: '/technicians',
  getParentRoute: () => AdminRoute,
} as any);

const AdminAnalyticsRoute = AdminAnalyticsImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any);

const AdminOrdersIdRoute = AdminOrdersIdImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => AdminRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    '/admin': {
      preLoaderRoute: typeof AdminImport;
      parentRoute: typeof rootRoute;
    };
    '/book': {
      preLoaderRoute: typeof BookImport;
      parentRoute: typeof rootRoute;
    };
    '/admin/': {
      preLoaderRoute: typeof AdminIndexImport;
      parentRoute: typeof AdminImport;
    };
    '/admin/analytics': {
      preLoaderRoute: typeof AdminAnalyticsImport;
      parentRoute: typeof AdminImport;
    };
    '/admin/orders': {
      preLoaderRoute: typeof AdminOrdersImport;
      parentRoute: typeof AdminImport;
    };
    '/admin/refunds': {
      preLoaderRoute: typeof AdminRefundsImport;
      parentRoute: typeof AdminImport;
    };
    '/admin/reschedule': {
      preLoaderRoute: typeof AdminRescheduleImport;
      parentRoute: typeof AdminImport;
    };
    '/admin/reviews': {
      preLoaderRoute: typeof AdminReviewsImport;
      parentRoute: typeof AdminImport;
    };
    '/admin/technicians': {
      preLoaderRoute: typeof AdminTechniciansImport;
      parentRoute: typeof AdminImport;
    };
    '/admin/orders/$id': {
      preLoaderRoute: typeof AdminOrdersIdImport;
      parentRoute: typeof AdminImport;
    };
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AdminRoute.addChildren([
    AdminIndexRoute,
    AdminAnalyticsRoute,
    AdminOrdersRoute,
    AdminOrdersIdRoute,
    AdminRefundsRoute,
    AdminRescheduleRoute,
    AdminReviewsRoute,
    AdminTechniciansRoute,
  ]),
  BookRoute,
]);

/* prettier-ignore-end */
