/* eslint-disable */
// This file was auto-generated by TanStack Router.

import { Route as rootRoute } from './routes/__root';
import { Route as indexImport } from './routes/index';
import { Route as loginImport } from './routes/login';
import { Route as apartmentsImport } from './routes/apartments';
import { Route as customersImport } from './routes/customers';
import { Route as viewingsImport } from './routes/viewings';
import { Route as followupsImport } from './routes/followups';
import { Route as leasesImport } from './routes/leases';
import { Route as depositsImport } from './routes/deposits';
import { Route as remindersImport } from './routes/reminders';
import { Route as todosImport } from './routes/todos';
import { Route as searchImport } from './routes/search';
import { Route as reportsImport } from './routes/reports';
import { Route as usersImport } from './routes/users';

const indexRoute = indexImport.update({
  getParentRoute: () => rootRoute,
} as any);

const loginRoute = loginImport.update({
  getParentRoute: () => rootRoute,
} as any);

const apartmentsRoute = apartmentsImport.update({
  getParentRoute: () => rootRoute,
} as any);

const customersRoute = customersImport.update({
  getParentRoute: () => rootRoute,
} as any);

const viewingsRoute = viewingsImport.update({
  getParentRoute: () => rootRoute,
} as any);

const followupsRoute = followupsImport.update({
  getParentRoute: () => rootRoute,
} as any);

const leasesRoute = leasesImport.update({
  getParentRoute: () => rootRoute,
} as any);

const depositsRoute = depositsImport.update({
  getParentRoute: () => rootRoute,
} as any);

const remindersRoute = remindersImport.update({
  getParentRoute: () => rootRoute,
} as any);

const todosRoute = todosImport.update({
  getParentRoute: () => rootRoute,
} as any);

const searchRoute = searchImport.update({
  getParentRoute: () => rootRoute,
} as any);

const reportsRoute = reportsImport.update({
  getParentRoute: () => rootRoute,
} as any);

const usersRoute = usersImport.update({
  getParentRoute: () => rootRoute,
} as any);

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof indexImport;
      parentRoute: typeof rootRoute;
    };
    '/login': {
      id: '/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof loginImport;
      parentRoute: typeof rootRoute;
    };
    '/apartments': {
      id: '/apartments';
      path: '/apartments';
      fullPath: '/apartments';
      preLoaderRoute: typeof apartmentsImport;
      parentRoute: typeof rootRoute;
    };
    '/customers': {
      id: '/customers';
      path: '/customers';
      fullPath: '/customers';
      preLoaderRoute: typeof customersImport;
      parentRoute: typeof rootRoute;
    };
    '/viewings': {
      id: '/viewings';
      path: '/viewings';
      fullPath: '/viewings';
      preLoaderRoute: typeof viewingsImport;
      parentRoute: typeof rootRoute;
    };
    '/followups': {
      id: '/followups';
      path: '/followups';
      fullPath: '/followups';
      preLoaderRoute: typeof followupsImport;
      parentRoute: typeof rootRoute;
    };
    '/leases': {
      id: '/leases';
      path: '/leases';
      fullPath: '/leases';
      preLoaderRoute: typeof leasesImport;
      parentRoute: typeof rootRoute;
    };
    '/deposits': {
      id: '/deposits';
      path: '/deposits';
      fullPath: '/deposits';
      preLoaderRoute: typeof depositsImport;
      parentRoute: typeof rootRoute;
    };
    '/reminders': {
      id: '/reminders';
      path: '/reminders';
      fullPath: '/reminders';
      preLoaderRoute: typeof remindersImport;
      parentRoute: typeof rootRoute;
    };
    '/todos': {
      id: '/todos';
      path: '/todos';
      fullPath: '/todos';
      preLoaderRoute: typeof todosImport;
      parentRoute: typeof rootRoute;
    };
    '/search': {
      id: '/search';
      path: '/search';
      fullPath: '/search';
      preLoaderRoute: typeof searchImport;
      parentRoute: typeof rootRoute;
    };
    '/reports': {
      id: '/reports';
      path: '/reports';
      fullPath: '/reports';
      preLoaderRoute: typeof reportsImport;
      parentRoute: typeof rootRoute;
    };
    '/users': {
      id: '/users';
      path: '/users';
      fullPath: '/users';
      preLoaderRoute: typeof usersImport;
      parentRoute: typeof rootRoute;
    };
  }
}

export const routeTree = rootRoute.addChildren({
  indexRoute,
  loginRoute,
  apartmentsRoute,
  customersRoute,
  viewingsRoute,
  followupsRoute,
  leasesRoute,
  depositsRoute,
  remindersRoute,
  todosRoute,
  searchRoute,
  reportsRoute,
  usersRoute,
});
