# Generated by Django 4.2.7 on 2026-06-05 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctors', '0001_initial'),
        ('appointments', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_no', models.CharField(max_length=50, unique=True, verbose_name='处方号')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('ACTIVE', '生效中'), ('COMPLETED', '已完成'), ('CANCELLED', '已取消')], default='DRAFT', max_length=20, verbose_name='状态')),
                ('notes', models.TextField(blank=True, verbose_name='医嘱')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='appointments.appointment', verbose_name='关联预约')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_prescriptions', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='doctors.doctorprofile', verbose_name='开方医生')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='patients.patientprofile', verbose_name='患者')),
            ],
            options={
                'verbose_name': '处方',
                'verbose_name_plural': '处方',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=200, verbose_name='药品名称')),
                ('specification', models.CharField(max_length=100, verbose_name='规格')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='数量')),
                ('unit', models.CharField(max_length=20, verbose_name='单位')),
                ('dosage', models.CharField(max_length=100, verbose_name='剂量')),
                ('frequency', models.CharField(max_length=100, verbose_name='用法')),
                ('duration', models.CharField(blank=True, max_length=100, verbose_name='疗程')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='medical_records.prescription', verbose_name='处方')),
            ],
            options={
                'verbose_name': '处方明细',
                'verbose_name_plural': '处方明细',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MedicalSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chief_complaint', models.TextField(blank=True, verbose_name='主诉')),
                ('present_illness', models.TextField(blank=True, verbose_name='现病史')),
                ('past_illness', models.TextField(blank=True, verbose_name='既往史')),
                ('family_history', models.TextField(blank=True, verbose_name='家族史')),
                ('personal_history', models.TextField(blank=True, verbose_name='个人史')),
                ('physical_exam', models.TextField(blank=True, verbose_name='体格检查')),
                ('auxiliary_exam', models.TextField(blank=True, verbose_name='辅助检查')),
                ('diagnosis', models.TextField(blank=True, verbose_name='诊断')),
                ('treatment_plan', models.TextField(blank=True, verbose_name='治疗方案')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_summaries', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('last_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_summaries', to=settings.AUTH_USER_MODEL, verbose_name='最后更新人')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_summary', to='patients.patientprofile', verbose_name='患者')),
            ],
            options={
                'verbose_name': '病历摘要',
                'verbose_name_plural': '病历摘要',
            },
        ),
        migrations.CreateModel(
            name='FollowUpRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_number', models.IntegerField(default=1, verbose_name='第几次随访')),
                ('visit_date', models.DateField(verbose_name='随访日期')),
                ('symptoms', models.TextField(blank=True, verbose_name='症状描述')),
                ('physical_exam', models.TextField(blank=True, verbose_name='体格检查')),
                ('blood_pressure', models.CharField(blank=True, max_length=20, verbose_name='血压')),
                ('heart_rate', models.IntegerField(blank=True, null=True, verbose_name='心率')),
                ('blood_sugar', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='血糖')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='体重(kg)')),
                ('exam_results', models.TextField(blank=True, verbose_name='检查结果')),
                ('diagnosis', models.TextField(blank=True, verbose_name='诊断意见')),
                ('medication_adjustment', models.TextField(blank=True, verbose_name='用药调整')),
                ('lifestyle_advice', models.TextField(blank=True, verbose_name='生活方式建议')),
                ('next_visit_date', models.DateField(blank=True, null=True, verbose_name='下次随访日期')),
                ('notes', models.TextField(blank=True, verbose_name='其他备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followup_records', to='appointments.appointment', verbose_name='关联预约')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_followup_records', to=settings.AUTH_USER_MODEL, verbose_name='记录人')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='followup_records', to='doctors.doctorprofile', verbose_name='随访医生')),
                ('followup_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followup_records', to='appointments.followupplan', verbose_name='关联复诊计划')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followup_records', to='patients.patientprofile', verbose_name='患者')),
            ],
            options={
                'verbose_name': '随访记录',
                'verbose_name_plural': '随访记录',
                'ordering': ['-visit_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalRecordPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_level', models.CharField(choices=[('READ', '只读'), ('WRITE', '可编辑'), ('FULL', '完全控制')], default='READ', max_length=20, verbose_name='权限级别')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL, verbose_name='授权人')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_permissions', to='patients.patientprofile', verbose_name='患者')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_permissions', to=settings.AUTH_USER_MODEL, verbose_name='授权用户')),
            ],
            options={
                'verbose_name': '病历权限',
                'verbose_name_plural': '病历权限',
                'ordering': ['-created_at'],
                'unique_together': {('patient', 'user')},
            },
        ),
    ]
