# Generated by Django 5.2.15 on 2026-06-21 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='流程名称')),
                ('flow_type', models.CharField(choices=[('contract', '合同审批'), ('invoice', '发票审批'), ('supplier', '供应商准入审批'), ('price_adjustment', '价格调整审批'), ('risk_handle', '风险处理审批')], max_length=50, unique=True, verbose_name='流程类型')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '审批流程',
                'verbose_name_plural': '审批流程',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='审批层级名称')),
                ('level_order', models.PositiveIntegerField(unique=True, verbose_name='审批顺序')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '审批层级',
                'verbose_name_plural': '审批层级',
                'ordering': ['level_order'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approve', '同意'), ('reject', '驳回'), ('transfer', '转审'), ('comment', '加签')], max_length=20, verbose_name='审批动作')),
                ('comment', models.TextField(blank=True, verbose_name='审批意见')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='审批时间')),
            ],
            options={
                'verbose_name': '审批记录',
                'verbose_name_plural': '审批记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_type', models.CharField(max_length=50, verbose_name='流程类型')),
                ('title', models.CharField(max_length=200, verbose_name='审批标题')),
                ('object_id', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已通过'), ('rejected', '已驳回'), ('cancelled', '已取消'), ('in_progress', '审批中')], default='pending', max_length=30, verbose_name='审批状态')),
                ('current_level_order', models.PositiveIntegerField(default=1, verbose_name='当前审批层级')),
                ('remarks', models.TextField(blank=True, verbose_name='申请说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '审批申请',
                'verbose_name_plural': '审批申请',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FlowLevelRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='顺序号')),
                ('min_approvers', models.PositiveIntegerField(default=1, verbose_name='最少审批人数')),
            ],
            options={
                'verbose_name': '流程层级关系',
                'verbose_name_plural': '流程层级关系',
                'ordering': ['flow', 'order'],
            },
        ),
    ]
