# Generated by Django 5.2.15 on 2026-06-21 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('approvals', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrecord',
            name='approver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_records', to=settings.AUTH_USER_MODEL, verbose_name='审批人'),
        ),
        migrations.AddField(
            model_name='approvalrecord',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='approvals.approvallevel', verbose_name='审批层级'),
        ),
        migrations.AddField(
            model_name='approvalrecord',
            name='transferred_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_approvals', to=settings.AUTH_USER_MODEL, verbose_name='转审给谁'),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_approvals', to=settings.AUTH_USER_MODEL, verbose_name='申请人'),
        ),
        migrations.AddField(
            model_name='approvalrecord',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='approvals.approvalrequest', verbose_name='审批申请'),
        ),
        migrations.AddField(
            model_name='flowlevelrelation',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approvals.approvalflow', verbose_name='审批流程'),
        ),
        migrations.AddField(
            model_name='flowlevelrelation',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approvals.approvallevel', verbose_name='审批层级'),
        ),
        migrations.AddField(
            model_name='flowlevelrelation',
            name='required_approvers',
            field=models.ManyToManyField(related_name='approval_level_relations', to=settings.AUTH_USER_MODEL, verbose_name='可审批人'),
        ),
        migrations.AddField(
            model_name='approvalflow',
            name='levels',
            field=models.ManyToManyField(related_name='flows', through='approvals.FlowLevelRelation', to='approvals.approvallevel', verbose_name='审批层级'),
        ),
        migrations.AlterUniqueTogether(
            name='flowlevelrelation',
            unique_together={('flow', 'level', 'order')},
        ),
    ]
