source "https://rubygems.org"

gem "rails", "~> 8.0.5"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"

gem "bcrypt", "~> 3.1.7"
gem "jwt"
gem "rack-cors"
gem "sidekiq"
gem "ransack"
gem "kaminari"
gem "aasm"
gem "rubyzip", require: "zip"
gem "roo"
gem "caxlsx"
gem "caxlsx_rails"

gem "solid_cache"
gem "solid_queue"
gem "solid_cable"

gem "bootsnap", require: false

group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
  gem "faker"
end
