import type {
  Metric,
  Anomaly,
  MetricDefinition,
  DeliveryProject,
  ReviewReport,
  Alert,
  Subscription,
  AuditLog,
  MetricDataPoint,
} from "@/types";
import type {
  MetricCategory,
  MetricStatus,
  TrendDirection,
  AnomalySeverity,
  AnomalyStatus,
  RootCauseCategory,
  AlertType,
  AlertOperator,
  DetectionAlgorithm,
  NotificationChannel,
  ApprovalStatus,
  DeliveryStatus,
  MilestoneStatus,
  EntityType,
  UserRole,
} from "@prisma/client";

const now = new Date();

export const mockUsers = [
  { id: "user-1", name: "张明", email: "zhangming@company.com", role: "OPERATIONS_MANAGER" as UserRole, department: "运营部" },
  { id: "user-2", name: "李华", email: "lihua@company.com", role: "OPERATIONS_SPECIALIST" as UserRole, department: "运营部" },
  { id: "user-3", name: "王强", email: "wangqiang@company.com", role: "SALES_DIRECTOR" as UserRole, department: "销售部" },
  { id: "user-4", name: "赵雪", email: "zhaoxue@company.com", role: "ADMIN" as UserRole, department: "技术部" },
];

function generateMetricData(days: number = 30, baseValue: number = 1000): MetricDataPoint[] {
  const data: MetricDataPoint[] = [];
  let value = baseValue;
  for (let i = days; i >= 0; i--) {
    const date = new Date(now);
    date.setDate(date.getDate() - i);
    const change = (Math.random() - 0.45) * baseValue * 0.1;
    value = Math.max(baseValue * 0.5, value + change);
    if (i === 5) value = value * 0.7;
    data.push({
      date: date.toISOString().split("T")[0],
      value: Math.round(value),
    });
  }
  return data;
}

export const mockMetrics: Metric[] = [
  {
    id: "metric-1",
    name: "日活跃用户",
    code: "DAU",
    description: "每日活跃用户数，统计当日登录并使用核心功能的用户",
    category: "USER_GROWTH" as MetricCategory,
    unit: "人",
    currentValue: 125680,
    previousValue: 132450,
    changeRate: -0.0511,
    trend: "DOWN" as TrendDirection,
    status: "WARNING" as MetricStatus,
    updatedAt: new Date(),
    dimensions: [
      { id: "dim-1", name: "渠道", key: "channel", values: ["自然流量", "广告投放", "社交媒体", "应用商店"], isActive: true, sortOrder: 1 },
      { id: "dim-2", name: "地区", key: "region", values: ["华东", "华北", "华南", "西南", "东北"], isActive: true, sortOrder: 2 },
      { id: "dim-3", name: "设备", key: "device", values: ["iOS", "Android", "Web"], isActive: true, sortOrder: 3 },
    ],
    alertRules: [
      {
        id: "rule-1",
        metricId: "metric-1",
        name: "DAU 异常下跌告警",
        type: "THRESHOLD" as AlertType,
        operator: "LT" as AlertOperator,
        threshold: 130000,
        thresholdMin: null,
        thresholdMax: null,
        detectionAlgorithm: "THREE_SIGMA" as DetectionAlgorithm,
        notificationChannels: ["EMAIL", "WECHAT" as NotificationChannel],
        notifyUsers: ["user-1", "user-3"],
        silentPeriodStart: null,
        silentPeriodEnd: null,
        isEnabled: true,
      },
    ],
    subscriptions: [
      {
        id: "sub-1",
        metricId: "metric-1",
        name: "DAU 每日日报",
        dimensions: { channel: ["自然流量", "广告投放"] },
        channels: ["EMAIL" as NotificationChannel],
        subscribers: ["user-1", "user-2"],
        schedule: { hour: 9, minute: 0, timezone: "Asia/Shanghai" },
        templateId: "template-dau",
        isEnabled: true,
        createdBy: "user-1",
        createdAt: new Date("2025-01-15"),
      },
    ],
  },
  {
    id: "metric-2",
    name: "新增用户",
    code: "NEW_USERS",
    description: "每日新增注册用户数",
    category: "USER_GROWTH" as MetricCategory,
    unit: "人",
    currentValue: 8520,
    previousValue: 7800,
    changeRate: 0.0923,
    trend: "UP" as TrendDirection,
    status: "NORMAL" as MetricStatus,
    updatedAt: new Date(),
    dimensions: [
      { id: "dim-4", name: "注册渠道", key: "register_channel", values: ["手机号", "微信", "QQ", "邮箱"], isActive: true, sortOrder: 1 },
      { id: "dim-5", name: "推广渠道", key: "promotion_channel", values: ["抖音", "小红书", "B站", "微博"], isActive: true, sortOrder: 2 },
    ],
    alertRules: [],
    subscriptions: [],
  },
  {
    id: "metric-3",
    name: "次日留存率",
    code: "RETENTION_D1",
    description: "新用户次日留存比例",
    category: "RETENTION" as MetricCategory,
    unit: "%",
    currentValue: 0.425,
    previousValue: 0.452,
    changeRate: -0.0597,
    trend: "DOWN" as TrendDirection,
    status: "CRITICAL" as MetricStatus,
    updatedAt: new Date(),
    dimensions: [
      { id: "dim-6", name: "用户分层", key: "user_tier", values: ["高价值", "中价值", "低价值"], isActive: true, sortOrder: 1 },
    ],
    alertRules: [
      {
        id: "rule-2",
        metricId: "metric-3",
        name: "次日留存率下跌告警",
        type: "ANOMALY" as AlertType,
        operator: "LT" as AlertOperator,
        threshold: 0.4,
        thresholdMin: null,
        thresholdMax: null,
        detectionAlgorithm: "THREE_SIGMA" as DetectionAlgorithm,
        notificationChannels: ["EMAIL", "WECHAT", "SMS" as NotificationChannel],
        notifyUsers: ["user-1", "user-3", "user-2"],
        silentPeriodStart: "00:00",
        silentPeriodEnd: "06:00",
        isEnabled: true,
      },
    ],
    subscriptions: [
      {
        id: "sub-2",
        metricId: "metric-3",
        name: "留存率监控日报",
        dimensions: null,
        channels: ["EMAIL", "WECHAT" as NotificationChannel],
        subscribers: ["user-1", "user-2", "user-3"],
        schedule: { hour: 8, minute: 30, timezone: "Asia/Shanghai" },
        templateId: "template-retention",
        isEnabled: true,
        createdBy: "user-1",
        createdAt: new Date("2025-02-01"),
      },
    ],
  },
  {
    id: "metric-4",
    name: "转化率",
    code: "CONVERSION_RATE",
    description: "浏览用户到付费用户的转化率",
    category: "CONVERSION" as MetricCategory,
    unit: "%",
    currentValue: 0.038,
    previousValue: 0.036,
    changeRate: 0.0556,
    trend: "UP" as TrendDirection,
    status: "NORMAL" as MetricStatus,
    updatedAt: new Date(),
    dimensions: [
      { id: "dim-7", name: "商品分类", key: "category", values: ["会员", "虚拟商品", "实物商品"], isActive: true, sortOrder: 1 },
      { id: "dim-8", name: "支付方式", key: "payment", values: ["微信支付", "支付宝", "苹果支付"], isActive: true, sortOrder: 2 },
    ],
    alertRules: [],
    subscriptions: [],
  },
  {
    id: "metric-5",
    name: "GMV",
    code: "GMV",
    description: "商品交易总额",
    category: "REVENUE" as MetricCategory,
    unit: "元",
    currentValue: 2586000,
    previousValue: 2340000,
    changeRate: 0.1051,
    trend: "UP" as TrendDirection,
    status: "NORMAL" as MetricStatus,
    updatedAt: new Date(),
    dimensions: [
      { id: "dim-9", name: "业务线", key: "business_line", values: ["核心业务", "增值服务", "广告收入"], isActive: true, sortOrder: 1 },
    ],
    alertRules: [],
    subscriptions: [],
  },
  {
    id: "metric-6",
    name: "人均使用时长",
    code: "AVG_SESSION_DURATION",
    description: "平均每人每日使用时长（分钟）",
    category: "ENGAGEMENT" as MetricCategory,
    unit: "分钟",
    currentValue: 28.5,
    previousValue: 26.8,
    changeRate: 0.0634,
    trend: "UP" as TrendDirection,
    status: "NORMAL" as MetricStatus,
    updatedAt: new Date(),
    dimensions: [],
    alertRules: [],
    subscriptions: [],
  },
];

export const mockAnomalies: Anomaly[] = [
  {
    id: "anomaly-1",
    metricId: "metric-3",
    metricName: "次日留存率",
    detectedAt: new Date(now.getTime() - 1000 * 60 * 60 * 2),
    severity: "CRITICAL" as AnomalySeverity,
    actualValue: 0.425,
    expectedValue: 0.45,
    deviation: 0.025,
    deviationPercent: 0.0556,
    status: "INVESTIGATING" as AnomalyStatus,
    rootCause: "正在调查中，疑似新版本发布导致用户体验下降",
    rootCauseCategory: "BUSINESS_CHANGE" as RootCauseCategory,
    impactAssessment: "影响约 5% 的新用户留存，预计造成日活下降 3-5%",
    resolution: "已联系产品团队回滚关键改动，同时运营团队准备召回活动",
    assignee: "user-2",
    assigneeName: "李华",
    resolvedAt: null,
    relatedAnomalies: ["anomaly-2"],
    createdAt: new Date(now.getTime() - 1000 * 60 * 60 * 2),
  },
  {
    id: "anomaly-2",
    metricId: "metric-1",
    metricName: "日活跃用户",
    detectedAt: new Date(now.getTime() - 1000 * 60 * 60 * 5),
    severity: "HIGH" as AnomalySeverity,
    actualValue: 125680,
    expectedValue: 135000,
    deviation: 9320,
    deviationPercent: 0.069,
    status: "INVESTIGATING" as AnomalyStatus,
    rootCause: "留存率下降导致，同时渠道投放策略调整影响新增",
    rootCauseCategory: "EXTERNAL_FACTOR" as RootCauseCategory,
    impactAssessment: "日活下降约 5%，影响范围较大",
    resolution: "正在优化投放策略，同时配合召回活动",
    assignee: "user-2",
    assigneeName: "李华",
    resolvedAt: null,
    relatedAnomalies: ["anomaly-1"],
    createdAt: new Date(now.getTime() - 1000 * 60 * 60 * 5),
  },
  {
    id: "anomaly-3",
    metricId: "metric-4",
    metricName: "转化率",
    detectedAt: new Date(now.getTime() - 1000 * 60 * 60 * 24),
    severity: "MEDIUM" as AnomalySeverity,
    actualValue: 0.032,
    expectedValue: 0.038,
    deviation: 0.006,
    deviationPercent: 0.1579,
    status: "RESOLVED" as AnomalyStatus,
    rootCause: "支付网关临时故障，导致部分用户支付失败",
    rootCauseCategory: "SYSTEM_FAILURE" as RootCauseCategory,
    impactAssessment: "影响约 15% 的订单，已进行补偿",
    resolution: "技术团队已修复支付网关问题，运营团队对受影响用户发放优惠券补偿",
    assignee: "user-2",
    assigneeName: "李华",
    resolvedAt: new Date(now.getTime() - 1000 * 60 * 60 * 12),
    relatedAnomalies: [],
    createdAt: new Date(now.getTime() - 1000 * 60 * 60 * 24),
  },
  {
    id: "anomaly-4",
    metricId: "metric-5",
    metricName: "GMV",
    detectedAt: new Date(now.getTime() - 1000 * 60 * 60 * 48),
    severity: "LOW" as AnomalySeverity,
    actualValue: 2100000,
    expectedValue: 2300000,
    deviation: 200000,
    deviationPercent: 0.087,
    status: "RESOLVED" as AnomalyStatus,
    rootCause: "数据统计口径临时调整，已恢复正常",
    rootCauseCategory: "DATA_QUALITY" as RootCauseCategory,
    impactAssessment: "无实际业务影响，仅数据统计问题",
    resolution: "数据团队已修复统计逻辑，重新计算后数据已恢复",
    assignee: "user-1",
    assigneeName: "张明",
    resolvedAt: new Date(now.getTime() - 1000 * 60 * 60 * 36),
    relatedAnomalies: [],
    createdAt: new Date(now.getTime() - 1000 * 60 * 60 * 48),
  },
];

export const mockMetricDefinitions: MetricDefinition[] = [
  {
    id: "def-1",
    metricId: "metric-1",
    version: 3,
    name: "日活跃用户",
    description: "每日活跃用户数",
    calculationLogic: "统计当日登录并使用核心功能的去重用户数，核心功能定义为：浏览内容、发布内容、互动、交易中的任意一项",
    sqlQuery: "SELECT COUNT(DISTINCT user_id) FROM user_activity WHERE DATE(created_at) = CURRENT_DATE AND action_type IN ('view', 'post', 'interact', 'trade')",
    dataSource: "user_activity 表，数据仓库 ods 层",
    businessOwner: "user-1",
    businessOwnerName: "张明",
    technicalOwner: "user-4",
    technicalOwnerName: "赵雪",
    changeReason: "核心功能定义更新，新增交易行为作为活跃判定标准",
    changeImpact: "DAU 预计提升 2-3%，历史数据需重新计算",
    approvalStatus: "APPROVED" as ApprovalStatus,
    approvedBy: "user-1",
    approvedByName: "张明",
    approvedAt: new Date("2025-05-10"),
    createdBy: "user-2",
    createdByName: "李华",
    createdAt: new Date("2025-05-08"),
    isCurrent: true,
  },
  {
    id: "def-2",
    metricId: "metric-1",
    version: 2,
    name: "日活跃用户",
    description: "每日活跃用户数",
    calculationLogic: "统计当日登录并使用核心功能的去重用户数，核心功能定义为：浏览内容、发布内容、互动中的任意一项",
    sqlQuery: "SELECT COUNT(DISTINCT user_id) FROM user_activity WHERE DATE(created_at) = CURRENT_DATE AND action_type IN ('view', 'post', 'interact')",
    dataSource: "user_activity 表，数据仓库 ods 层",
    businessOwner: "user-1",
    businessOwnerName: "张明",
    technicalOwner: "user-4",
    technicalOwnerName: "赵雪",
    changeReason: "调整活跃判定标准，排除仅登录用户",
    changeImpact: "DAU 预计下降 5%",
    approvalStatus: "APPROVED" as ApprovalStatus,
    approvedBy: "user-1",
    approvedByName: "张明",
    approvedAt: new Date("2025-03-15"),
    createdBy: "user-2",
    createdByName: "李华",
    createdAt: new Date("2025-03-12"),
    isCurrent: false,
  },
  {
    id: "def-3",
    metricId: "metric-1",
    version: 1,
    name: "日活跃用户",
    description: "每日活跃用户数",
    calculationLogic: "统计当日登录的去重用户数",
    sqlQuery: "SELECT COUNT(DISTINCT user_id) FROM user_sessions WHERE DATE(login_at) = CURRENT_DATE",
    dataSource: "user_sessions 表",
    businessOwner: "user-1",
    businessOwnerName: "张明",
    technicalOwner: "user-4",
    technicalOwnerName: "赵雪",
    changeReason: "初始定义",
    changeImpact: null,
    approvalStatus: "APPROVED" as ApprovalStatus,
    approvedBy: "user-1",
    approvedByName: "张明",
    approvedAt: new Date("2025-01-01"),
    createdBy: "user-1",
    createdByName: "张明",
    createdAt: new Date("2025-01-01"),
    isCurrent: false,
  },
];

export const mockDeliveryProjects: DeliveryProject[] = [
  {
    id: "proj-1",
    name: "Q2 用户增长项目",
    description: "二季度用户增长目标达成 20%，主要通过渠道优化和活动运营",
    owner: "user-1",
    ownerName: "张明",
    startDate: new Date("2025-04-01"),
    endDate: new Date("2025-06-30"),
    progress: 65,
    status: "IN_PROGRESS" as DeliveryStatus,
    milestones: [
      { id: "ms-1", name: "渠道策略制定", dueDate: new Date("2025-04-15"), completedAt: new Date("2025-04-12"), status: "COMPLETED" as MilestoneStatus, sortOrder: 1 },
      { id: "ms-2", name: "A/B 测试方案", dueDate: new Date("2025-04-30"), completedAt: new Date("2025-04-28"), status: "COMPLETED" as MilestoneStatus, sortOrder: 2 },
      { id: "ms-3", name: "活动上线", dueDate: new Date("2025-05-20"), completedAt: new Date("2025-05-18"), status: "COMPLETED" as MilestoneStatus, sortOrder: 3 },
      { id: "ms-4", name: "效果评估与优化", dueDate: new Date("2025-06-15"), completedAt: null, status: "IN_PROGRESS" as MilestoneStatus, sortOrder: 4 },
      { id: "ms-5", name: "项目复盘", dueDate: new Date("2025-06-30"), completedAt: null, status: "PENDING" as MilestoneStatus, sortOrder: 5 },
    ],
    remarks: [
      { id: "remark-1", content: "渠道优化初见成效，投放 ROI 提升 15%", createdBy: "user-1", createdByName: "张明", createdAt: new Date("2025-05-10"), progressSnapshot: 40 },
      { id: "remark-2", content: "活动上线后新增用户提升 25%，超出预期", createdBy: "user-2", createdByName: "李华", createdAt: new Date("2025-05-25"), progressSnapshot: 60 },
      { id: "remark-3", content: "近期留存率有所波动，正在分析原因并调整策略", createdBy: "user-1", createdByName: "张明", createdAt: new Date("2025-06-10"), progressSnapshot: 65 },
    ],
    createdAt: new Date("2025-04-01"),
    updatedAt: new Date(),
  },
  {
    id: "proj-2",
    name: "会员体系升级",
    description: "升级会员权益体系，提升会员转化率和留存",
    owner: "user-1",
    ownerName: "张明",
    startDate: new Date("2025-05-01"),
    endDate: new Date("2025-07-31"),
    progress: 30,
    status: "IN_PROGRESS" as DeliveryStatus,
    milestones: [
      { id: "ms-6", name: "需求调研与方案设计", dueDate: new Date("2025-05-20"), completedAt: new Date("2025-05-18"), status: "COMPLETED" as MilestoneStatus, sortOrder: 1 },
      { id: "ms-7", name: "产品开发", dueDate: new Date("2025-06-30"), completedAt: null, status: "IN_PROGRESS" as MilestoneStatus, sortOrder: 2 },
      { id: "ms-8", name: "灰度测试", dueDate: new Date("2025-07-10"), completedAt: null, status: "PENDING" as MilestoneStatus, sortOrder: 3 },
      { id: "ms-9", name: "全量上线", dueDate: new Date("2025-07-20"), completedAt: null, status: "PENDING" as MilestoneStatus, sortOrder: 4 },
      { id: "ms-10", name: "效果评估", dueDate: new Date("2025-07-31"), completedAt: null, status: "PENDING" as MilestoneStatus, sortOrder: 5 },
    ],
    remarks: [
      { id: "remark-4", content: "需求调研完成，已确定会员等级和权益体系", createdBy: "user-2", createdByName: "李华", createdAt: new Date("2025-05-20"), progressSnapshot: 20 },
      { id: "remark-5", content: "开发进度正常，预计提前 3 天完成", createdBy: "user-1", createdByName: "张明", createdAt: new Date("2025-06-05"), progressSnapshot: 30 },
    ],
    createdAt: new Date("2025-05-01"),
    updatedAt: new Date(),
  },
  {
    id: "proj-3",
    name: "数据中台建设",
    description: "构建统一数据指标体系，提升数据质量和查询效率",
    owner: "user-4",
    ownerName: "赵雪",
    startDate: new Date("2025-03-01"),
    endDate: new Date("2025-06-30"),
    progress: 85,
    status: "IN_PROGRESS" as DeliveryStatus,
    milestones: [
      { id: "ms-11", name: "指标体系梳理", dueDate: new Date("2025-03-31"), completedAt: new Date("2025-03-28"), status: "COMPLETED" as MilestoneStatus, sortOrder: 1 },
      { id: "ms-12", name: "数据仓库建模", dueDate: new Date("2025-04-30"), completedAt: new Date("2025-04-25"), status: "COMPLETED" as MilestoneStatus, sortOrder: 2 },
      { id: "ms-13", name: "ETL 开发", dueDate: new Date("2025-05-31"), completedAt: new Date("2025-05-28"), status: "COMPLETED" as MilestoneStatus, sortOrder: 3 },
      { id: "ms-14", name: "数据质量监控", dueDate: new Date("2025-06-15"), completedAt: null, status: "IN_PROGRESS" as MilestoneStatus, sortOrder: 4 },
      { id: "ms-15", name: "上线验收", dueDate: new Date("2025-06-30"), completedAt: null, status: "PENDING" as MilestoneStatus, sortOrder: 5 },
    ],
    remarks: [
      { id: "remark-6", content: "指标体系梳理完成，共梳理核心指标 50+", createdBy: "user-4", createdByName: "赵雪", createdAt: new Date("2025-03-28"), progressSnapshot: 25 },
      { id: "remark-7", content: "数据仓库建模完成，已接入 3 个业务系统数据", createdBy: "user-4", createdByName: "赵雪", createdAt: new Date("2025-04-25"), progressSnapshot: 50 },
      { id: "remark-8", content: "ETL 开发完成，数据处理时效提升 30%", createdBy: "user-4", createdByName: "赵雪", createdAt: new Date("2025-05-28"), progressSnapshot: 75 },
    ],
    createdAt: new Date("2025-03-01"),
    updatedAt: new Date(),
  },
];

export const mockReviewReports: ReviewReport[] = [
  {
    id: "report-2025-05",
    month: "2025-05",
    metricsSummary: [
      { metricId: "metric-1", metricName: "日活跃用户", targetValue: 150000, actualValue: 135000, completionRate: 0.9, anomalyCount: 3 },
      { metricId: "metric-2", metricName: "新增用户", targetValue: 10000, actualValue: 9200, completionRate: 0.92, anomalyCount: 1 },
      { metricId: "metric-3", metricName: "次日留存率", targetValue: 0.48, actualValue: 0.43, completionRate: 0.896, anomalyCount: 2 },
      { metricId: "metric-5", metricName: "GMV", targetValue: 2500000, actualValue: 2586000, completionRate: 1.034, anomalyCount: 1 },
    ],
    anomaliesSummary: {
      total: 7,
      bySeverity: { LOW: 2, MEDIUM: 2, HIGH: 2, CRITICAL: 1 },
      byCategory: { DATA_QUALITY: 1, BUSINESS_CHANGE: 2, SYSTEM_FAILURE: 2, EXTERNAL_FACTOR: 1, OTHER: 1 },
      avgResolutionTime: 12.5,
    },
    deliverySummary: {
      totalProjects: 3,
      completedProjects: 0,
      onTimeRate: 0.667,
    },
    generatedBy: "user-1",
    generatedByName: "张明",
    generatedAt: new Date("2025-06-01"),
  },
];

export const mockAlerts: Alert[] = [
  {
    id: "alert-1",
    alertRuleId: "rule-2",
    anomalyId: "anomaly-1",
    message: "【严重告警】次日留存率下跌至 42.5%，低于阈值 45%",
    severity: "CRITICAL" as AnomalySeverity,
    status: "OPEN" as AnomalyStatus,
    triggeredAt: new Date(now.getTime() - 1000 * 60 * 60 * 2),
    acknowledgedAt: new Date(now.getTime() - 1000 * 60 * 60 * 1.5),
    acknowledgedBy: "user-2",
    resolvedAt: null,
  },
  {
    id: "alert-2",
    alertRuleId: "rule-1",
    anomalyId: "anomaly-2",
    message: "【高级告警】DAU 下跌至 125,680，低于阈值 130,000",
    severity: "HIGH" as AnomalySeverity,
    status: "OPEN" as AnomalyStatus,
    triggeredAt: new Date(now.getTime() - 1000 * 60 * 60 * 5),
    acknowledgedAt: new Date(now.getTime() - 1000 * 60 * 60 * 4),
    acknowledgedBy: "user-2",
    resolvedAt: null,
  },
];

export const mockAuditLogs: AuditLog[] = [
  {
    id: "audit-1",
    action: "UPDATE_THRESHOLD",
    entityType: "METRIC_THRESHOLD" as EntityType,
    entityId: "rule-1",
    oldValue: { threshold: 140000 },
    newValue: { threshold: 130000 },
    remark: "根据业务实际情况下调 DAU 告警阈值，原阈值过高导致频繁误报",
    operatorId: "user-1",
    operatorName: "张明",
    createdAt: new Date("2025-06-01"),
  },
  {
    id: "audit-2",
    action: "UPDATE_PERMISSION",
    entityType: "USER_PERMISSION" as EntityType,
    entityId: "user-3",
    oldValue: { role: "VIEWER" },
    newValue: { role: "SALES_DIRECTOR" },
    remark: "销售总监王强晋升，授予异常告警查看和交付进度管理权限",
    operatorId: "user-4",
    operatorName: "赵雪",
    createdAt: new Date("2025-05-15"),
  },
  {
    id: "audit-3",
    action: "UPDATE_DEFINITION",
    entityType: "DEFINITION_CHANGE" as EntityType,
    entityId: "def-1",
    oldValue: { calculationLogic: "统计当日登录并使用核心功能的去重用户数" },
    newValue: { calculationLogic: "统计当日登录并使用核心功能的去重用户数，新增交易行为作为活跃判定" },
    remark: "DAU 口径更新，增加交易行为作为活跃判定标准，已通过审批",
    operatorId: "user-2",
    operatorName: "李华",
    createdAt: new Date("2025-05-08"),
  },
];

export function getMockMetricData(metricId: string): MetricDataPoint[] {
  const baseValues: Record<string, number> = {
    "metric-1": 130000,
    "metric-2": 8000,
    "metric-3": 0.45,
    "metric-4": 0.035,
    "metric-5": 2400000,
    "metric-6": 25,
  };
  return generateMetricData(30, baseValues[metricId] || 1000);
}

export function getCurrentUser() {
  return mockUsers[0];
}
