<?php

namespace App\Http\Controllers;

use App\Http\Requests\ExportReportRequest;
use App\Exports\ReportExport;
use App\Models\Bill;
use App\Models\Contract;
use App\Services\OperationLogService;
use Inertia\Inertia;
use Maatwebsite\Excel\Excel;

class ReportExportController extends Controller
{
    public function form()
    {
        return Inertia::render('Reports/Export');
    }

    public function download(ExportReportRequest $request)
    {
        $data = $request->validated();
        $generator = $request->user();
        $type = $request->input('export_type', 'contracts');

        if ($type === 'bills') {
            return $this->exportBills($data, $generator);
        }

        return $this->exportContracts($data, $generator);
    }

    private function exportContracts(array $data, $generator)
    {
        $query = Contract::with(['property', 'tenant', 'consultant']);

        if (!empty($data['status'])) {
            $query->where('status', $data['status']);
        }
        if (!empty($data['property_id'])) {
            $query->where('property_id', $data['property_id']);
        }
        if (!empty($data['date_from'])) {
            $query->where('start_date', '>=', $data['date_from']);
        }
        if (!empty($data['date_to'])) {
            $query->where('start_date', '<=', $data['date_to']);
        }

        $contracts = $query->orderByDesc('id')->get();

        $export = new ReportExport(
            $this->buildContractRows($contracts),
            $this->buildMetadata($data, $generator)
        );

        app(OperationLogService::class)->log(
            $generator,
            'export_contracts',
            Contract::class,
            null,
            $data
        );

        $fileName = 'contracts_' . now()->format('Ymd_His') . '.xlsx';

        return $export->download($fileName, Excel::XLSX);
    }

    private function exportBills(array $data, $generator)
    {
        $query = Bill::with(['contract.property', 'contract.tenant']);

        if (!empty($data['status'])) {
            $query->where('status', $data['status']);
        }
        if (!empty($data['contract_id'])) {
            $query->where('contract_id', $data['contract_id']);
        }
        if (!empty($data['date_from'])) {
            $query->where('due_date', '>=', $data['date_from']);
        }
        if (!empty($data['date_to'])) {
            $query->where('due_date', '<=', $data['date_to']);
        }

        $bills = $query->orderByDesc('id')->get();

        $export = new ReportExport(
            $this->buildBillRows($bills),
            $this->buildMetadata($data, $generator)
        );

        app(OperationLogService::class)->log(
            $generator,
            'export_bills',
            Bill::class,
            null,
            $data
        );

        $fileName = 'bills_' . now()->format('Ymd_His') . '.xlsx';

        return $export->download($fileName, Excel::XLSX);
    }

    private function buildMetadata(array $data, $generator): array
    {
        $filters = [];
        if (!empty($data['status'])) {
            $filters[] = 'Status: ' . $data['status'];
        }
        if (!empty($data['date_from'])) {
            $filters[] = 'From: ' . $data['date_from'];
        }
        if (!empty($data['date_to'])) {
            $filters[] = 'To: ' . $data['date_to'];
        }
        if (!empty($data['property_id'])) {
            $filters[] = 'Property ID: ' . $data['property_id'];
        }
        if (!empty($data['contract_id'])) {
            $filters[] = 'Contract ID: ' . $data['contract_id'];
        }

        return [
            'Generated At: ' . now()->toIso8601String(),
            'Generated By: ' . $generator->name,
            'Date Range: ' . ($data['date_from'] ?? 'N/A') . ' ~ ' . ($data['date_to'] ?? 'N/A'),
            'Filters: ' . (count($filters) > 0 ? implode('; ', $filters) : 'None'),
        ];
    }

    private function buildContractRows($contracts): array
    {
        $headers = ['Contract No', 'Property', 'Tenant', 'Start Date', 'End Date', 'Monthly Rent', 'Deposit', 'Status'];

        $rows = $contracts->map(fn ($c) => [
            $c->contract_no,
            $c->property?->name,
            $c->tenant?->name,
            $c->start_date?->format('Y-m-d'),
            $c->end_date?->format('Y-m-d'),
            $c->monthly_rent,
            $c->deposit_amount,
            $c->status,
        ])->toArray();

        return array_merge([$headers], $rows);
    }

    private function buildBillRows($bills): array
    {
        $headers = ['Bill No', 'Contract', 'Property', 'Type', 'Amount', 'Due Date', 'Paid Date', 'Status'];

        $rows = $bills->map(fn ($b) => [
            $b->bill_no,
            $b->contract?->contract_no,
            $b->contract?->property?->name,
            $b->type,
            $b->amount,
            $b->due_date?->format('Y-m-d'),
            $b->paid_date?->format('Y-m-d'),
            $b->status,
        ])->toArray();

        return array_merge([$headers], $rows);
    }
}
