# Generated by Django 4.2.30 on 2026-06-16 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='合同标题')),
                ('contract_number', models.CharField(max_length=100, unique=True, verbose_name='合同编号')),
                ('file', models.FileField(upload_to='uploads/contracts/%Y/%m/', verbose_name='合同文件')),
                ('counterparty', models.CharField(blank=True, max_length=255, verbose_name='对方单位')),
                ('contract_type', models.CharField(blank=True, max_length=100, verbose_name='合同类型')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='合同金额')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('under_review', '审查中'), ('approved', '已通过'), ('rejected', '已退回'), ('stamped', '已盖章'), ('archived', '已归档')], default='draft', max_length=20, verbose_name='状态')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_contracts', to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'verbose_name': '合同',
                'verbose_name_plural': '合同',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractReview',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('in_progress', '进行中'), ('completed', '已完成'), ('rejected', '已退回'), ('cancelled', '已取消')], default='in_progress', max_length=20, verbose_name='状态')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='contracts.contract', verbose_name='合同')),
            ],
            options={
                'verbose_name': '合同审查',
                'verbose_name_plural': '合同审查',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceChecklist',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255, verbose_name='证据项名称')),
                ('is_required', models.BooleanField(default=True, verbose_name='是否必须')),
                ('is_collected', models.BooleanField(default=False, verbose_name='是否已收集')),
                ('collected_at', models.DateTimeField(blank=True, null=True, verbose_name='收集时间')),
                ('business_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_checklists', to='contracts.contractreview', verbose_name='业务单')),
                ('collector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_evidences', to=settings.AUTH_USER_MODEL, verbose_name='收集人')),
            ],
            options={
                'verbose_name': '证据清单',
                'verbose_name_plural': '证据清单',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewWorkflow',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='流程名称')),
                ('description', models.TextField(blank=True, verbose_name='流程说明')),
                ('contract_type', models.CharField(blank=True, max_length=100, verbose_name='适用合同类型')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '审查流程',
                'verbose_name_plural': '审查流程',
            },
        ),
        migrations.CreateModel(
            name='StampNode',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stamp_type', models.CharField(max_length=100, verbose_name='盖章类型')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('status', models.CharField(choices=[('pending', '待盖章'), ('completed', '已盖章'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('business_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stamp_nodes', to='contracts.contractreview', verbose_name='业务单')),
                ('handler', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_stamps', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
            ],
            options={
                'verbose_name': '盖章节点',
                'verbose_name_plural': '盖章节点',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewStep',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(verbose_name='步骤顺序')),
                ('name', models.CharField(max_length=255, verbose_name='步骤名称')),
                ('reviewer_role', models.CharField(max_length=100, verbose_name='审查人角色')),
                ('is_required', models.BooleanField(default=True, verbose_name='是否必须')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='contracts.reviewworkflow', verbose_name='所属流程')),
            ],
            options={
                'verbose_name': '审查步骤',
                'verbose_name_plural': '审查步骤',
                'ordering': ['workflow', 'order'],
                'unique_together': {('workflow', 'order')},
            },
        ),
        migrations.CreateModel(
            name='ReviewOpinion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('opinion', models.TextField(verbose_name='审查意见')),
                ('result', models.CharField(choices=[('pass', '通过'), ('reject', '退回')], max_length=10, verbose_name='审查结果')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True, verbose_name='审查时间')),
                ('contract_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opinions', to='contracts.contractreview', verbose_name='合同审查')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_opinions', to=settings.AUTH_USER_MODEL, verbose_name='审查人')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contracts.reviewstep', verbose_name='审查步骤')),
            ],
            options={
                'verbose_name': '审查意见',
                'verbose_name_plural': '审查意见',
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.CreateModel(
            name='RejectionNotification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(verbose_name='退回原因')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('synced_to_board', models.BooleanField(default=False, verbose_name='是否已同步至看板')),
                ('compliance_manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_rejections', to=settings.AUTH_USER_MODEL, verbose_name='合规经理')),
                ('contract_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejection_notifications', to='contracts.contractreview', verbose_name='合同审查')),
                ('rejected_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_rejections', to=settings.AUTH_USER_MODEL, verbose_name='退回人')),
            ],
            options={
                'verbose_name': '退回提醒',
                'verbose_name_plural': '退回提醒',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgressRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('upload', '上传'), ('submit', '提交'), ('review', '审查'), ('approve', '审批'), ('stamp', '盖章'), ('archive', '归档')], max_length=20, verbose_name='阶段')),
                ('action', models.CharField(max_length=255, verbose_name='操作')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('business_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='contracts.contractreview', verbose_name='业务单')),
                ('handler', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
            ],
            options={
                'verbose_name': '办理进度',
                'verbose_name_plural': '办理进度',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceMaterial',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='uploads/evidences/%Y/%m/', verbose_name='证据文件')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('business_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_materials', to='contracts.contractreview', verbose_name='业务单')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='contracts.evidencechecklist', verbose_name='证据清单项')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_evidences', to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'verbose_name': '证据材料',
                'verbose_name_plural': '证据材料',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='contractreview',
            name='current_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_reviews', to='contracts.reviewstep', verbose_name='当前步骤'),
        ),
        migrations.AddField(
            model_name='contractreview',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='contracts.reviewworkflow', verbose_name='审查流程'),
        ),
    ]
