# Generated by Django 5.2.15 on 2026-06-21 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContractPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='协议单价(元)')),
                ('minimum_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='最小采购量')),
                ('discount_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='折扣率(%)')),
                ('effective_date', models.DateField(verbose_name='生效日期')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='失效日期')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '合同价格',
                'verbose_name_plural': '合同价格',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractRenewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renewal_recommendation', models.TextField(blank=True, verbose_name='续签建议')),
                ('decision', models.CharField(choices=[('pending', '待处理'), ('in_progress', '处理中'), ('renewed', '已续签'), ('not_renewed', '不续签')], default='pending', max_length=30, verbose_name='处理结果')),
                ('decision_reason', models.TextField(blank=True, verbose_name='决策原因')),
                ('handled_date', models.DateField(blank=True, null=True, verbose_name='处理日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '合同续签',
                'verbose_name_plural': '合同续签',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FrameworkContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=50, unique=True, verbose_name='合同编号')),
                ('title', models.CharField(max_length=200, verbose_name='合同名称')),
                ('start_date', models.DateField(verbose_name='合同开始日期')),
                ('end_date', models.DateField(verbose_name='合同结束日期')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='合同总金额(元)')),
                ('minimum_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='最小起订金额(元)')),
                ('payment_terms', models.CharField(choices=[('monthly', '月结'), ('quarterly', '季结'), ('semiannual', '半年结'), ('annual', '年结'), ('delivery', '货到付款')], default='monthly', max_length=30, verbose_name='付款方式')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending_approval', '待审批'), ('active', '执行中'), ('expiring_soon', '即将到期'), ('expired', '已到期'), ('terminated', '已终止')], default='draft', max_length=30, verbose_name='合同状态')),
                ('terms_and_conditions', models.TextField(blank=True, verbose_name='合同条款')),
                ('delivery_terms', models.TextField(blank=True, verbose_name='交货条款')),
                ('quality_requirements', models.TextField(blank=True, verbose_name='质量要求')),
                ('penalty_clause', models.TextField(blank=True, verbose_name='违约条款')),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='contract_files/%Y/%m/', verbose_name='合同文件')),
                ('signed_date', models.DateField(blank=True, null=True, verbose_name='签订日期')),
                ('signing_location', models.CharField(blank=True, max_length=100, verbose_name='签订地点')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '框架协议',
                'verbose_name_plural': '框架协议',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='单价(元)')),
                ('price_date', models.DateField(verbose_name='价格日期')),
                ('source', models.CharField(default='contract', max_length=100, verbose_name='价格来源')),
                ('change_reason', models.CharField(blank=True, max_length=300, verbose_name='变动原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '价格历史',
                'verbose_name_plural': '价格历史',
                'ordering': ['-price_date'],
            },
        ),
    ]
