# Generated by Django 5.2.15 on 2026-06-21 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consumables', '0002_initial'),
        ('contracts', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contractprice',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='contractprice',
            name='specification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_prices', to='consumables.consumablespecification', verbose_name='耗材规格'),
        ),
        migrations.AddField(
            model_name='contractrenewal',
            name='handled_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handled_renewals', to=settings.AUTH_USER_MODEL, verbose_name='处理人'),
        ),
        migrations.AddField(
            model_name='frameworkcontract',
            name='categories',
            field=models.ManyToManyField(related_name='contracts', to='consumables.consumablecategory', verbose_name='覆盖品类'),
        ),
        migrations.AddField(
            model_name='frameworkcontract',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_contracts', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='frameworkcontract',
            name='project_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_contracts', to=settings.AUTH_USER_MODEL, verbose_name='项目负责人'),
        ),
        migrations.AddField(
            model_name='frameworkcontract',
            name='specifications',
            field=models.ManyToManyField(blank=True, related_name='contracts', to='consumables.consumablespecification', verbose_name='覆盖规格'),
        ),
        migrations.AddField(
            model_name='frameworkcontract',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='suppliers.supplier', verbose_name='供应商'),
        ),
        migrations.AddField(
            model_name='contractrenewal',
            name='new_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewed_from', to='contracts.frameworkcontract', verbose_name='新合同'),
        ),
        migrations.AddField(
            model_name='contractrenewal',
            name='original_contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='contracts.frameworkcontract', verbose_name='原合同'),
        ),
        migrations.AddField(
            model_name='contractprice',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='contracts.frameworkcontract', verbose_name='所属合同'),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_histories', to='contracts.frameworkcontract', verbose_name='来源合同'),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='recorded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='记录人'),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='specification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_histories', to='consumables.consumablespecification', verbose_name='耗材规格'),
        ),
        migrations.AlterUniqueTogether(
            name='contractprice',
            unique_together={('contract', 'specification', 'effective_date')},
        ),
    ]
