# Generated by Django 4.2.30 on 2026-06-06 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approve', '同意'), ('reject', '拒绝'), ('transfer', '转交')], max_length=20, verbose_name='审批动作')),
                ('remarks', models.TextField(blank=True, verbose_name='审批意见')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='审批时间')),
            ],
            options={
                'verbose_name': '审批记录',
                'verbose_name_plural': '审批记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BorrowItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('picked_up_quantity', models.IntegerField(default=0, verbose_name='已领取数量')),
                ('returned_quantity', models.IntegerField(default=0, verbose_name='已归还数量')),
                ('status', models.CharField(choices=[('pending', '待领取'), ('picked_up', '已领取'), ('returned', '已归还'), ('damaged', '损坏'), ('lost', '丢失')], default='pending', max_length=50, verbose_name='状态')),
                ('pickup_time', models.DateTimeField(blank=True, null=True, verbose_name='领取时间')),
                ('return_time', models.DateTimeField(blank=True, null=True, verbose_name='归还时间')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '借用明细',
                'verbose_name_plural': '借用明细',
            },
        ),
        migrations.CreateModel(
            name='BorrowOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=50, unique=True, verbose_name='借单号')),
                ('type', models.CharField(choices=[('borrow', '正常借用'), ('temporary', '临时追加')], default='borrow', max_length=20, verbose_name='借用类型')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending_approval', '待审批'), ('approved', '已批准'), ('picked_up', '已领取'), ('partial_returned', '部分归还'), ('returned', '已归还'), ('cancelled', '已取消')], default='draft', max_length=50, verbose_name='状态')),
                ('is_cross_hall', models.BooleanField(default=False, verbose_name='是否跨展厅借用')),
                ('requires_approval', models.BooleanField(default=False, verbose_name='需要审批')),
                ('first_confirm_time', models.DateTimeField(blank=True, null=True, verbose_name='第一确认时间')),
                ('second_confirm_time', models.DateTimeField(blank=True, null=True, verbose_name='第二确认时间')),
                ('approval_time', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('approval_remarks', models.TextField(blank=True, verbose_name='审批备注')),
                ('expected_pickup_date', models.DateField(verbose_name='预计领取日期')),
                ('expected_return_date', models.DateField(verbose_name='预计归还日期')),
                ('actual_pickup_date', models.DateTimeField(blank=True, null=True, verbose_name='实际领取时间')),
                ('actual_return_date', models.DateTimeField(blank=True, null=True, verbose_name='实际归还时间')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '借用单',
                'verbose_name_plural': '借用单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='展览名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='展览编码')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('planning', '规划中'), ('installation', '布展中'), ('open', '已开幕'), ('closed', '已闭展'), ('archived', '已归档')], default='draft', max_length=50, verbose_name='状态')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('installation_start', models.DateField(blank=True, null=True, verbose_name='布展开始日期')),
                ('installation_end', models.DateField(blank=True, null=True, verbose_name='布展结束日期')),
                ('opening_date', models.DateField(blank=True, null=True, verbose_name='开幕日期')),
                ('closing_date', models.DateField(blank=True, null=True, verbose_name='闭展日期')),
                ('description', models.TextField(blank=True, verbose_name='展览描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '展览',
                'verbose_name_plural': '展览',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ExhibitionHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='展厅名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='展厅编码')),
                ('floor', models.CharField(blank=True, max_length=50, verbose_name='楼层')),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='面积(㎡)')),
                ('capacity', models.IntegerField(blank=True, null=True, verbose_name='容量')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '展厅',
                'verbose_name_plural': '展厅',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TransportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_no', models.CharField(blank=True, max_length=100, verbose_name='运单号')),
                ('from_location', models.CharField(max_length=200, verbose_name='出发地')),
                ('to_location', models.CharField(max_length=200, verbose_name='目的地')),
                ('carrier', models.CharField(blank=True, max_length=100, verbose_name='承运人')),
                ('driver', models.CharField(blank=True, max_length=100, verbose_name='司机')),
                ('driver_phone', models.CharField(blank=True, max_length=20, verbose_name='司机电话')),
                ('status', models.CharField(choices=[('pending', '待运输'), ('in_transit', '运输中'), ('delivered', '已送达'), ('returned', '已退回')], default='pending', max_length=50, verbose_name='状态')),
                ('estimated_departure', models.DateTimeField(blank=True, null=True, verbose_name='预计出发时间')),
                ('actual_departure', models.DateTimeField(blank=True, null=True, verbose_name='实际出发时间')),
                ('estimated_arrival', models.DateTimeField(blank=True, null=True, verbose_name='预计到达时间')),
                ('actual_arrival', models.DateTimeField(blank=True, null=True, verbose_name='实际到达时间')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('borrow_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_records', to='exhibitions.borroworder', verbose_name='借用单')),
            ],
            options={
                'verbose_name': '运输记录',
                'verbose_name_plural': '运输记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
