# Generated by Django 4.2.30 on 2026-06-06 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
        ('exhibitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportrecord',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transports', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exhibitions', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='curator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curated_exhibitions', to=settings.AUTH_USER_MODEL, verbose_name='策展人'),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exhibitions', to='exhibitions.exhibitionhall', verbose_name='展厅'),
        ),
        migrations.AddField(
            model_name='borroworder',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_orders', to=settings.AUTH_USER_MODEL, verbose_name='审批人'),
        ),
        migrations.AddField(
            model_name='borroworder',
            name='construction_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL, verbose_name='施工负责人'),
        ),
        migrations.AddField(
            model_name='borroworder',
            name='exhibition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_orders', to='exhibitions.exhibition', verbose_name='展览'),
        ),
        migrations.AddField(
            model_name='borroworder',
            name='first_confirmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_confirmed_orders', to=settings.AUTH_USER_MODEL, verbose_name='第一确认人'),
        ),
        migrations.AddField(
            model_name='borroworder',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrow_orders', to='exhibitions.exhibitionhall', verbose_name='使用展厅'),
        ),
        migrations.AddField(
            model_name='borroworder',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_orders', to=settings.AUTH_USER_MODEL, verbose_name='申请人'),
        ),
        migrations.AddField(
            model_name='borroworder',
            name='second_confirmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_confirmed_orders', to=settings.AUTH_USER_MODEL, verbose_name='第二确认人(贵重物品)'),
        ),
        migrations.AddField(
            model_name='borrowitem',
            name='borrow_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='exhibitions.borroworder', verbose_name='借用单'),
        ),
        migrations.AddField(
            model_name='borrowitem',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrow_items', to='inventory.inventoryitem', verbose_name='具体库存项'),
        ),
        migrations.AddField(
            model_name='borrowitem',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrow_items', to='inventory.material', verbose_name='物料'),
        ),
        migrations.AddField(
            model_name='borrowitem',
            name='returned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returned_items', to=settings.AUTH_USER_MODEL, verbose_name='归还人'),
        ),
        migrations.AddField(
            model_name='approvalrecord',
            name='approver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_records', to=settings.AUTH_USER_MODEL, verbose_name='审批人'),
        ),
        migrations.AddField(
            model_name='approvalrecord',
            name='borrow_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_records', to='exhibitions.borroworder', verbose_name='借用单'),
        ),
        migrations.AddField(
            model_name='approvalrecord',
            name='next_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_approvals', to=settings.AUTH_USER_MODEL, verbose_name='转交审批人'),
        ),
    ]
