# Generated by Django 4.2.30 on 2026-06-05 20:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=200, verbose_name='耗材名称')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU编码')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('unit', models.CharField(max_length=20, verbose_name='单位')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='单价')),
                ('current_stock', models.IntegerField(default=0, verbose_name='当前库存')),
                ('min_stock', models.IntegerField(default=10, verbose_name='最低库存预警')),
                ('max_stock', models.IntegerField(default=100, verbose_name='最大库存')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='存放位置')),
                ('image', models.ImageField(blank=True, null=True, upload_to='consumables/', verbose_name='图片')),
                ('specifications', models.JSONField(blank=True, default=dict, verbose_name='规格参数')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '耗材',
                'verbose_name_plural': '耗材',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ConsumableCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='类别名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '耗材类别',
                'verbose_name_plural': '耗材类别',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ConsumableRestock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('quantity', models.IntegerField(verbose_name='入库数量')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='进货单价')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总费用')),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='供应商')),
                ('batch_number', models.CharField(blank=True, max_length=100, verbose_name='批次号')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='过期日期')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '耗材入库记录',
                'verbose_name_plural': '耗材入库记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsumableUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('unit_price_at_usage', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='使用时单价')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总费用')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('is_billed', models.BooleanField(default=False, verbose_name='已计费')),
                ('billed_at', models.DateTimeField(blank=True, null=True, verbose_name='计费时间')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumable_usages', to='bookings.booking', verbose_name='关联预约')),
                ('consumable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='consumables.consumable', verbose_name='耗材')),
            ],
            options={
                'verbose_name': '耗材使用记录',
                'verbose_name_plural': '耗材使用记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
