# Generated by Django 4.2.30 on 2026-06-05 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment', '0001_initial'),
        ('consumables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumableusage',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='consumableusage',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumable_usages', to='equipment.equipment', verbose_name='关联设备'),
        ),
        migrations.AddField(
            model_name='consumableusage',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
        migrations.AddField(
            model_name='consumableusage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumable_usages', to=settings.AUTH_USER_MODEL, verbose_name='使用人'),
        ),
        migrations.AddField(
            model_name='consumablerestock',
            name='consumable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restocks', to='consumables.consumable', verbose_name='耗材'),
        ),
        migrations.AddField(
            model_name='consumablerestock',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='consumablerestock',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
        migrations.AddField(
            model_name='consumable',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumables', to='consumables.consumablecategory', verbose_name='耗材类别'),
        ),
        migrations.AddField(
            model_name='consumable',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='consumable',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
        migrations.AddIndex(
            model_name='consumableusage',
            index=models.Index(fields=['consumable', 'created_at'], name='consumables_consuma_d8e97f_idx'),
        ),
        migrations.AddIndex(
            model_name='consumableusage',
            index=models.Index(fields=['user', 'created_at'], name='consumables_user_id_cc3a4f_idx'),
        ),
        migrations.AddIndex(
            model_name='consumableusage',
            index=models.Index(fields=['is_billed'], name='consumables_is_bill_bae05a_idx'),
        ),
        migrations.AddIndex(
            model_name='consumable',
            index=models.Index(fields=['name'], name='consumables_name_50eb19_idx'),
        ),
        migrations.AddIndex(
            model_name='consumable',
            index=models.Index(fields=['sku'], name='consumables_sku_e19996_idx'),
        ),
        migrations.AddIndex(
            model_name='consumable',
            index=models.Index(fields=['category'], name='consumables_categor_9dc8b6_idx'),
        ),
        migrations.AddIndex(
            model_name='consumable',
            index=models.Index(fields=['current_stock'], name='consumables_current_73b807_idx'),
        ),
    ]
