# Generated by Django 4.2.7 on 2026-06-06 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaliberConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='配置键')),
                ('value', models.TextField(verbose_name='配置值')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '口径配置',
                'verbose_name_plural': '口径配置',
            },
        ),
        migrations.CreateModel(
            name='LossAggregation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('period_type', models.CharField(choices=[('day', '日'), ('week', '周'), ('month', '月')], max_length=20, verbose_name='周期类型')),
                ('period_date', models.DateField(verbose_name='周期日期')),
                ('shift', models.CharField(blank=True, choices=[('morning', '早班'), ('afternoon', '中班'), ('evening', '晚班'), ('all', '全天')], max_length=20, verbose_name='班次')),
                ('total_use', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='总领用')),
                ('total_wastage', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='总报损')),
                ('total_stocktake_diff', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='总盘点差异')),
                ('total_sale_consume', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='总销售消耗')),
                ('loss_rate', models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='损耗率')),
                ('loss_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='损耗金额')),
                ('includes_trial', models.BooleanField(default=True, verbose_name='包含试营原料')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loss_aggs', to='materials.material', verbose_name='原料')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loss_aggs', to='organization.store', verbose_name='门店')),
            ],
            options={
                'verbose_name': '损耗聚合',
                'verbose_name_plural': '损耗聚合',
                'ordering': ['-period_date'],
                'unique_together': {('store', 'material', 'period_type', 'period_date', 'shift', 'includes_trial')},
            },
        ),
    ]
