# Generated by Django 4.2.7 on 2026-06-07 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lossaggregation',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='lossaggregation',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loss_aggs', to='materials.material', verbose_name='原料'),
        ),
        migrations.AlterField(
            model_name='lossaggregation',
            name='shift',
            field=models.CharField(blank=True, choices=[('morning', '早班'), ('afternoon', '中班'), ('evening', '晚班'), ('all', '全天')], default='all', max_length=20, verbose_name='班次'),
        ),
    ]
