# Generated by Django 4.2.30 on 2026-06-17 08:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.CharField(choices=[('pending', '待质检'), ('checking', '质检中'), ('passed', '已通过'), ('failed', '未通过')], default='pending', max_length=20, verbose_name='质检状态')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='质检分数')),
                ('check_items', models.JSONField(default=dict, verbose_name='检查项')),
                ('comments', models.TextField(blank=True, verbose_name='质检评语')),
                ('issues_found', models.TextField(blank=True, verbose_name='发现问题')),
                ('suggestions', models.TextField(blank=True, verbose_name='改进建议')),
                ('checked_at', models.DateTimeField(blank=True, null=True, verbose_name='质检时间')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('checker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_checks', to=settings.AUTH_USER_MODEL, verbose_name='质检人')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_checks', to='tickets.ticket', verbose_name='关联工单')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '质检记录',
                'verbose_name_plural': '质检记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImprovementAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=200, verbose_name='改进项标题')),
                ('description', models.TextField(verbose_name='问题描述')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('in_progress', '进行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高')], default='medium', max_length=20, verbose_name='优先级')),
                ('due_date', models.DateField(verbose_name='截止日期')),
                ('progress', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='进度百分比')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('solution', models.TextField(blank=True, verbose_name='解决方案')),
                ('result', models.TextField(blank=True, verbose_name='执行结果')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_improvements', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('quality_check', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='improvement_actions', to='operations.qualitycheck', verbose_name='关联质检')),
                ('related_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='improvement_actions', to='tickets.ticket', verbose_name='关联工单')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '改进措施',
                'verbose_name_plural': '改进措施',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('export_type', models.CharField(choices=[('tickets', '工单数据'), ('quality', '质检数据'), ('knowledge', '知识库数据'), ('reports', '报表数据'), ('custom', '自定义导出')], default='tickets', max_length=20, verbose_name='导出类型')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('file_name', models.CharField(max_length=200, verbose_name='文件名')),
                ('file_path', models.FileField(blank=True, null=True, upload_to='exports/', verbose_name='文件路径')),
                ('file_size', models.IntegerField(blank=True, null=True, verbose_name='文件大小(字节)')),
                ('filters', models.JSONField(default=dict, verbose_name='筛选条件')),
                ('filter_hash', models.CharField(max_length=64, verbose_name='筛选条件哈希值')),
                ('record_count', models.IntegerField(blank=True, null=True, verbose_name='记录数')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exports', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('previous_export', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_exports', to='operations.exportrecord', verbose_name='上一次相同条件导出')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '导出记录',
                'verbose_name_plural': '导出记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='qualitycheck',
            index=models.Index(fields=['ticket'], name='operations__ticket__70d855_idx'),
        ),
        migrations.AddIndex(
            model_name='qualitycheck',
            index=models.Index(fields=['checker'], name='operations__checker_35c046_idx'),
        ),
        migrations.AddIndex(
            model_name='qualitycheck',
            index=models.Index(fields=['status'], name='operations__status_33a7a3_idx'),
        ),
        migrations.AddIndex(
            model_name='qualitycheck',
            index=models.Index(fields=['created_at'], name='operations__created_82a1be_idx'),
        ),
        migrations.AddIndex(
            model_name='improvementaction',
            index=models.Index(fields=['status'], name='operations__status_c7e33f_idx'),
        ),
        migrations.AddIndex(
            model_name='improvementaction',
            index=models.Index(fields=['priority'], name='operations__priorit_244d3f_idx'),
        ),
        migrations.AddIndex(
            model_name='improvementaction',
            index=models.Index(fields=['assignee'], name='operations__assigne_61b87b_idx'),
        ),
        migrations.AddIndex(
            model_name='improvementaction',
            index=models.Index(fields=['due_date'], name='operations__due_dat_5e049d_idx'),
        ),
        migrations.AddIndex(
            model_name='improvementaction',
            index=models.Index(fields=['created_at'], name='operations__created_536540_idx'),
        ),
        migrations.AddIndex(
            model_name='exportrecord',
            index=models.Index(fields=['export_type'], name='operations__export__fea563_idx'),
        ),
        migrations.AddIndex(
            model_name='exportrecord',
            index=models.Index(fields=['status'], name='operations__status_32e014_idx'),
        ),
        migrations.AddIndex(
            model_name='exportrecord',
            index=models.Index(fields=['filter_hash'], name='operations__filter__2b4153_idx'),
        ),
        migrations.AddIndex(
            model_name='exportrecord',
            index=models.Index(fields=['created_by'], name='operations__created_02b6dd_idx'),
        ),
        migrations.AddIndex(
            model_name='exportrecord',
            index=models.Index(fields=['created_at'], name='operations__created_bfd6b8_idx'),
        ),
    ]
