# Generated by Django 4.2.30 on 2026-06-05 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='类别名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('requires_training', models.BooleanField(default=True, verbose_name='需要培训')),
                ('is_dangerous', models.BooleanField(default=False, verbose_name='危险设备')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '设备类别',
                'verbose_name_plural': '设备类别',
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['name'], name='equipment_e_name_c638d1_idx'), models.Index(fields=['requires_training'], name='equipment_e_require_492a4e_idx'), models.Index(fields=['is_dangerous'], name='equipment_e_is_dang_63450c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=200, verbose_name='设备名称')),
                ('model_number', models.CharField(blank=True, max_length=100, verbose_name='型号')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='序列号')),
                ('location', models.CharField(max_length=200, verbose_name='存放位置')),
                ('status', models.CharField(choices=[('available', '可用'), ('in_use', '使用中'), ('maintenance', '维护中'), ('broken', '故障'), ('retired', '已报废')], default='available', max_length=20, verbose_name='状态')),
                ('description', models.TextField(blank=True, verbose_name='设备描述')),
                ('specifications', models.JSONField(blank=True, default=dict, verbose_name='规格参数')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='购买日期')),
                ('last_maintenance_date', models.DateField(blank=True, null=True, verbose_name='上次维护日期')),
                ('next_maintenance_date', models.DateField(blank=True, null=True, verbose_name='下次维护日期')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='二维码')),
                ('image', models.ImageField(blank=True, null=True, upload_to='equipment/', verbose_name='设备图片')),
                ('max_booking_hours', models.IntegerField(default=4, verbose_name='最长预约时长(小时)')),
                ('require_approval', models.BooleanField(default=False, verbose_name='需要审批')),
                ('usage_count', models.IntegerField(default=0, verbose_name='使用次数')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipments', to='equipment.equipmentcategory', verbose_name='设备类别')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentUsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('notes', models.TextField(blank=True, verbose_name='使用备注')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='equipment.equipment', verbose_name='设备')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_usage_logs', to=settings.AUTH_USER_MODEL, verbose_name='使用人')),
            ],
            options={
                'verbose_name': '设备使用日志',
                'verbose_name_plural': '设备使用日志',
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['equipment', 'start_time'], name='equipment_e_equipme_4751c5_idx'), models.Index(fields=['user', 'start_time'], name='equipment_e_user_id_32bc8d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['name'], name='equipment_e_name_8baf3a_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['category'], name='equipment_e_categor_3d1cd8_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['status'], name='equipment_e_status_fb8540_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['location'], name='equipment_e_locatio_e2f5a2_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['created_at'], name='equipment_e_created_ddb06c_idx'),
        ),
    ]
