# Generated by Django 4.2.7 on 2026-06-06 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, verbose_name='原料名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='原料编码')),
                ('unit', models.CharField(max_length=20, verbose_name='计量单位')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('is_trial', models.BooleanField(default=False, verbose_name='是否试营原料')),
            ],
            options={
                'verbose_name': '原料',
                'verbose_name_plural': '原料',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TrialProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('start_date', models.DateField(verbose_name='试营开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='试营结束日期')),
                ('store_ids', models.JSONField(default=list, verbose_name='适用门店ID列表')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trial_info', to='materials.material', verbose_name='原料')),
            ],
            options={
                'verbose_name': '试营原料',
                'verbose_name_plural': '试营原料',
            },
        ),
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='materials.materialcategory', verbose_name='上级分类')),
            ],
            options={
                'verbose_name': '原料分类',
                'verbose_name_plural': '原料分类',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='material',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='materials.materialcategory', verbose_name='原料分类'),
        ),
    ]
