# Generated by Django 5.0.1 on 2026-06-11 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模型名称')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('google', 'Google'), ('local', '本地模型'), ('other', '其他')], max_length=50, verbose_name='提供商')),
                ('model_id', models.CharField(max_length=255, verbose_name='模型ID')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('max_tokens', models.IntegerField(default=4096, verbose_name='最大Token数')),
                ('input_price', models.DecimalField(decimal_places=6, default=0.0, max_digits=10, verbose_name='输入价格/千Token')),
                ('output_price', models.DecimalField(decimal_places=6, default=0.0, max_digits=10, verbose_name='输出价格/千Token')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('supports_streaming', models.BooleanField(default=True, verbose_name='支持流式输出')),
                ('capabilities', models.JSONField(blank=True, default=list, verbose_name='能力列表')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'AI模型',
                'verbose_name_plural': 'AI模型',
                'db_table': 'ai_models',
                'ordering': ['provider', 'name'],
            },
        ),
        migrations.CreateModel(
            name='APIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50, verbose_name='提供商')),
                ('api_key', models.CharField(max_length=500, verbose_name='API密钥')),
                ('base_url', models.URLField(blank=True, verbose_name='API基础URL')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认')),
                ('rate_limit_per_minute', models.IntegerField(default=60, verbose_name='每分钟请求限制')),
                ('rate_limit_per_day', models.IntegerField(default=10000, verbose_name='每日请求限制')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'API配置',
                'verbose_name_plural': 'API配置',
                'db_table': 'api_configs',
            },
        ),
        migrations.CreateModel(
            name='AILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(verbose_name='输入内容')),
                ('response', models.TextField(verbose_name='输出内容')),
                ('prompt_tokens', models.IntegerField(default=0, verbose_name='提示Token数')),
                ('completion_tokens', models.IntegerField(default=0, verbose_name='补全Token数')),
                ('total_tokens', models.IntegerField(default=0, verbose_name='总Token数')),
                ('cost', models.DecimalField(decimal_places=6, default=0.0, max_digits=10, verbose_name='费用')),
                ('latency', models.FloatField(default=0.0, verbose_name='响应时间(秒)')),
                ('status', models.CharField(default='success', max_length=20, verbose_name='状态')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('request_id', models.CharField(blank=True, max_length=100, verbose_name='请求ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_logs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='ai_service.aimodel', verbose_name='使用模型')),
            ],
            options={
                'verbose_name': 'AI调用日志',
                'verbose_name_plural': 'AI调用日志',
                'db_table': 'ai_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
