import { routeTree } from './routes';

export { routeTree };
// This file is generated by TanStack Router.
// Manual edits will be overwritten by `tsr generate`
// It serves as the entry point for the generated route tree.
export * from './routes';
