extends Node

signal card_dragged(card_id: String, position: Vector2)
signal card_dropped(card_id: String, slot_index: int)
signal card_pressed(card_id: String)
signal card_released(card_id: String)
signal tag_applied(card_id: String, tag_id: String)
signal tag_removed(card_id: String, tag_id: String)
signal evidence_linked(card_a_id: String, card_b_id: String)
signal evidence_unlinked(card_a_id: String, card_b_id: String)
signal hint_requested(level: int)
signal hint_revealed(hint_text: String, level: int)
signal timeline_submitted()
signal timeline_validated(result: Dictionary)
signal level_started(level_id: String)
signal level_completed(result: Dictionary)
signal level_failed(reasons: Array)
signal game_paused()
signal game_resumed()
signal settings_changed(category: String)
signal audio_play(sound_id: String, volume_db: float)
signal ui_state_changed(state: String, data: Dictionary)
signal feedback_shown(message: String, type: String, duration: float)
