# Generated by Django 4.2.7 on 2026-06-07 15:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='问题类型')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='问题大类')),
            ],
            options={
                'verbose_name': '问题类型',
                'verbose_name_plural': '问题类型',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='门店名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='门店编码')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='所属区域')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '门店',
                'verbose_name_plural': '门店',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='班组名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='班组编码')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='visit_dashboard.store', verbose_name='所属门店')),
            ],
            options={
                'verbose_name': '处理班组',
                'verbose_name_plural': '处理班组',
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=64, unique=True, verbose_name='工单编号')),
                ('customer_name', models.CharField(max_length=100, verbose_name='客户姓名')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='客户手机号')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('closed', '已关闭')], default='pending', max_length=20, verbose_name='工单状态')),
                ('description', models.TextField(blank=True, verbose_name='问题描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('handler', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_orders', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('problem_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='visit_dashboard.problemtype', verbose_name='问题类型')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='visit_dashboard.store', verbose_name='门店')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='visit_dashboard.team', verbose_name='处理班组')),
            ],
            options={
                'verbose_name': '工单',
                'verbose_name_plural': '工单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_status', models.CharField(choices=[('pending', '待回访'), ('completed', '已完成'), ('unreachable', '无法联系'), ('refused', '客户拒绝')], default='pending', max_length=20, verbose_name='回访状态')),
                ('satisfaction_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='满意度评分(1-5)')),
                ('recording_tags', models.JSONField(blank=True, default=list, verbose_name='录音标签')),
                ('visit_note', models.TextField(blank=True, verbose_name='回访备注')),
                ('visited_at', models.DateTimeField(blank=True, null=True, verbose_name='回访时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('visitor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_records', to=settings.AUTH_USER_MODEL, verbose_name='回访人')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_records', to='visit_dashboard.workorder', verbose_name='关联工单')),
            ],
            options={
                'verbose_name': '回访记录',
                'verbose_name_plural': '回访记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecondaryComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_type', models.CharField(max_length=100, verbose_name='投诉类型')),
                ('complaint_time', models.DateTimeField(verbose_name='二次投诉时间')),
                ('is_post_refund', models.BooleanField(default=False, verbose_name='是否退款后投诉')),
                ('description', models.TextField(blank=True, verbose_name='投诉描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_complaints', to='visit_dashboard.workorder', verbose_name='关联工单')),
            ],
            options={
                'verbose_name': '二次投诉',
                'verbose_name_plural': '二次投诉',
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='退款金额')),
                ('status', models.CharField(choices=[('pending', '待退款'), ('approved', '已审批'), ('refunded', '已退款'), ('rejected', '已驳回')], default='pending', max_length=20, verbose_name='退款状态')),
                ('refund_time', models.DateTimeField(blank=True, null=True, verbose_name='退款时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='visit_dashboard.workorder', verbose_name='关联工单')),
            ],
            options={
                'verbose_name': '退款记录',
                'verbose_name_plural': '退款记录',
            },
        ),
        migrations.CreateModel(
            name='MetricConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='口径名称')),
                ('dimension', models.CharField(choices=[('store', '门店'), ('problem_type', '问题类型'), ('team', '处理班组'), ('handler', '处理人')], max_length=20, verbose_name='对比维度')),
                ('low_score_threshold', models.IntegerField(default=3, verbose_name='低分阈值')),
                ('satisfaction_weight', models.FloatField(default=1.0, verbose_name='满意度权重')),
                ('include_unreachable', models.BooleanField(default=False, verbose_name='是否包含无法联系记录')),
                ('include_refused', models.BooleanField(default=False, verbose_name='是否包含客户拒绝记录')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '口径配置',
                'verbose_name_plural': '口径配置',
            },
        ),
        migrations.CreateModel(
            name='AsyncReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='报表名称')),
                ('report_type', models.CharField(max_length=50, verbose_name='报表类型')),
                ('params', models.JSONField(blank=True, default=dict, verbose_name='查询参数')),
                ('status', models.CharField(choices=[('pending', '生成中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='文件路径')),
                ('task_id', models.CharField(blank=True, max_length=200, verbose_name='Celery任务ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '异步报表',
                'verbose_name_plural': '异步报表',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnomalyAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomaly_type', models.CharField(choices=[('post_refund_complaint', '退款后二次投诉'), ('low_score_trend', '低分趋势异常'), ('data_quality', '数据质量异常')], max_length=30, verbose_name='异常类型')),
                ('annotation_text', models.TextField(verbose_name='注释内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('annotated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='注释人')),
                ('related_work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='visit_dashboard.workorder', verbose_name='关联工单')),
            ],
            options={
                'verbose_name': '异常点注释',
                'verbose_name_plural': '异常点注释',
            },
        ),
    ]
