# Generated by Django 4.2.7 on 2026-06-07 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visit_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='授权时间')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_users', to='visit_dashboard.store', verbose_name='门店')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_permissions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '门店权限',
                'verbose_name_plural': '门店权限',
                'unique_together': {('user', 'store')},
            },
        ),
    ]
