# Generated by Django 4.2.7 on 2026-06-05 18:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('core', '0001_initial'),
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('title', models.CharField(max_length=300, verbose_name='活动标题')),
                ('description', models.TextField(verbose_name='活动描述')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='event_covers/', verbose_name='封面图片')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('location', models.CharField(max_length=300, verbose_name='活动地点')),
                ('host', models.CharField(blank=True, max_length=200, verbose_name='主办方')),
                ('speaker', models.CharField(blank=True, max_length=200, verbose_name='主讲人')),
                ('max_participants', models.IntegerField(default=50, verbose_name='最大人数')),
                ('min_participants', models.IntegerField(default=0, verbose_name='最少人数')),
                ('registered_count', models.IntegerField(default=0, verbose_name='已报名人数')),
                ('checked_in_count', models.IntegerField(default=0, verbose_name='已签到人数')),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='活动费用')),
                ('points_required', models.IntegerField(default=0, verbose_name='所需积分')),
                ('points_reward', models.IntegerField(default=0, verbose_name='奖励积分')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('registration_open', '报名中'), ('registration_closed', '报名截止'), ('ongoing', '进行中'), ('completed', '已结束'), ('cancelled', '已取消')], default='draft', max_length=30, verbose_name='状态')),
                ('registration_deadline', models.DateTimeField(blank=True, null=True, verbose_name='报名截止时间')),
                ('cancellation_deadline', models.DateTimeField(blank=True, null=True, verbose_name='取消报名截止时间')),
                ('tags', models.CharField(blank=True, max_length=500, verbose_name='标签')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='core.user', verbose_name='创建人')),
            ],
            options={
                'verbose_name': '读书会活动',
                'verbose_name_plural': '读书会活动',
                'db_table': 'event',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认'), ('cancelled', '已取消'), ('checked_in', '已签到'), ('no_show', '未出席')], default='pending', max_length=20, verbose_name='状态')),
                ('registration_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='报名时间')),
                ('check_in_time', models.DateTimeField(blank=True, null=True, verbose_name='签到时间')),
                ('payment_status', models.CharField(default='unpaid', max_length=20, verbose_name='支付状态')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='支付金额')),
                ('points_used', models.IntegerField(default=0, verbose_name='使用积分')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='event_qr/', verbose_name='签到二维码')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='core.user', verbose_name='创建人')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event', verbose_name='活动')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to='members.member', verbose_name='会员')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='core.user', verbose_name='更新人')),
            ],
            options={
                'verbose_name': '活动报名',
                'verbose_name_plural': '活动报名',
                'db_table': 'event_registration',
                'ordering': ['-created_at'],
                'unique_together': {('event', 'member')},
            },
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('name', models.CharField(max_length=100, verbose_name='活动类型')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('color', models.CharField(default='#1890ff', max_length=7, verbose_name='标签颜色')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='core.user', verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='core.user', verbose_name='更新人')),
            ],
            options={
                'verbose_name': '活动类型',
                'verbose_name_plural': '活动类型',
                'db_table': 'event_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EventTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('ticket_no', models.CharField(max_length=50, unique=True, verbose_name='票号')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='tickets/', verbose_name='二维码')),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='出票时间')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='使用时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='core.user', verbose_name='创建人')),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='events.eventregistration', verbose_name='报名记录')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='core.user', verbose_name='更新人')),
            ],
            options={
                'verbose_name': '活动门票',
                'verbose_name_plural': '活动门票',
                'db_table': 'event_ticket',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.eventtype', verbose_name='活动类型'),
        ),
        migrations.AddField(
            model_name='event',
            name='related_books',
            field=models.ManyToManyField(blank=True, related_name='events', to='books.book', verbose_name='相关图书'),
        ),
        migrations.AddField(
            model_name='event',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='core.user', verbose_name='更新人'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status'], name='event_status_c263a9_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_time'], name='event_start_t_a7590c_idx'),
        ),
    ]
