export const metricsDefinition = {
  waterConsumption: {
    name: "灌溉用水量",
    unit: "m³",
    description: "指定时间段内的总灌溉水量",
    formula: "SUM(water_volume)",
    aggregation: "sum",
    dimensions: ["field", "crop", "pump_station", "strategy", "date"],
  },
  waterEfficiency: {
    name: "用水效率",
    unit: "m³/亩",
    description: "单位面积灌溉用水量",
    formula: "SUM(water_volume) / SUM(field_area)",
    aggregation: "ratio",
    dimensions: ["field", "crop", "date"],
  },
  irrigationFrequency: {
    name: "灌溉频次",
    unit: "次",
    description: "指定时间段内的灌溉次数",
    formula: "COUNT(irrigation_records)",
    aggregation: "count",
    dimensions: ["field", "crop", "pump_station", "strategy"],
  },
  avgFlowRate: {
    name: "平均流量",
    unit: "m³/h",
    description: "水泵运行时的平均流量",
    formula: "AVG(flow_rate)",
    aggregation: "avg",
    dimensions: ["pump_station", "field", "date"],
  },
  electricityConsumption: {
    name: "耗电量",
    unit: "kWh",
    description: "灌溉过程消耗的总电量",
    formula: "SUM(electricity_consumed)",
    aggregation: "sum",
    dimensions: ["field", "pump_station", "strategy", "date"],
  },
  electricityCost: {
    name: "电费",
    unit: "元",
    description: "灌溉产生的电费支出",
    formula: "SUM(electricity_cost)",
    aggregation: "sum",
    dimensions: ["field", "pump_station", "strategy", "date"],
  },
  unitWaterCost: {
    name: "单方水成本",
    unit: "元/m³",
    description: "每立方米灌溉水的电费成本",
    formula: "SUM(electricity_cost) / SUM(water_volume)",
    aggregation: "ratio",
    dimensions: ["pump_station", "strategy", "date"],
  },
  soilMoistureAvg: {
    name: "平均土壤湿度",
    unit: "%",
    description: "指定时间段内土壤湿度平均值",
    formula: "AVG(moisture_level)",
    aggregation: "avg",
    dimensions: ["field", "crop", "date"],
  },
  soilMoistureMin: {
    name: "最低土壤湿度",
    unit: "%",
    description: "指定时间段内土壤湿度最小值",
    formula: "MIN(moisture_level)",
    aggregation: "min",
    dimensions: ["field", "crop"],
  },
  rainfall: {
    name: "降雨量",
    unit: "mm",
    description: "指定时间段内的累计降雨量",
    formula: "SUM(rainfall)",
    aggregation: "sum",
    dimensions: ["date"],
  },
  postRainIrrigation: {
    name: "雨后灌溉量",
    unit: "m³",
    description: "降雨后24小时内的灌溉水量（需重点关注）",
    formula: "SUM(water_volume) WHERE is_after_rain = true",
    aggregation: "sum",
    dimensions: ["field", "crop", "date"],
  },
  pumpEfficiency: {
    name: "泵站运行效率",
    unit: "%",
    description: "泵站实际效率与额定效率的比值",
    formula: "(实际流量/额定流量) * 100",
    aggregation: "avg",
    dimensions: ["pump_station", "date"],
  },
  strategyYield: {
    name: "策略节水收益",
    unit: "%",
    description: "相比基准策略的节水量百分比",
    formula: "(基准用水量 - 策略用水量) / 基准用水量 * 100",
    aggregation: "ratio",
    dimensions: ["strategy", "crop", "field"],
  },
  moistureDeviation: {
    name: "湿度偏差率",
    unit: "%",
    description: "实际湿度与目标湿度的偏差百分比",
    formula: "|实际湿度 - 目标湿度| / 目标湿度 * 100",
    aggregation: "avg",
    dimensions: ["field", "strategy"],
  },
};

export const anomalyRules = {
  excessiveWatering: {
    name: "过量灌溉",
    severity: "high",
    condition: "water_volume > field_area * crop_water_requirement * 1.5",
    description: "灌溉水量超过作物需求的1.5倍",
    suggestion: "检查土壤湿度传感器，调整灌溉时长",
  },
  postRainOverwatering: {
    name: "雨后过度灌溉",
    severity: "high",
    condition: "is_after_rain = true AND rain_amount_24h > 10 AND water_volume > field_area * 2",
    description: "降雨超过10mm后仍大量灌溉",
    suggestion: "启用降雨联动控制，雨后自动减少灌溉",
  },
  lowPumpEfficiency: {
    name: "泵站效率低下",
    severity: "medium",
    condition: "pump_efficiency < rated_efficiency * 0.7",
    description: "泵站运行效率低于额定值的70%",
    suggestion: "检查水泵叶轮、管道堵塞或电压问题",
  },
  moistureAbnormal: {
    name: "土壤湿度异常",
    severity: "medium",
    condition: "moisture_level < optimal_min OR moisture_level > optimal_max",
    description: "土壤湿度超出作物适宜范围",
    suggestion: "调整灌溉计划，检查传感器校准",
  },
  highUnitCost: {
    name: "单方水成本偏高",
    severity: "low",
    condition: "unit_water_cost > avg_unit_cost * 1.2",
    description: "单方水成本超过区域平均20%",
    suggestion: "优化灌溉时段，利用低谷电价",
  },
  frequentIrrigation: {
    name: "灌溉过于频繁",
    severity: "low",
    condition: "daily_irrigation_count > 3",
    description: "单日灌溉次数超过3次",
    suggestion: "考虑增加单次灌水量，减少启停损耗",
  },
};

export const targetMoistureByCrop = {
  小麦: { min: 60, max: 80 },
  玉米: { min: 65, max: 85 },
  水稻: { min: 80, max: 95 },
  大豆: { min: 55, max: 75 },
  棉花: { min: 50, max: 70 },
  蔬菜: { min: 70, max: 90 },
  果树: { min: 55, max: 75 },
};
