# Generated by Django 5.2.15 on 2026-06-16 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150, verbose_name='用户名（冗余）')),
                ('operation', models.CharField(choices=[('create', '创建'), ('update', '更新'), ('delete', '删除'), ('login', '登录'), ('logout', '登出'), ('export', '导出'), ('approve', '审核通过'), ('reject', '审核拒绝'), ('notify', '发送通知'), ('assign', '分配任务'), ('complete', '完成任务')], max_length=30, verbose_name='操作类型')),
                ('module', models.CharField(max_length=100, verbose_name='模块')),
                ('description', models.TextField(blank=True, verbose_name='操作描述')),
                ('object_id', models.BigIntegerField(blank=True, null=True, verbose_name='对象ID')),
                ('old_data', models.JSONField(blank=True, null=True, verbose_name='旧数据')),
                ('new_data', models.JSONField(blank=True, null=True, verbose_name='新数据')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='用户代理')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='内容类型')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作用户')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='audit_audit_user_id_429f6b_idx'), models.Index(fields=['module', 'operation'], name='audit_audit_module_f15d3a_idx'), models.Index(fields=['created_at'], name='audit_audit_created_2c1626_idx')],
            },
        ),
    ]
