# Generated by Django 5.2.15 on 2026-06-21 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_type', models.CharField(choices=[('price_fluctuation', '价格波动'), ('contract_status', '合同状态统计'), ('supplier_risk', '供应商风险分布'), ('invoice_status', '发票状态统计'), ('usage_trend', '用量趋势'), ('approval_pending', '待办审批')], max_length=50, verbose_name='组件类型')),
                ('title', models.CharField(max_length=100, verbose_name='组件标题')),
                ('config', models.JSONField(default=dict, verbose_name='组件配置')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='显示顺序')),
                ('is_visible', models.BooleanField(default=True, verbose_name='是否显示')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '看板组件',
                'verbose_name_plural': '看板组件',
                'ordering': ['user', 'position'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('contract_expiry', '合同到期提醒'), ('approval_pending', '待审批通知'), ('supplier_risk', '供应商风险提醒'), ('invoice_overdue', '发票逾期提醒'), ('price_change', '价格变动通知'), ('system', '系统通知')], max_length=50, verbose_name='通知类型')),
                ('priority', models.CharField(choices=[('high', '高'), ('medium', '中'), ('low', '低')], default='medium', max_length=20, verbose_name='优先级')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('is_handled', models.BooleanField(default=False, verbose_name='是否已处理')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('handle_result', models.TextField(blank=True, verbose_name='处理结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='操作动作')),
                ('module', models.CharField(max_length=50, verbose_name='所属模块')),
                ('target_type', models.CharField(blank=True, max_length=100, verbose_name='目标类型')),
                ('target_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='目标ID')),
                ('description', models.TextField(blank=True, verbose_name='操作描述')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='客户端信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
