# Generated by Django 4.2.7 on 2026-06-06 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_date', models.DateField(verbose_name='手术日期')),
                ('operation_room', models.CharField(max_length=50, verbose_name='手术室')),
                ('patient_name', models.CharField(max_length=100, verbose_name='患者姓名')),
                ('patient_id', models.CharField(max_length=50, verbose_name='住院号')),
                ('surgeon', models.CharField(max_length=100, verbose_name='主刀医生')),
                ('anesthetist', models.CharField(max_length=100, verbose_name='麻醉医生')),
                ('status', models.CharField(choices=[('SCHEDULED', '已排班'), ('PREPARING', '备包中'), ('READY', '已备妥'), ('IN_PROGRESS', '进行中'), ('COMPLETED', '已完成'), ('CANCELLED', '已取消'), ('CHANGED', '已换术式')], default='SCHEDULED', max_length=20, verbose_name='状态')),
                ('schedule_time', models.TimeField(verbose_name='预计时间')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_operations', to=settings.AUTH_USER_MODEL, verbose_name='巡回护士')),
            ],
            options={
                'verbose_name': '手术排班',
                'verbose_name_plural': '手术排班',
            },
        ),
        migrations.CreateModel(
            name='PreparedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('item_type', models.CharField(default='REQUIRED', max_length=20, verbose_name='物品类型')),
                ('status', models.CharField(choices=[('PREPARED', '已备妥'), ('VERIFIED', '已核对'), ('USED', '已使用'), ('RETURNED', '已退回')], default='PREPARED', max_length=20, verbose_name='状态')),
                ('storage_location', models.CharField(blank=True, max_length=100, verbose_name='器械包位置')),
                ('prepared_at', models.DateTimeField(auto_now_add=True, verbose_name='备包时间')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='核对时间')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.batch', verbose_name='批号')),
                ('prepared_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prepared_items', to=settings.AUTH_USER_MODEL, verbose_name='备包人')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prepared_items', to='surgery.operationschedule', verbose_name='手术排班')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.supply', verbose_name='耗材')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_items', to=settings.AUTH_USER_MODEL, verbose_name='核对人')),
            ],
            options={
                'verbose_name': '备包物品',
                'verbose_name_plural': '备包物品',
            },
        ),
        migrations.CreateModel(
            name='SurgicalTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='术式名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='术式编码')),
                ('department', models.CharField(max_length=100, verbose_name='所属科室')),
                ('description', models.TextField(blank=True, verbose_name='术式描述')),
                ('estimated_duration', models.IntegerField(default=120, verbose_name='预计时长(分钟)')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '术式模板',
                'verbose_name_plural': '术式模板',
            },
        ),
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('is_high_value', models.BooleanField(default=False, verbose_name='是否高值耗材')),
                ('is_double_confirmed', models.BooleanField(default=False, verbose_name='是否双人确认')),
                ('scan_time', models.DateTimeField(auto_now_add=True, verbose_name='扫码时间')),
                ('confirm_time', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.batch', verbose_name='批号')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_usages', to=settings.AUTH_USER_MODEL, verbose_name='确认人')),
                ('prepared_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='surgery.prepareditem', verbose_name='备包物品')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='surgery.operationschedule', verbose_name='手术排班')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.supply', verbose_name='耗材')),
                ('used_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage_records', to=settings.AUTH_USER_MODEL, verbose_name='使用人')),
            ],
            options={
                'verbose_name': '领用记录',
                'verbose_name_plural': '领用记录',
            },
        ),
        migrations.CreateModel(
            name='ReturnRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('return_status', models.CharField(choices=[('UNOPENED', '未拆封'), ('OPENED', '已拆封'), ('DAMAGED', '需报损')], default='UNOPENED', max_length=20, verbose_name='退包状态')),
                ('is_high_value', models.BooleanField(default=False, verbose_name='是否高值耗材')),
                ('is_double_confirmed', models.BooleanField(default=False, verbose_name='是否双人确认')),
                ('return_time', models.DateTimeField(auto_now_add=True, verbose_name='退包时间')),
                ('confirm_time', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.batch', verbose_name='批号')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_returns', to=settings.AUTH_USER_MODEL, verbose_name='确认人')),
                ('returned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returned_items', to=settings.AUTH_USER_MODEL, verbose_name='退包人')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_records', to='surgery.operationschedule', verbose_name='手术排班')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.supply', verbose_name='耗材')),
            ],
            options={
                'verbose_name': '退包记录',
                'verbose_name_plural': '退包记录',
            },
        ),
        migrations.AddField(
            model_name='operationschedule',
            name='original_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='changed_operations', to='surgery.surgicaltemplate', verbose_name='原术式模板'),
        ),
        migrations.AddField(
            model_name='operationschedule',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='surgery.surgicaltemplate', verbose_name='术式模板'),
        ),
        migrations.CreateModel(
            name='HighValueAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('action_type', models.CharField(choices=[('USED', '使用'), ('RETURNED', '退回'), ('DAMAGED', '报损')], max_length=20, verbose_name='操作类型')),
                ('is_audited', models.BooleanField(default=False, verbose_name='是否已审核')),
                ('action_time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('audit_time', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('auditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audited_high_value', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.batch', verbose_name='批号')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='high_value_actions', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='high_value_audits', to='surgery.operationschedule', verbose_name='手术排班')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.supply', verbose_name='高值耗材')),
            ],
            options={
                'verbose_name': '高值耗材审计',
                'verbose_name_plural': '高值耗材审计',
            },
        ),
        migrations.CreateModel(
            name='TemplateSupplyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('REQUIRED', '必备耗材'), ('HIGH_VALUE', '高值耗材'), ('DEVICE', '器械包')], default='REQUIRED', max_length=20, verbose_name='物品类型')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('remark', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.supply', verbose_name='耗材')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_items', to='surgery.surgicaltemplate', verbose_name='术式模板')),
            ],
            options={
                'verbose_name': '模板耗材项',
                'verbose_name_plural': '模板耗材项',
                'unique_together': {('template', 'supply')},
            },
        ),
    ]
