# Generated by Django 4.2.7 on 2026-06-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surgery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagerecord',
            name='is_scan_created',
            field=models.BooleanField(default=False, verbose_name='是否扫码创建'),
        ),
    ]
