# Generated by Django 5.0.1 on 2026-06-11 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='会话标题')),
                ('status', models.CharField(choices=[('active', '进行中'), ('archived', '已归档'), ('deleted', '已删除')], db_index=True, default='active', max_length=20, verbose_name='状态')),
                ('customer_name', models.CharField(db_index=True, max_length=100, verbose_name='客户姓名')),
                ('customer_phone', models.CharField(db_index=True, max_length=20, verbose_name='客户手机号')),
                ('sales_operation', models.CharField(db_index=True, max_length=50, verbose_name='销售运营分组')),
                ('channel', models.CharField(choices=[('web', '网页'), ('app', 'APP'), ('wechat', '微信'), ('phone', '电话')], db_index=True, default='web', max_length=20, verbose_name='渠道')),
                ('priority', models.CharField(choices=[('normal', '普通'), ('high', '高'), ('urgent', '紧急')], db_index=True, default='normal', max_length=20, verbose_name='优先级')),
                ('ai_suggestion_adoption_rate', models.FloatField(default=0, verbose_name='AI建议采纳率')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '会话',
                'verbose_name_plural': '会话',
                'db_table': 'conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', '用户'), ('assistant', '助手'), ('system', '系统')], db_index=True, max_length=20, verbose_name='角色')),
                ('content', models.TextField(verbose_name='消息内容')),
                ('tokens_used', models.IntegerField(default=0, verbose_name='消耗Token数')),
                ('is_ai_suggestion', models.BooleanField(db_index=True, default=False, verbose_name='是否AI生成的建议')),
                ('is_adopted', models.BooleanField(db_index=True, default=False, verbose_name='是否已被客服采纳')),
                ('ai_model', models.CharField(blank=True, max_length=100, verbose_name='使用的AI模型')),
                ('prompt_version', models.CharField(blank=True, max_length=50, verbose_name='使用的提示词版本')),
                ('error_type', models.CharField(blank=True, db_index=True, default='none', max_length=50, verbose_name='调用异常类型')),
                ('error_message', models.TextField(blank=True, verbose_name='异常详情')),
                ('suggested_reply', models.TextField(blank=True, verbose_name='AI建议的回复内容')),
                ('review_status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝'), ('flagged', '需关注')], db_index=True, default='pending', max_length=20, verbose_name='审核状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conversations.conversation', verbose_name='会话')),
            ],
            options={
                'verbose_name': '消息',
                'verbose_name_plural': '消息',
                'db_table': 'messages',
                'ordering': ['created_at'],
            },
        ),
    ]
