# Generated by Django 4.2.30 on 2026-06-17 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('summary', models.CharField(blank=True, max_length=500, verbose_name='摘要')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '已归档')], default='draft', max_length=20, verbose_name='状态')),
                ('category', models.CharField(choices=[('product', '产品知识'), ('service', '服务流程'), ('faq', '常见问题'), ('troubleshooting', '故障排除'), ('policy', '政策法规'), ('other', '其他')], default='other', max_length=30, verbose_name='分类')),
                ('keywords', models.CharField(blank=True, max_length=500, verbose_name='关键词')),
                ('view_count', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('helpful_count', models.IntegerField(default=0, verbose_name='有用次数')),
                ('not_helpful_count', models.IntegerField(default=0, verbose_name='无用次数')),
                ('hit_count', models.IntegerField(default=0, verbose_name='命中次数')),
                ('is_tutorial', models.BooleanField(default=False, verbose_name='是否为教程')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('related_items', models.ManyToManyField(blank=True, related_name='related_to', to='knowledge.knowledgeitem', verbose_name='相关条目')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '知识库条目',
                'verbose_name_plural': '知识库条目',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('query_text', models.CharField(max_length=500, verbose_name='查询内容')),
                ('match_score', models.FloatField(blank=True, null=True, verbose_name='匹配度')),
                ('is_helpful', models.BooleanField(blank=True, null=True, verbose_name='是否有用')),
                ('has_reminder', models.BooleanField(default=False, verbose_name='是否设置提醒')),
                ('source', models.CharField(blank=True, max_length=50, verbose_name='来源')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='用户代理')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('matched_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queries', to='knowledge.knowledgeitem', verbose_name='匹配条目')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_queries', to=settings.AUTH_USER_MODEL, verbose_name='查询用户')),
            ],
            options={
                'verbose_name': '知识查询记录',
                'verbose_name_plural': '知识查询记录',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='knowledge_k_user_id_f0f174_idx'), models.Index(fields=['matched_item'], name='knowledge_k_matched_68e938_idx'), models.Index(fields=['created_at'], name='knowledge_k_created_962a14_idx'), models.Index(fields=['has_reminder'], name='knowledge_k_has_rem_fe40bc_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='knowledgeitem',
            index=models.Index(fields=['status'], name='knowledge_k_status_b29669_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeitem',
            index=models.Index(fields=['category'], name='knowledge_k_categor_f5a4b2_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeitem',
            index=models.Index(fields=['is_tutorial'], name='knowledge_k_is_tuto_790170_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeitem',
            index=models.Index(fields=['created_at'], name='knowledge_k_created_494a2a_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeitem',
            index=models.Index(fields=['view_count'], name='knowledge_k_view_co_57ccf7_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeitem',
            index=models.Index(fields=['hit_count'], name='knowledge_k_hit_cou_09f537_idx'),
        ),
    ]
