# Generated by Django 4.2.7 on 2026-06-06 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=100, verbose_name='批号')),
                ('production_date', models.DateField(verbose_name='生产日期')),
                ('expiry_date', models.DateField(verbose_name='有效期至')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('storage_location', models.CharField(max_length=100, verbose_name='存放位置')),
                ('is_expired', models.BooleanField(default=False, verbose_name='是否过期')),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='供应商')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='入库时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '批号库存',
                'verbose_name_plural': '批号库存',
            },
        ),
        migrations.CreateModel(
            name='SupplyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '耗材分类',
                'verbose_name_plural': '耗材分类',
            },
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='耗材名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='耗材编码')),
                ('supply_type', models.CharField(choices=[('NORMAL', '普通耗材'), ('HIGH_VALUE', '高值耗材'), ('DEVICE', '器械包')], default='NORMAL', max_length=20, verbose_name='耗材类型')),
                ('specification', models.CharField(blank=True, max_length=200, verbose_name='规格型号')),
                ('unit', models.CharField(default='个', max_length=20, verbose_name='单位')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='单价')),
                ('warning_threshold', models.IntegerField(default=10, verbose_name='库存预警阈值')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.supplycategory', verbose_name='分类')),
            ],
            options={
                'verbose_name': '耗材信息',
                'verbose_name_plural': '耗材信息',
            },
        ),
        migrations.CreateModel(
            name='StockWarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warning_type', models.CharField(choices=[('LOW_STOCK', '库存不足'), ('EXPIRING', '即将过期'), ('EXPIRED', '已过期')], max_length=20, verbose_name='预警类型')),
                ('warning_level', models.CharField(choices=[('INFO', '提示'), ('WARNING', '警告'), ('DANGER', '危险')], default='WARNING', max_length=20, verbose_name='预警级别')),
                ('message', models.TextField(verbose_name='预警信息')),
                ('is_handled', models.BooleanField(default=False, verbose_name='是否已处理')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.batch', verbose_name='批号')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.supply', verbose_name='耗材')),
            ],
            options={
                'verbose_name': '库存预警',
                'verbose_name_plural': '库存预警',
            },
        ),
        migrations.CreateModel(
            name='ScanRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(choices=[('IN', '入库扫描'), ('OUT', '领用扫描'), ('RETURN', '退包扫描'), ('INVENTORY', '盘点扫描')], max_length=20, verbose_name='扫描类型')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('is_double_confirmed', models.BooleanField(default=False, verbose_name='是否双人确认')),
                ('scan_time', models.DateTimeField(auto_now_add=True, verbose_name='扫描时间')),
                ('confirm_time', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.batch', verbose_name='批号')),
                ('confirm_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_scans', to=settings.AUTH_USER_MODEL, verbose_name='确认人')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scan_records', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '扫码记录',
                'verbose_name_plural': '扫码记录',
            },
        ),
        migrations.AddField(
            model_name='batch',
            name='supply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.supply', verbose_name='耗材'),
        ),
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('supply', 'batch_number')},
        ),
    ]
