# Generated by Django 4.2.30 on 2026-06-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='序列号')),
                ('status', models.CharField(choices=[('available', '可用'), ('reserved', '已预占'), ('borrowed', '已借出'), ('in_transit', '运输中'), ('maintenance', '维护中'), ('damaged', '损坏'), ('lost', '丢失')], default='available', max_length=50, verbose_name='状态')),
                ('location_detail', models.CharField(blank=True, max_length=200, verbose_name='具体位置')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='采购日期')),
                ('last_inspection_date', models.DateField(blank=True, null=True, verbose_name='上次检查日期')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '库存明细',
                'verbose_name_plural': '库存明细',
                'ordering': ['material__code', 'serial_number'],
            },
        ),
        migrations.CreateModel(
            name='InventoryReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认'), ('cancelled', '已取消'), ('fulfilled', '已完成')], default='pending', max_length=50, verbose_name='状态')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '库存预占',
                'verbose_name_plural': '库存预占',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='物料名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='物料编码')),
                ('type', models.CharField(choices=[('display_case', '展柜'), ('lighting', '灯具'), ('transport_box', '运输箱'), ('other', '其他')], max_length=50, verbose_name='物料类型')),
                ('specification', models.CharField(blank=True, max_length=200, verbose_name='规格型号')),
                ('is_valuable', models.BooleanField(default=False, verbose_name='是否贵重展具')),
                ('requires_double_confirm', models.BooleanField(default=False, verbose_name='需要双人确认')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('image', models.ImageField(blank=True, null=True, upload_to='materials/', verbose_name='图片')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '物料',
                'verbose_name_plural': '物料',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='类别名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='类别编码')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '物料类别',
                'verbose_name_plural': '物料类别',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='仓库名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='仓库编码')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='位置')),
            ],
            options={
                'verbose_name': '仓库',
                'verbose_name_plural': '仓库',
                'ordering': ['code'],
            },
        ),
    ]
