# Generated by Django 4.2.30 on 2026-06-06 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0002_initial'),
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryreservation',
            name='borrow_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='exhibitions.borroworder', verbose_name='借用单'),
        ),
    ]
