# Generated by Django 4.2.7 on 2026-06-06 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('task_id', models.CharField(max_length=100, unique=True, verbose_name='任务ID')),
                ('report_type', models.CharField(choices=[('loss_summary', '损耗汇总报表'), ('loss_detail', '损耗明细报表'), ('store_ranking', '门店排行报表'), ('material_analysis', '原料分析报表')], max_length=50, verbose_name='报表类型')),
                ('filters', models.JSONField(default=dict, verbose_name='筛选条件')),
                ('exclude_trial', models.BooleanField(default=False, verbose_name='排除试营原料')),
                ('status', models.CharField(choices=[('pending', '待生成'), ('processing', '生成中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('file_path', models.CharField(blank=True, max_length=255, verbose_name='文件路径')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='生成用户')),
            ],
            options={
                'verbose_name': '报表导出任务',
                'verbose_name_plural': '报表导出任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('task_id', models.CharField(max_length=100, unique=True, verbose_name='任务ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='文件名')),
                ('data_type', models.CharField(choices=[('inventory', '进货数据'), ('material_use', '领用数据'), ('wastage', '报损数据'), ('stocktake', '盘点数据'), ('sale', '销售数据'), ('staff_shift', '班次数据')], max_length=50, verbose_name='数据类型')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('total_rows', models.IntegerField(default=0, verbose_name='总行数')),
                ('success_rows', models.IntegerField(default=0, verbose_name='成功行数')),
                ('failed_rows', models.IntegerField(default=0, verbose_name='失败行数')),
                ('error_log', models.TextField(blank=True, verbose_name='错误日志')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='上传用户')),
            ],
            options={
                'verbose_name': '数据导入任务',
                'verbose_name_plural': '数据导入任务',
                'ordering': ['-created_at'],
            },
        ),
    ]
