# Generated by Django 4.2.7 on 2026-06-07 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importtask',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='完成时间'),
        ),
        migrations.AddField(
            model_name='reporttask',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='完成时间'),
        ),
        migrations.AddField(
            model_name='reporttask',
            name='error_log',
            field=models.TextField(blank=True, verbose_name='错误日志'),
        ),
    ]
