# Generated by Django 4.2.7 on 2026-06-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='ISBN')),
                ('title', models.CharField(max_length=300, verbose_name='书名')),
                ('author', models.CharField(max_length=200, verbose_name='作者')),
                ('translator', models.CharField(blank=True, max_length=200, verbose_name='译者')),
                ('publisher', models.CharField(max_length=200, verbose_name='出版社')),
                ('publish_date', models.DateField(blank=True, null=True, verbose_name='出版日期')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='定价')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='进货价')),
                ('pages', models.IntegerField(blank=True, null=True, verbose_name='页数')),
                ('binding', models.CharField(blank=True, max_length=50, verbose_name='装帧')),
                ('language', models.CharField(default='中文', max_length=50, verbose_name='语言')),
                ('summary', models.TextField(blank=True, verbose_name='内容简介')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='book_covers/', verbose_name='封面图片')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='库存数量')),
                ('reserved_quantity', models.IntegerField(default=0, verbose_name='预留数量')),
                ('low_stock_threshold', models.IntegerField(default=5, verbose_name='低库存阈值')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='书架位置')),
                ('status', models.CharField(choices=[('in_stock', '有库存'), ('low_stock', '库存不足'), ('out_of_stock', '缺货')], default='in_stock', max_length=20, verbose_name='状态')),
                ('allow_reservation', models.BooleanField(default=True, verbose_name='是否允许预留')),
            ],
            options={
                'verbose_name': '图书',
                'verbose_name_plural': '图书',
                'db_table': 'book',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('image', models.ImageField(upload_to='book_images/', verbose_name='图片')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_primary', models.BooleanField(default=False, verbose_name='是否主图')),
            ],
            options={
                'verbose_name': '图书图片',
                'verbose_name_plural': '图书图片',
                'db_table': 'book_image',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '图书分类',
                'verbose_name_plural': '图书分类',
                'db_table': 'book_category',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('name', models.CharField(max_length=200, verbose_name='供应商名称')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='联系电话')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='地址')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '供应商',
                'verbose_name_plural': '供应商',
                'db_table': 'book_supplier',
                'ordering': ['-created_at'],
            },
        ),
    ]
