# Generated by Django 4.2.7 on 2026-06-05 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='费用名称')),
                ('fee_type', models.CharField(choices=[('tuition', '学费'), ('meal', '餐费'), ('activity', '活动费'), ('material', '材料费'), ('other', '其他')], default='tuition', max_length=20, verbose_name='费用类型')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='截止日期')),
                ('is_active', models.BooleanField(default=True, verbose_name='有效')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('class_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_items', to='children.classgroup', verbose_name='适用班级')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '收费项目',
                'verbose_name_plural': '收费项目',
                'db_table': 'finance_feeitem',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='应缴金额')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='实缴金额')),
                ('status', models.CharField(choices=[('pending', '待缴费'), ('paid', '已缴费'), ('overdue', '已逾期'), ('waived', '已减免')], default='pending', max_length=10, verbose_name='状态')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='截止日期')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='缴费时间')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='children.child', verbose_name='儿童')),
                ('fee_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.feeitem', verbose_name='收费项目')),
            ],
            options={
                'verbose_name': '缴费记录',
                'verbose_name_plural': '缴费记录',
                'db_table': 'finance_payment',
                'indexes': [models.Index(fields=['child', 'status'], name='idx_payment_child_status'), models.Index(fields=['status', 'due_date'], name='idx_payment_status_due')],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('reason', models.TextField(verbose_name='请假原因')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('rejected', '已拒绝')], default='pending', max_length=10, verbose_name='状态')),
                ('review_remark', models.TextField(blank=True, default='', verbose_name='审批备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='children.child', verbose_name='儿童')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_leaves', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
            ],
            options={
                'verbose_name': '请假申请',
                'verbose_name_plural': '请假申请',
                'db_table': 'finance_leaverequest',
                'indexes': [models.Index(fields=['child', 'status'], name='idx_leave_child_status'), models.Index(fields=['requester', 'status'], name='idx_leave_requester_status')],
            },
        ),
        migrations.AddIndex(
            model_name='feeitem',
            index=models.Index(fields=['fee_type', 'is_active'], name='idx_feeitem_type_active'),
        ),
    ]
