import type { AchievementDef } from "@/game/types";

export const ACHIEVEMENT_DEFS: AchievementDef[] = [
  {
    id: "first_product",
    name: "初次生产",
    description: "生产第1个产品",
    category: "production",
    target: 1,
    icon: "📦",
  },
  {
    id: "speed_demon",
    name: "速度恶魔",
    description: "1分钟内交付5个订单",
    category: "production",
    target: 5,
    icon: "⚡",
  },
  {
    id: "mass_production",
    name: "量产专家",
    description: "累计生产1000个",
    category: "production",
    target: 1000,
    icon: "🏭",
  },
  {
    id: "first_order",
    name: "接单新手",
    description: "完成第1个订单",
    category: "order",
    target: 1,
    icon: "📋",
  },
  {
    id: "order_master",
    name: "订单大师",
    description: "完成50个订单",
    category: "order",
    target: 50,
    icon: "🏆",
  },
  {
    id: "elite_handler",
    name: "精英猎手",
    description: "完成5个精英订单",
    category: "order",
    target: 5,
    icon: "💎",
  },
  {
    id: "first_upgrade",
    name: "初次升级",
    description: "首次升级机器",
    category: "upgrade",
    target: 1,
    icon: "🔧",
  },
  {
    id: "maxed_out",
    name: "满级之力",
    description: "将任意机器升至满级",
    category: "upgrade",
    target: 1,
    icon: "🔝",
  },
  {
    id: "upgrade_frenzy",
    name: "升级狂人",
    description: "累计升级20次",
    category: "upgrade",
    target: 20,
    icon: "⬆️",
  },
  {
    id: "no_rejects",
    name: "零次品",
    description: "连续20个产品全部合格",
    category: "special",
    target: 20,
    icon: "✅",
  },
  {
    id: "bottleneck_free",
    name: "畅通无阻",
    description: "单关无瓶颈通关",
    category: "special",
    target: 1,
    icon: "🚀",
  },
  {
    id: "offline_collector",
    name: "离线收藏家",
    description: "领取5次离线收益",
    category: "special",
    target: 5,
    icon: "💤",
  },
];
