import type { LevelConfig } from "@/game/types";

export const LEVEL_CONFIGS: LevelConfig[] = [
  {
    id: "level_01",
    name: "初始车间",
    gridWidth: 8,
    gridHeight: 6,
    startCoins: 500,
    availableMachines: ["press", "conveyor", "qa_station"],
    orderPool: ["order_easy_01", "order_easy_02", "order_easy_03"],
    starThresholds: { 1: 300, 2: 180, 3: 90 },
    entryPoint: { x: 0, y: 2 },
    exitPoint: { x: 7, y: 4 },
    entryDirection: "right",
    description: "学习基本生产线搭建，使用冲压机加工零件",
  },
  {
    id: "level_02",
    name: "扩展车间",
    gridWidth: 8,
    gridHeight: 6,
    startCoins: 800,
    availableMachines: ["press", "cutter", "conveyor", "qa_station"],
    orderPool: [
      "order_easy_03",
      "order_easy_04",
      "order_normal_01",
      "order_normal_02",
    ],
    starThresholds: { 1: 360, 2: 240, 3: 120 },
    entryPoint: { x: 0, y: 2 },
    exitPoint: { x: 7, y: 4 },
    entryDirection: "right",
    description: "解锁切割机，应对更复杂的加工需求",
  },
  {
    id: "level_03",
    name: "焊接工厂",
    gridWidth: 10,
    gridHeight: 6,
    startCoins: 1200,
    availableMachines: ["press", "cutter", "welder", "conveyor", "qa_station"],
    orderPool: [
      "order_normal_02",
      "order_normal_03",
      "order_normal_04",
      "order_hard_01",
    ],
    starThresholds: { 1: 420, 2: 300, 3: 150 },
    entryPoint: { x: 0, y: 2 },
    exitPoint: { x: 9, y: 4 },
    entryDirection: "right",
    description: "焊接机上线，三道工序组合生产",
  },
  {
    id: "level_04",
    name: "喷涂车间",
    gridWidth: 10,
    gridHeight: 8,
    startCoins: 1500,
    availableMachines: [
      "press",
      "cutter",
      "welder",
      "painter",
      "conveyor",
      "qa_station",
    ],
    orderPool: [
      "order_hard_01",
      "order_hard_02",
      "order_hard_03",
      "order_elite_01",
    ],
    starThresholds: { 1: 480, 2: 360, 3: 180 },
    entryPoint: { x: 0, y: 3 },
    exitPoint: { x: 9, y: 5 },
    entryDirection: "right",
    description: "喷涂机加入，四道工序挑战精英订单",
  },
  {
    id: "level_05",
    name: "全自动工厂",
    gridWidth: 12,
    gridHeight: 8,
    startCoins: 2000,
    availableMachines: [
      "press",
      "cutter",
      "welder",
      "painter",
      "conveyor",
      "qa_station",
    ],
    orderPool: [
      "order_easy_01",
      "order_normal_01",
      "order_normal_03",
      "order_hard_02",
      "order_hard_03",
      "order_elite_01",
      "order_elite_02",
      "order_elite_03",
      "order_elite_04",
    ],
    starThresholds: { 1: 600, 2: 420, 3: 210 },
    entryPoint: { x: 0, y: 3 },
    exitPoint: { x: 11, y: 5 },
    entryDirection: "right",
    description: "全机器解锁，面对所有难度的订单挑战",
  },
];
