import type { MachineType } from "@/game/types";

export const MACHINE_TYPES: Record<string, MachineType> = {
  press: {
    id: "press",
    name: "冲压机",
    baseSpeed: 2,
    baseQuality: 0.85,
    upgradeCostMultiplier: 1.8,
    maxLevel: 10,
    cost: 100,
    sprite: "press",
    bufferCapacity: 3,
  },
  cutter: {
    id: "cutter",
    name: "切割机",
    baseSpeed: 3,
    baseQuality: 0.8,
    upgradeCostMultiplier: 2.0,
    maxLevel: 10,
    cost: 150,
    sprite: "cutter",
    bufferCapacity: 2,
  },
  welder: {
    id: "welder",
    name: "焊接机",
    baseSpeed: 4,
    baseQuality: 0.75,
    upgradeCostMultiplier: 2.2,
    maxLevel: 10,
    cost: 200,
    sprite: "welder",
    bufferCapacity: 2,
  },
  painter: {
    id: "painter",
    name: "喷涂机",
    baseSpeed: 3,
    baseQuality: 0.9,
    upgradeCostMultiplier: 1.9,
    maxLevel: 10,
    cost: 180,
    sprite: "painter",
    bufferCapacity: 3,
  },
  qa_station: {
    id: "qa_station",
    name: "质检点",
    baseSpeed: 1,
    baseQuality: 1.0,
    upgradeCostMultiplier: 1.5,
    maxLevel: 5,
    cost: 120,
    sprite: "qa",
    bufferCapacity: 5,
  },
  conveyor: {
    id: "conveyor",
    name: "传送带",
    baseSpeed: 0.5,
    baseQuality: 1.0,
    upgradeCostMultiplier: 1.3,
    maxLevel: 5,
    cost: 30,
    sprite: "conveyor",
    bufferCapacity: 10,
  },
};

export type MachineTypeMap = typeof MACHINE_TYPES;
