import type { OrderTemplate } from "@/game/types";

export const ORDER_TEMPLATES: OrderTemplate[] = [
  {
    id: "order_easy_01",
    name: "简单零件",
    difficulty: "easy",
    requiredCount: 5,
    timeLimit: 120,
    coinReward: 50,
    expReward: 10,
    requiredStages: 1,
  },
  {
    id: "order_easy_02",
    name: "基础冲压件",
    difficulty: "easy",
    requiredCount: 8,
    timeLimit: 120,
    coinReward: 70,
    expReward: 15,
    requiredStages: 1,
  },
  {
    id: "order_easy_03",
    name: "初级加工品",
    difficulty: "easy",
    requiredCount: 10,
    timeLimit: 120,
    coinReward: 100,
    expReward: 20,
    requiredStages: 1,
  },
  {
    id: "order_easy_04",
    name: "标准件批次",
    difficulty: "easy",
    requiredCount: 6,
    timeLimit: 120,
    coinReward: 60,
    expReward: 12,
    requiredStages: 1,
  },
  {
    id: "order_normal_01",
    name: "精密冲压件",
    difficulty: "normal",
    requiredCount: 10,
    timeLimit: 180,
    coinReward: 100,
    expReward: 20,
    requiredStages: 2,
  },
  {
    id: "order_normal_02",
    name: "切割组件",
    difficulty: "normal",
    requiredCount: 15,
    timeLimit: 180,
    coinReward: 150,
    expReward: 30,
    requiredStages: 2,
  },
  {
    id: "order_normal_03",
    name: "复合零件",
    difficulty: "normal",
    requiredCount: 20,
    timeLimit: 180,
    coinReward: 250,
    expReward: 40,
    requiredStages: 2,
  },
  {
    id: "order_normal_04",
    name: "中型装配件",
    difficulty: "normal",
    requiredCount: 12,
    timeLimit: 180,
    coinReward: 180,
    expReward: 25,
    requiredStages: 2,
  },
  {
    id: "order_hard_01",
    name: "焊接总成",
    difficulty: "hard",
    requiredCount: 20,
    timeLimit: 240,
    coinReward: 250,
    expReward: 40,
    requiredStages: 3,
  },
  {
    id: "order_hard_02",
    name: "高强度组件",
    difficulty: "hard",
    requiredCount: 30,
    timeLimit: 240,
    coinReward: 350,
    expReward: 60,
    requiredStages: 3,
  },
  {
    id: "order_hard_03",
    name: "复杂装配件",
    difficulty: "hard",
    requiredCount: 40,
    timeLimit: 240,
    coinReward: 500,
    expReward: 80,
    requiredStages: 3,
  },
  {
    id: "order_elite_01",
    name: "全流程成品",
    difficulty: "elite",
    requiredCount: 40,
    timeLimit: 300,
    coinReward: 500,
    expReward: 80,
    requiredStages: 4,
  },
  {
    id: "order_elite_02",
    name: "高端定制件",
    difficulty: "elite",
    requiredCount: 50,
    timeLimit: 300,
    coinReward: 750,
    expReward: 120,
    requiredStages: 4,
  },
  {
    id: "order_elite_03",
    name: "旗舰产品",
    difficulty: "elite",
    requiredCount: 60,
    timeLimit: 300,
    coinReward: 1000,
    expReward: 150,
    requiredStages: 4,
  },
  {
    id: "order_elite_04",
    name: "限量精品",
    difficulty: "elite",
    requiredCount: 45,
    timeLimit: 300,
    coinReward: 800,
    expReward: 100,
    requiredStages: 5,
  },
];
