const bcrypt = require('bcryptjs');
const { ObjectId } = require('mongodb');

const SALT_ROUNDS = 10;

const getPasswordHash = (password) => {
  return bcrypt.hashSync(password, SALT_ROUNDS);
};

const generateSeedData = () => {
  const hashedPassword = getPasswordHash('123456');

  const adminId = new ObjectId().toString();
  const trainer1Id = new ObjectId().toString();
  const trainer2Id = new ObjectId().toString();
  const reviewerId = new ObjectId().toString();

  const users = [
    {
      _id: adminId,
      username: 'admin',
      password: hashedPassword,
      name: '系统管理员',
      role: 'admin',
      phone: '13800000000',
      email: 'admin@example.com',
      status: 'active',
      createdAt: new Date('2024-01-01').toISOString(),
      updatedAt: new Date('2024-01-01').toISOString(),
    },
    {
      _id: trainer1Id,
      username: 'trainer1',
      password: hashedPassword,
      name: '李训练',
      role: 'trainer',
      phone: '13800000001',
      email: 'trainer1@example.com',
      status: 'active',
      createdAt: new Date('2024-01-02').toISOString(),
      updatedAt: new Date('2024-01-02').toISOString(),
    },
    {
      _id: trainer2Id,
      username: 'trainer2',
      password: hashedPassword,
      name: '王教练',
      role: 'trainer',
      phone: '13800000002',
      email: 'trainer2@example.com',
      status: 'active',
      createdAt: new Date('2024-01-03').toISOString(),
      updatedAt: new Date('2024-01-03').toISOString(),
    },
    {
      _id: reviewerId,
      username: 'reviewer',
      password: hashedPassword,
      name: '张审核',
      role: 'reviewer',
      phone: '13800000003',
      email: 'reviewer@example.com',
      status: 'active',
      createdAt: new Date('2024-01-04').toISOString(),
      updatedAt: new Date('2024-01-04').toISOString(),
    },
  ];

  const pet1Id = new ObjectId().toString();
  const pet2Id = new ObjectId().toString();
  const pet3Id = new ObjectId().toString();
  const pet4Id = new ObjectId().toString();
  const pet5Id = new ObjectId().toString();

  const pets = [
    {
      _id: pet1Id,
      petNo: 'PET202401001',
      name: '大黄',
      species: 'dog',
      breed: '金毛寻回犬',
      gender: 'male',
      birthday: new Date('2022-03-15').toISOString(),
      weight: 28.5,
      color: '金色',
      chipNo: '900123456789001',
      vaccineStatus: {
        rabies: true,
        distemper: true,
        parvovirus: true,
        catPlague: false,
      },
      sterilized: true,
      healthStatus: 'healthy',
      temperament: '温顺、亲人、活泼',
      dietaryNotes: '每日两餐，每餐200g狗粮，禁鸡骨头',
      medicalNotes: '无重大疾病史，定期驱虫',
      trainerId: trainer1Id,
      status: 'fostering',
      fosterStartTime: new Date('2024-01-10').toISOString(),
      createdBy: adminId,
      updatedBy: adminId,
      createdAt: new Date('2024-01-05').toISOString(),
      updatedAt: new Date('2024-01-10').toISOString(),
    },
    {
      _id: pet2Id,
      petNo: 'PET202401002',
      name: '小黑',
      species: 'dog',
      breed: '拉布拉多',
      gender: 'female',
      birthday: new Date('2023-06-20').toISOString(),
      weight: 25.0,
      color: '黑色',
      chipNo: '900123456789002',
      vaccineStatus: {
        rabies: true,
        distemper: true,
        parvovirus: true,
        catPlague: false,
      },
      sterilized: false,
      healthStatus: 'healthy',
      temperament: '聪明、活泼、好动',
      dietaryNotes: '每日两餐，食量较大，注意控制体重',
      medicalNotes: '皮肤敏感，潮湿天气易发痒',
      trainerId: trainer1Id,
      status: 'fostering',
      fosterStartTime: new Date('2024-02-01').toISOString(),
      createdBy: adminId,
      updatedBy: adminId,
      createdAt: new Date('2024-01-08').toISOString(),
      updatedAt: new Date('2024-02-01').toISOString(),
    },
    {
      _id: pet3Id,
      petNo: 'PET202401003',
      name: '花花',
      species: 'cat',
      breed: '英国短毛猫',
      gender: 'female',
      birthday: new Date('2023-09-10').toISOString(),
      weight: 4.2,
      color: '三花',
      chipNo: '900123456789003',
      vaccineStatus: {
        rabies: true,
        distemper: false,
        parvovirus: false,
        catPlague: true,
      },
      sterilized: true,
      healthStatus: 'healthy',
      temperament: '高冷、独立、安静',
      dietaryNotes: '猫粮为主，偶尔零食，需充足饮水',
      medicalNotes: '泌尿系统健康，定期体检',
      trainerId: trainer2Id,
      status: 'pending',
      fosterStartTime: null,
      createdBy: adminId,
      updatedBy: adminId,
      createdAt: new Date('2024-01-12').toISOString(),
      updatedAt: new Date('2024-01-12').toISOString(),
    },
    {
      _id: pet4Id,
      petNo: 'PET202401004',
      name: '豆豆',
      species: 'cat',
      breed: '橘猫',
      gender: 'male',
      birthday: new Date('2022-12-01').toISOString(),
      weight: 5.8,
      color: '橘色',
      chipNo: '900123456789004',
      vaccineStatus: {
        rabies: true,
        distemper: false,
        parvovirus: false,
        catPlague: true,
      },
      sterilized: true,
      healthStatus: 'recovering',
      temperament: '黏人、贪吃、爱玩',
      dietaryNotes: '控制饮食，体重超标，减肥粮',
      medicalNotes: '轻度肥胖，正在减肥中',
      trainerId: trainer2Id,
      status: 'fostering',
      fosterStartTime: new Date('2024-03-05').toISOString(),
      createdBy: adminId,
      updatedBy: adminId,
      createdAt: new Date('2024-01-15').toISOString(),
      updatedAt: new Date('2024-03-05').toISOString(),
    },
    {
      _id: pet5Id,
      petNo: 'PET202401005',
      name: '小白',
      species: 'dog',
      breed: '比熊',
      gender: 'male',
      birthday: new Date('2024-01-01').toISOString(),
      weight: 3.5,
      color: '白色',
      chipNo: '',
      vaccineStatus: {
        rabies: false,
        distemper: false,
        parvovirus: false,
        catPlague: false,
      },
      sterilized: false,
      healthStatus: 'healthy',
      temperament: '活泼、好动、黏人',
      dietaryNotes: '幼犬粮，每日三餐，少量多次',
      medicalNotes: '幼犬，需完成疫苗接种',
      trainerId: trainer1Id,
      status: 'pending',
      fosterStartTime: null,
      createdBy: adminId,
      updatedBy: adminId,
      createdAt: new Date('2024-01-20').toISOString(),
      updatedAt: new Date('2024-01-20').toISOString(),
    },
  ];

  const app1Id = new ObjectId().toString();
  const app2Id = new ObjectId().toString();
  const app3Id = new ObjectId().toString();
  const app4Id = new ObjectId().toString();
  const app5Id = new ObjectId().toString();

  const adoptionApplications = [
    {
      _id: app1Id,
      applicationNo: 'ADP202401001',
      petId: pet1Id,
      petNo: 'PET202401001',
      petName: '大黄',
      applicantName: '陈小明',
      applicantPhone: '13912345678',
      applicantIdCard: '110101199001011234',
      applicantEmail: 'chenxm@example.com',
      applicantAddress: '北京市朝阳区望京街道某小区1号楼101室',
      housingType: 'apartment',
      hasPetExperience: true,
      currentPets: '之前养过一只金毛，已经10岁去世了',
      familyMembers: 3,
      hasChildren: true,
      workSchedule: '朝九晚五，周末双休',
      monthlyBudget: 1000,
      adoptionReason: '孩子喜欢狗狗，家里有足够空间',
      emergencyContact: {
        name: '陈先生',
        phone: '13888888888',
        relationship: '父亲',
      },
      veterinaryInfo: '望京宠物医院',
      missingFields: [],
      trainerId: trainer1Id,
      trainerName: '李训练',
      reviewerId: reviewerId,
      reviewerName: '张审核',
      status: 'approved',
      reviewComments: '申请人条件良好，有养宠经验，家庭环境适合养狗',
      rejectionReason: '',
      submittedAt: new Date('2024-02-10').toISOString(),
      reviewedAt: new Date('2024-02-15').toISOString(),
      completedAt: null,
      createdBy: trainer1Id,
      updatedBy: reviewerId,
      createdAt: new Date('2024-02-05').toISOString(),
      updatedAt: new Date('2024-02-15').toISOString(),
    },
    {
      _id: app2Id,
      applicationNo: 'ADP202401002',
      petId: pet2Id,
      petNo: 'PET202401002',
      petName: '小黑',
      applicantName: '刘小红',
      applicantPhone: '13698765432',
      applicantIdCard: '',
      applicantEmail: '',
      applicantAddress: '北京市海淀区中关村大街',
      housingType: 'apartment',
      hasPetExperience: false,
      currentPets: '',
      familyMembers: 2,
      hasChildren: false,
      workSchedule: '',
      monthlyBudget: 800,
      adoptionReason: '喜欢狗狗，想有个伴',
      emergencyContact: {
        name: '',
        phone: '',
        relationship: '',
      },
      veterinaryInfo: '',
      missingFields: ['applicantIdCard', 'applicantEmail', 'workSchedule', 'emergencyContact.name', 'emergencyContact.phone'],
      trainerId: trainer1Id,
      trainerName: '李训练',
      reviewerId: null,
      reviewerName: '',
      status: 'draft',
      reviewComments: '',
      rejectionReason: '',
      submittedAt: null,
      reviewedAt: null,
      completedAt: null,
      createdBy: trainer1Id,
      updatedBy: trainer1Id,
      createdAt: new Date('2024-02-10').toISOString(),
      updatedAt: new Date('2024-02-12').toISOString(),
    },
    {
      _id: app3Id,
      applicationNo: 'ADP202401003',
      petId: pet3Id,
      petNo: 'PET202401003',
      petName: '花花',
      applicantName: '张小华',
      applicantPhone: '13511112222',
      applicantIdCard: '310101199505054321',
      applicantEmail: 'zhanghua@example.com',
      applicantAddress: '上海市浦东新区陆家嘴环路',
      housingType: 'apartment',
      hasPetExperience: true,
      currentPets: '现在有一只英短，想再养一只作伴',
      familyMembers: 2,
      hasChildren: false,
      workSchedule: '自由职业，在家时间多',
      monthlyBudget: 500,
      adoptionReason: '喜欢猫咪，有养猫经验',
      emergencyContact: {
        name: '张女士',
        phone: '13666666666',
        relationship: '姐姐',
      },
      veterinaryInfo: '浦东宠物诊所',
      missingFields: [],
      trainerId: trainer2Id,
      trainerName: '王教练',
      reviewerId: reviewerId,
      reviewerName: '张审核',
      status: 'under_review',
      reviewComments: '',
      rejectionReason: '',
      submittedAt: new Date('2024-03-01').toISOString(),
      reviewedAt: null,
      completedAt: null,
      createdBy: trainer2Id,
      updatedBy: reviewerId,
      createdAt: new Date('2024-02-25').toISOString(),
      updatedAt: new Date('2024-03-02').toISOString(),
    },
    {
      _id: app4Id,
      applicationNo: 'ADP202401004',
      petId: pet4Id,
      petNo: 'PET202401004',
      petName: '豆豆',
      applicantName: '王大山',
      applicantPhone: '13733334444',
      applicantIdCard: '440101198808085678',
      applicantEmail: 'wangds@example.com',
      applicantAddress: '广州市天河区体育西路',
      housingType: 'house',
      hasPetExperience: true,
      currentPets: '两只土猫',
      familyMembers: 4,
      hasChildren: true,
      workSchedule: '企业高管，家中有保姆',
      monthlyBudget: 2000,
      adoptionReason: '孩子喜欢橘猫，家里条件好',
      emergencyContact: {
        name: '王夫人',
        phone: '13777777777',
        relationship: '配偶',
      },
      veterinaryInfo: '天河宠物医院',
      missingFields: [],
      trainerId: trainer2Id,
      trainerName: '王教练',
      reviewerId: null,
      reviewerName: '',
      status: 'submitted',
      reviewComments: '',
      rejectionReason: '',
      submittedAt: new Date('2024-03-10').toISOString(),
      reviewedAt: null,
      completedAt: null,
      createdBy: trainer2Id,
      updatedBy: trainer2Id,
      createdAt: new Date('2024-03-05').toISOString(),
      updatedAt: new Date('2024-03-10').toISOString(),
    },
    {
      _id: app5Id,
      applicationNo: 'ADP202401005',
      petId: pet1Id,
      petNo: 'PET202401001',
      petName: '大黄',
      applicantName: '李大爷',
      applicantPhone: '13855556666',
      applicantIdCard: '',
      applicantEmail: '',
      applicantAddress: '成都市锦江区春熙路',
      housingType: 'apartment',
      hasPetExperience: false,
      currentPets: '',
      familyMembers: 1,
      hasChildren: false,
      workSchedule: '退休',
      monthlyBudget: 600,
      adoptionReason: '退休在家孤单，想养只狗作伴',
      emergencyContact: {
        name: '李阿姨',
        phone: '13899999999',
        relationship: '老伴',
      },
      veterinaryInfo: '',
      missingFields: ['applicantIdCard', 'applicantEmail', 'veterinaryInfo'],
      trainerId: trainer1Id,
      trainerName: '李训练',
      reviewerId: reviewerId,
      reviewerName: '张审核',
      status: 'rejected',
      reviewComments: '年龄较大，建议考虑小型犬',
      rejectionReason: '申请人年龄偏大，金毛体型较大，日常遛狗可能有困难。建议考虑体型较小的犬种。',
      submittedAt: new Date('2024-01-20').toISOString(),
      reviewedAt: new Date('2024-01-25').toISOString(),
      completedAt: null,
      createdBy: trainer1Id,
      updatedBy: reviewerId,
      createdAt: new Date('2024-01-15').toISOString(),
      updatedAt: new Date('2024-01-25').toISOString(),
    },
  ];

  const trainingRecords = [
    {
      _id: new ObjectId().toString(),
      recordNo: 'TRN202401001',
      petId: pet1Id,
      petNo: 'PET202401001',
      petName: '大黄',
      trainerId: trainer1Id,
      trainerName: '李训练',
      trainingDate: new Date('2024-01-15').toISOString(),
      trainingType: 'basic_commands',
      trainingContent: '坐下、握手、趴下、等待基础指令训练',
      duration: 60,
      performance: 'excellent',
      notes: '学习能力强，注意力集中',
      beforeBehavior: '对指令反应一般，有时不听指挥',
      afterBehavior: '能快速响应基础指令，服从性明显提升',
      nextPlan: '进阶训练：衔取、召回',
      createdBy: trainer1Id,
      updatedBy: trainer1Id,
      createdAt: new Date('2024-01-15').toISOString(),
      updatedAt: new Date('2024-01-15').toISOString(),
    },
    {
      _id: new ObjectId().toString(),
      recordNo: 'TRN202401002',
      petId: pet1Id,
      petNo: 'PET202401001',
      petName: '大黄',
      trainerId: trainer1Id,
      trainerName: '李训练',
      trainingDate: new Date('2024-01-22').toISOString(),
      trainingType: 'socialization',
      trainingContent: '社会化训练，接触陌生人和其他狗狗',
      duration: 90,
      performance: 'good',
      notes: '对陌生人友好，与其他狗狗相处融洽',
      beforeBehavior: '对陌生狗狗有时会吠叫',
      afterBehavior: '能友好地与其他狗狗互动',
      nextPlan: '继续社会化，增加复杂环境适应',
      createdBy: trainer1Id,
      updatedBy: trainer1Id,
      createdAt: new Date('2024-01-22').toISOString(),
      updatedAt: new Date('2024-01-22').toISOString(),
    },
    {
      _id: new ObjectId().toString(),
      recordNo: 'TRN202401003',
      petId: pet2Id,
      petNo: 'PET202401002',
      petName: '小黑',
      trainerId: trainer1Id,
      trainerName: '李训练',
      trainingDate: new Date('2024-02-05').toISOString(),
      trainingType: 'obedience',
      trainingContent: '服从性训练，随行、停止、召回',
      duration: 75,
      performance: 'good',
      notes: '精力充沛，需要更多运动',
      beforeBehavior: '外出时容易兴奋，拉拽牵引绳',
      afterBehavior: '随行表现改善，能保持在主人身边',
      nextPlan: '加强召回训练，增加干扰环境练习',
      createdBy: trainer1Id,
      updatedBy: trainer1Id,
      createdAt: new Date('2024-02-05').toISOString(),
      updatedAt: new Date('2024-02-05').toISOString(),
    },
    {
      _id: new ObjectId().toString(),
      recordNo: 'TRN202401004',
      petId: pet3Id,
      petNo: 'PET202401003',
      petName: '花花',
      trainerId: trainer2Id,
      trainerName: '王教练',
      trainingDate: new Date('2024-01-20').toISOString(),
      trainingType: 'behavior_correction',
      trainingContent: '行为纠正，改善对陌生人的攻击性',
      duration: 45,
      performance: 'average',
      notes: '需要更多时间和耐心',
      beforeBehavior: '对陌生人哈气、炸毛',
      afterBehavior: '在有食物诱导下能接受陌生人靠近',
      nextPlan: '继续脱敏训练，逐步增加接触时间',
      createdBy: trainer2Id,
      updatedBy: trainer2Id,
      createdAt: new Date('2024-01-20').toISOString(),
      updatedAt: new Date('2024-01-20').toISOString(),
    },
    {
      _id: new ObjectId().toString(),
      recordNo: 'TRN202401005',
      petId: pet4Id,
      petNo: 'PET202401004',
      petName: '豆豆',
      trainerId: trainer2Id,
      trainerName: '王教练',
      trainingDate: new Date('2024-03-08').toISOString(),
      trainingType: 'other',
      trainingContent: '减肥计划：运动训练加饮食控制',
      duration: 30,
      performance: 'good',
      notes: '配合度不错，需要坚持',
      beforeBehavior: '不爱动，容易累',
      afterBehavior: '能完成基本的逗猫棒互动15分钟',
      nextPlan: '逐渐增加运动时间，配合减肥粮',
      createdBy: trainer2Id,
      updatedBy: trainer2Id,
      createdAt: new Date('2024-03-08').toISOString(),
      updatedAt: new Date('2024-03-08').toISOString(),
    },
  ];

  const visitRecords = [
    {
      _id: new ObjectId().toString(),
      recordNo: 'VST202401001',
      applicationId: app1Id,
      applicationNo: 'ADP202401001',
      petId: pet1Id,
      petName: '大黄',
      applicantName: '陈小明',
      visitType: 'first_week',
      visitDate: new Date('2024-02-25').toISOString(),
      visitMethod: 'home_visit',
      visitorId: trainer1Id,
      visitorName: '李训练',
      petCondition: {
        health: 'excellent',
        mood: 'excellent',
        weight: 29.0,
        diet: '饮食规律，食欲好',
        exercise: '每天遛狗两次，每次约1小时',
      },
      livingEnvironment: '小区环境好，有电梯，家里空间充足',
      problems: '无明显问题',
      suggestions: '继续保持，定期体检',
      overallStatus: 'excellent',
      followUpRequired: false,
      followUpDate: null,
      createdBy: trainer1Id,
      createdAt: new Date('2024-02-25').toISOString(),
      updatedAt: new Date('2024-02-25').toISOString(),
    },
    {
      _id: new ObjectId().toString(),
      recordNo: 'VST202401002',
      applicationId: app1Id,
      applicationNo: 'ADP202401001',
      petId: pet1Id,
      petName: '大黄',
      applicantName: '陈小明',
      visitType: 'first_month',
      visitDate: new Date('2024-03-20').toISOString(),
      visitMethod: 'video_call',
      visitorId: trainer1Id,
      visitorName: '李训练',
      petCondition: {
        health: 'good',
        mood: 'good',
        weight: 29.5,
        diet: '正常',
        exercise: '每天户外活动2小时左右',
      },
      livingEnvironment: '适应良好',
      problems: '偶尔会翻垃圾桶',
      suggestions: '建议加强行为训练，垃圾桶加盖',
      overallStatus: 'good',
      followUpRequired: true,
      followUpDate: new Date('2024-04-20').toISOString(),
      createdBy: trainer1Id,
      createdAt: new Date('2024-03-20').toISOString(),
      updatedAt: new Date('2024-03-20').toISOString(),
    },
    {
      _id: new ObjectId().toString(),
      recordNo: 'VST202401003',
      applicationId: app3Id,
      applicationNo: 'ADP202401003',
      petId: pet3Id,
      petName: '花花',
      applicantName: '张小华',
      visitType: 'first_week',
      visitDate: new Date('2024-03-15').toISOString(),
      visitMethod: 'home_visit',
      visitorId: trainer2Id,
      visitorName: '王教练',
      petCondition: {
        health: 'good',
        mood: 'average',
        weight: 4.0,
        diet: '正常进食',
        exercise: '比较安静，大部分时间在睡觉',
      },
      livingEnvironment: '环境整洁，有猫爬架和猫砂盆',
      problems: '新环境适应中，有点胆小',
      suggestions: '给猫咪一些时间适应，不要强行互动',
      overallStatus: 'good',
      followUpRequired: true,
      followUpDate: new Date('2024-03-25').toISOString(),
      createdBy: trainer2Id,
      createdAt: new Date('2024-03-15').toISOString(),
      updatedAt: new Date('2024-03-15').toISOString(),
    },
  ];

  const safetyReminders = [
    {
      _id: new ObjectId().toString(),
      title: '夏季宠物防暑小贴士',
      content: '夏季气温高，宠物容易中暑。请确保宠物有充足的饮水，避免在中午高温时段外出遛狗。切勿将宠物单独留在车内，即使短时间也可能造成严重后果。如出现呼吸急促、口吐白沫等症状，请立即就医。',
      category: 'health',
      level: 'warning',
      targetAudience: 'all',
      isActive: true,
      isPinned: true,
      sortOrder: 1,
      createdBy: adminId,
      updatedBy: adminId,
      createdAt: new Date('2024-01-01').toISOString(),
      updatedAt: new Date('2024-01-01').toISOString(),
    },
    {
      _id: new ObjectId().toString(),
      title: '新领养宠物适应指南',
      content: '新领养的宠物需要时间适应新环境。建议准备好舒适的窝、食盆、水盆和玩具。开始几天给宠物足够的空间，不要强行抱撸。保持饮食规律，逐渐建立信任关系。如有任何健康问题，请及时联系兽医。',
      category: 'safety',
      level: 'info',
      targetAudience: 'adopter',
      isActive: true,
      isPinned: true,
      sortOrder: 2,
      createdBy: adminId,
      updatedBy: adminId,
      createdAt: new Date('2024-01-02').toISOString(),
      updatedAt: new Date('2024-01-02').toISOString(),
    },
    {
      _id: new ObjectId().toString(),
      title: '这些食物宠物不能吃',
      content: '巧克力、葡萄、葡萄干、洋葱、大蒜、牛油果、酒精、咖啡因等食物对宠物有毒性，可能导致严重健康问题甚至危及生命。请将这些食物放在宠物够不到的地方。如不慎误食，请立即就医。',
      category: 'feeding',
      level: 'danger',
      targetAudience: 'all',
      isActive: true,
      isPinned: false,
      sortOrder: 3,
      createdBy: adminId,
      updatedBy: adminId,
      createdAt: new Date('2024-01-03').toISOString(),
      updatedAt: new Date('2024-01-03').toISOString(),
    },
    {
      _id: new ObjectId().toString(),
      title: '定期疫苗和驱虫的重要性',
      content: '定期接种疫苗和驱虫是保障宠物健康的基础。犬只需接种狂犬疫苗、犬瘟热、细小病毒等疫苗。猫咪需接种狂犬疫苗、猫瘟等疫苗。体内外驱虫建议每月一次。请建立完整的健康档案，按时接种。',
      category: 'health',
      level: 'warning',
      targetAudience: 'all',
      isActive: true,
      isPinned: false,
      sortOrder: 4,
      createdBy: adminId,
      updatedBy: adminId,
      createdAt: new Date('2024-01-04').toISOString(),
      updatedAt: new Date('2024-01-04').toISOString(),
    },
    {
      _id: new ObjectId().toString(),
      title: '领养后回访须知',
      content: '领养成功后，我们会进行定期回访，包括首周回访、首月回访和季度回访。回访方式包括上门家访、视频通话和电话回访。请配合回访工作，如实反馈宠物状况。如有任何问题，可随时联系对接的训练师。',
      category: 'other',
      level: 'info',
      targetAudience: 'adopter',
      isActive: true,
      isPinned: false,
      sortOrder: 5,
      createdBy: adminId,
      updatedBy: adminId,
      createdAt: new Date('2024-01-05').toISOString(),
      updatedAt: new Date('2024-01-05').toISOString(),
    },
  ];

  const flowRecords = [
    {
      _id: new ObjectId().toString(),
      recordType: 'pet_profile',
      relatedId: pet1Id,
      relatedNo: 'PET202401001',
      action: 'create',
      actionLabel: '创建档案',
      beforeData: null,
      afterData: {
        name: '大黄',
        species: 'dog',
        breed: '金毛寻回犬',
        status: 'pending',
      },
      changedFields: [],
      description: '创建宠物档案：大黄',
      operatorId: adminId,
      operatorName: '系统管理员',
      operatorRole: 'admin',
      remark: '',
      createdAt: new Date('2024-01-05T10:00:00Z').toISOString(),
      updatedAt: new Date('2024-01-05T10:00:00Z').toISOString(),
    },
    {
      _id: new ObjectId().toString(),
      recordType: 'pet_profile',
      relatedId: pet1Id,
      relatedNo: 'PET202401001',
      action: 'status_change',
      actionLabel: '状态变更',
      beforeData: { status: 'pending' },
      afterData: { status: 'fostering' },
      changedFields: ['status'],
      description: '宠物状态从待寄养变更为寄养中',
      operatorId: trainer1Id,
      operatorName: '李训练',
      operatorRole: 'trainer',
      remark: '开始寄养，进入训练期',
      createdAt: new Date('2024-01-10T09:00:00Z').toISOString(),
      updatedAt: new Date('2024-01-10T09:00:00Z').toISOString(),
    },
    {
      _id: new ObjectId().toString(),
      recordType: 'adoption_application',
      relatedId: app1Id,
      relatedNo: 'ADP202401001',
      action: 'create',
      actionLabel: '创建申请',
      beforeData: null,
      afterData: {
        applicantName: '陈小明',
        petName: '大黄',
        status: 'draft',
      },
      changedFields: [],
      description: '创建领养申请：陈小明 - 大黄',
      operatorId: trainer1Id,
      operatorName: '李训练',
      operatorRole: 'trainer',
      remark: '',
      createdAt: new Date('2024-02-05T14:00:00Z').toISOString(),
      updatedAt: new Date('2024-02-05T14:00:00Z').toISOString(),
    },
    {
      _id: new ObjectId().toString(),
      recordType: 'adoption_application',
      relatedId: app1Id,
      relatedNo: 'ADP202401001',
      action: 'update',
      actionLabel: '更新申请',
      beforeData: {
        applicantPhone: '13912345678',
        hasPetExperience: false,
      },
      afterData: {
        applicantPhone: '13912345678',
        hasPetExperience: true,
      },
      changedFields: ['hasPetExperience', 'currentPets'],
      description: '更新领养申请资料：补充养宠经验',
      operatorId: trainer1Id,
      operatorName: '李训练',
      operatorRole: 'trainer',
      remark: '',
      createdAt: new Date('2024-02-08T10:30:00Z').toISOString(),
      updatedAt: new Date('2024-02-08T10:30:00Z').toISOString(),
    },
    {
      _id: new ObjectId().toString(),
      recordType: 'adoption_application',
      relatedId: app1Id,
      relatedNo: 'ADP202401001',
      action: 'submit',
      actionLabel: '提交审核',
      beforeData: { status: 'draft' },
      afterData: { status: 'submitted' },
      changedFields: ['status', 'submittedAt'],
      description: '提交领养申请，等待审核',
      operatorId: trainer1Id,
      operatorName: '李训练',
      operatorRole: 'trainer',
      remark: '资料完整，已提交审核',
      createdAt: new Date('2024-02-10T16:00:00Z').toISOString(),
      updatedAt: new Date('2024-02-10T16:00:00Z').toISOString(),
    },
    {
      _id: new ObjectId().toString(),
      recordType: 'adoption_application',
      relatedId: app1Id,
      relatedNo: 'ADP202401001',
      action: 'review',
      actionLabel: '审核通过',
      beforeData: {
        status: 'submitted',
        reviewComments: '',
        reviewerName: '',
      },
      afterData: {
        status: 'approved',
        reviewComments: '申请人条件良好，有养宠经验，家庭环境适合养狗',
        reviewerName: '张审核',
      },
      changedFields: ['status', 'reviewComments', 'reviewerId', 'reviewerName', 'reviewedAt'],
      description: '审核结果：审核通过',
      operatorId: reviewerId,
      operatorName: '张审核',
      operatorRole: 'reviewer',
      remark: '',
      createdAt: new Date('2024-02-15T11:00:00Z').toISOString(),
      updatedAt: new Date('2024-02-15T11:00:00Z').toISOString(),
    },
    {
      _id: new ObjectId().toString(),
      recordType: 'training_record',
      relatedId: trainingRecords[0]._id,
      relatedNo: 'TRN202401001',
      action: 'create',
      actionLabel: '创建记录',
      beforeData: null,
      afterData: {
        petName: '大黄',
        trainingType: 'basic_commands',
        performance: 'excellent',
      },
      changedFields: [],
      description: '创建训练记录：大黄 - 基础指令',
      operatorId: trainer1Id,
      operatorName: '李训练',
      operatorRole: 'trainer',
      remark: '',
      createdAt: new Date('2024-01-15T15:00:00Z').toISOString(),
      updatedAt: new Date('2024-01-15T15:00:00Z').toISOString(),
    },
    {
      _id: new ObjectId().toString(),
      recordType: 'visit_record',
      relatedId: visitRecords[0]._id,
      relatedNo: 'VST202401001',
      action: 'create',
      actionLabel: '创建回访',
      beforeData: null,
      afterData: {
        applicantName: '陈小明',
        visitType: 'first_week',
        overallStatus: 'excellent',
      },
      changedFields: [],
      description: '创建回访记录：陈小明 - 首周回访',
      operatorId: trainer1Id,
      operatorName: '李训练',
      operatorRole: 'trainer',
      remark: '',
      createdAt: new Date('2024-02-25T14:00:00Z').toISOString(),
      updatedAt: new Date('2024-02-25T14:00:00Z').toISOString(),
    },
  ];

  return {
    users,
    pets,
    adoptionApplications,
    trainingRecords,
    visitRecords,
    safetyReminders,
    flowRecords,
  };
};

module.exports = { generateSeedData };
