/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const TargetsLazyRouteImport = createFileRoute('/targets')()
const OfflineLazyRouteImport = createFileRoute('/offline')()
const AlertsLazyRouteImport = createFileRoute('/alerts')()
const IndexLazyRouteImport = createFileRoute('/')()
const TargetsIdLazyRouteImport = createFileRoute('/targets/$id')()
const ConfigZonesLazyRouteImport = createFileRoute('/config/zones')()
const ConfigSubsidiesLazyRouteImport = createFileRoute('/config/subsidies')()
const ConfigMetersLazyRouteImport = createFileRoute('/config/meters')()
const ConfigAuditLazyRouteImport = createFileRoute('/config/audit')()

const TargetsLazyRoute = TargetsLazyRouteImport.update({
  id: '/targets',
  path: '/targets',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/targets.lazy').then((d) => d.Route))
const OfflineLazyRoute = OfflineLazyRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/offline.lazy').then((d) => d.Route))
const AlertsLazyRoute = AlertsLazyRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/alerts.lazy').then((d) => d.Route))
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const TargetsIdLazyRoute = TargetsIdLazyRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TargetsLazyRoute,
} as any).lazy(() => import('./routes/targets.$id.lazy').then((d) => d.Route))
const ConfigZonesLazyRoute = ConfigZonesLazyRouteImport.update({
  id: '/config/zones',
  path: '/config/zones',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/config/zones.lazy').then((d) => d.Route))
const ConfigSubsidiesLazyRoute = ConfigSubsidiesLazyRouteImport.update({
  id: '/config/subsidies',
  path: '/config/subsidies',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/config/subsidies.lazy').then((d) => d.Route),
)
const ConfigMetersLazyRoute = ConfigMetersLazyRouteImport.update({
  id: '/config/meters',
  path: '/config/meters',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/config/meters.lazy').then((d) => d.Route))
const ConfigAuditLazyRoute = ConfigAuditLazyRouteImport.update({
  id: '/config/audit',
  path: '/config/audit',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/config/audit.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/alerts': typeof AlertsLazyRoute
  '/offline': typeof OfflineLazyRoute
  '/targets': typeof TargetsLazyRouteWithChildren
  '/config/audit': typeof ConfigAuditLazyRoute
  '/config/meters': typeof ConfigMetersLazyRoute
  '/config/subsidies': typeof ConfigSubsidiesLazyRoute
  '/config/zones': typeof ConfigZonesLazyRoute
  '/targets/$id': typeof TargetsIdLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/alerts': typeof AlertsLazyRoute
  '/offline': typeof OfflineLazyRoute
  '/targets': typeof TargetsLazyRouteWithChildren
  '/config/audit': typeof ConfigAuditLazyRoute
  '/config/meters': typeof ConfigMetersLazyRoute
  '/config/subsidies': typeof ConfigSubsidiesLazyRoute
  '/config/zones': typeof ConfigZonesLazyRoute
  '/targets/$id': typeof TargetsIdLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/alerts': typeof AlertsLazyRoute
  '/offline': typeof OfflineLazyRoute
  '/targets': typeof TargetsLazyRouteWithChildren
  '/config/audit': typeof ConfigAuditLazyRoute
  '/config/meters': typeof ConfigMetersLazyRoute
  '/config/subsidies': typeof ConfigSubsidiesLazyRoute
  '/config/zones': typeof ConfigZonesLazyRoute
  '/targets/$id': typeof TargetsIdLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/offline'
    | '/targets'
    | '/config/audit'
    | '/config/meters'
    | '/config/subsidies'
    | '/config/zones'
    | '/targets/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/offline'
    | '/targets'
    | '/config/audit'
    | '/config/meters'
    | '/config/subsidies'
    | '/config/zones'
    | '/targets/$id'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/offline'
    | '/targets'
    | '/config/audit'
    | '/config/meters'
    | '/config/subsidies'
    | '/config/zones'
    | '/targets/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AlertsLazyRoute: typeof AlertsLazyRoute
  OfflineLazyRoute: typeof OfflineLazyRoute
  TargetsLazyRoute: typeof TargetsLazyRouteWithChildren
  ConfigAuditLazyRoute: typeof ConfigAuditLazyRoute
  ConfigMetersLazyRoute: typeof ConfigMetersLazyRoute
  ConfigSubsidiesLazyRoute: typeof ConfigSubsidiesLazyRoute
  ConfigZonesLazyRoute: typeof ConfigZonesLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/targets': {
      id: '/targets'
      path: '/targets'
      fullPath: '/targets'
      preLoaderRoute: typeof TargetsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/targets/$id': {
      id: '/targets/$id'
      path: '/$id'
      fullPath: '/targets/$id'
      preLoaderRoute: typeof TargetsIdLazyRouteImport
      parentRoute: typeof TargetsLazyRoute
    }
    '/config/zones': {
      id: '/config/zones'
      path: '/config/zones'
      fullPath: '/config/zones'
      preLoaderRoute: typeof ConfigZonesLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/subsidies': {
      id: '/config/subsidies'
      path: '/config/subsidies'
      fullPath: '/config/subsidies'
      preLoaderRoute: typeof ConfigSubsidiesLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/meters': {
      id: '/config/meters'
      path: '/config/meters'
      fullPath: '/config/meters'
      preLoaderRoute: typeof ConfigMetersLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/audit': {
      id: '/config/audit'
      path: '/config/audit'
      fullPath: '/config/audit'
      preLoaderRoute: typeof ConfigAuditLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TargetsLazyRouteChildren {
  TargetsIdLazyRoute: typeof TargetsIdLazyRoute
}

const TargetsLazyRouteChildren: TargetsLazyRouteChildren = {
  TargetsIdLazyRoute: TargetsIdLazyRoute,
}

const TargetsLazyRouteWithChildren = TargetsLazyRoute._addFileChildren(
  TargetsLazyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AlertsLazyRoute: AlertsLazyRoute,
  OfflineLazyRoute: OfflineLazyRoute,
  TargetsLazyRoute: TargetsLazyRouteWithChildren,
  ConfigAuditLazyRoute: ConfigAuditLazyRoute,
  ConfigMetersLazyRoute: ConfigMetersLazyRoute,
  ConfigSubsidiesLazyRoute: ConfigSubsidiesLazyRoute,
  ConfigZonesLazyRoute: ConfigZonesLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
