# Generated by Django 5.2.15 on 2026-06-21 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='年份')),
                ('month', models.PositiveIntegerField(verbose_name='月份')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='使用数量')),
                ('actual_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='实际金额')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='使用部门')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '月度用量',
                'verbose_name_plural': '月度用量',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='SpecificationAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='specification_attachments/%Y/%m/', verbose_name='附件文件')),
                ('file_name', models.CharField(max_length=255, verbose_name='文件名')),
                ('file_type', models.CharField(blank=True, max_length=50, verbose_name='文件类型')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '规格附件',
                'verbose_name_plural': '规格附件',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsumableCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='品类名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='品类编码')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='consumables.consumablecategory', verbose_name='上级品类')),
            ],
            options={
                'verbose_name': '耗材品类',
                'verbose_name_plural': '耗材品类',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ConsumableSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='耗材名称')),
                ('specification', models.CharField(max_length=200, verbose_name='规格型号')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='品牌')),
                ('unit', models.CharField(choices=[('box', '盒'), ('pack', '包'), ('piece', '个'), ('roll', '卷'), ('ream', '令'), ('kg', '千克'), ('liter', '升'), ('set', '套')], default='box', max_length=20, verbose_name='单位')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='单价')),
                ('status', models.CharField(choices=[('active', '在用'), ('inactive', '停用'), ('obsolete', '淘汰')], default='active', max_length=20, verbose_name='状态')),
                ('description', models.TextField(blank=True, verbose_name='备注说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specifications', to='consumables.consumablecategory', verbose_name='品类')),
            ],
            options={
                'verbose_name': '耗材规格',
                'verbose_name_plural': '耗材规格',
                'ordering': ['-created_at'],
            },
        ),
    ]
