# Generated by Django 5.2.15 on 2026-06-21 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consumables', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consumablespecification',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_specifications', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='monthlyusage',
            name='recorded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_usages', to=settings.AUTH_USER_MODEL, verbose_name='登记人'),
        ),
        migrations.AddField(
            model_name='monthlyusage',
            name='specification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_usages', to='consumables.consumablespecification', verbose_name='耗材规格'),
        ),
        migrations.AddField(
            model_name='specificationattachment',
            name='specification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='consumables.consumablespecification', verbose_name='耗材规格'),
        ),
        migrations.AddField(
            model_name='specificationattachment',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='上传人'),
        ),
        migrations.AlterUniqueTogether(
            name='consumablespecification',
            unique_together={('category', 'name', 'specification')},
        ),
        migrations.AlterUniqueTogether(
            name='monthlyusage',
            unique_together={('specification', 'year', 'month', 'department')},
        ),
    ]
