import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Product from '#models/product'

export default class ProductSeeder extends BaseSeeder {
  public async run() {
    await Product.createMany([
      {
        name: 'OPI指甲油-红色系列',
        sku: 'OPI-RED-001',
        category: '指甲油',
        brand: 'OPI',
        description: 'OPI经典红色指甲油',
        unit: '瓶',
        costPrice: 35,
        retailPrice: 68,
        currentStock: 50,
        safetyStock: 10,
        maxStock: 100,
        status: 'active',
      },
      {
        name: '光疗胶-透明',
        sku: 'GEL-CLR-001',
        category: '光疗胶',
        brand: 'CND',
        description: 'CND透明光疗胶',
        unit: '瓶',
        costPrice: 45,
        retailPrice: 88,
        currentStock: 30,
        safetyStock: 8,
        maxStock: 60,
        status: 'active',
      },
      {
        name: '甲片-中号',
        sku: 'TIP-M-001',
        category: '甲片',
        brand: '通用',
        description: '中号美甲甲片100片装',
        unit: '盒',
        costPrice: 12,
        retailPrice: 25,
        currentStock: 5,
        safetyStock: 10,
        maxStock: 50,
        status: 'active',
      },
      {
        name: '卸甲水',
        sku: 'REM-001',
        category: '卸甲产品',
        brand: 'Zoya',
        description: '温和卸甲水',
        unit: '瓶',
        costPrice: 20,
        retailPrice: 38,
        currentStock: 25,
        safetyStock: 5,
        maxStock: 40,
        status: 'active',
      },
      {
        name: '底胶',
        sku: 'BASE-001',
        category: '底胶',
        brand: 'CND',
        description: 'CND底胶',
        unit: '瓶',
        costPrice: 40,
        retailPrice: 78,
        currentStock: 3,
        safetyStock: 8,
        maxStock: 30,
        status: 'active',
      },
      {
        name: '封层胶',
        sku: 'TOP-001',
        category: '封层',
        brand: 'CND',
        description: 'CND免洗封层',
        unit: '瓶',
        costPrice: 42,
        retailPrice: 82,
        currentStock: 15,
        safetyStock: 5,
        maxStock: 30,
        status: 'active',
      },
    ])
  }
}
