# Generated by Django 4.2.7 on 2026-06-05 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_no', models.CharField(max_length=50, unique=True, verbose_name='预约号')),
                ('queue_number', models.IntegerField(blank=True, null=True, verbose_name='排队序号')),
                ('reason', models.TextField(verbose_name='预约原因')),
                ('original_reason', models.TextField(blank=True, verbose_name='原预约原因(改期保留)')),
                ('status', models.CharField(choices=[('BOOKED', '已预约'), ('CHECKED_IN', '已签到'), ('IN_PROGRESS', '就诊中'), ('COMPLETED', '已完成'), ('CANCELLED', '已取消'), ('NO_SHOW', '爽约'), ('RESCHEDULED', '已改期')], default='BOOKED', max_length=20, verbose_name='状态')),
                ('payment_status', models.CharField(choices=[('UNPAID', '未缴费'), ('PAID', '已缴费'), ('REFUNDED', '已退款')], default='UNPAID', max_length=20, verbose_name='缴费状态')),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='费用')),
                ('reschedule_note', models.TextField(blank=True, verbose_name='改期备注')),
                ('checked_in_at', models.DateTimeField(blank=True, null=True, verbose_name='签到时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='取消时间')),
                ('reminder_sent', models.BooleanField(default=False, verbose_name='提醒已发送')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '预约记录',
                'verbose_name_plural': '预约记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FollowUpPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='计划标题')),
                ('description', models.TextField(blank=True, verbose_name='计划描述')),
                ('total_visits', models.IntegerField(default=1, verbose_name='总复诊次数')),
                ('interval_days', models.IntegerField(default=30, verbose_name='复诊间隔(天)')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('next_appointment_date', models.DateField(blank=True, null=True, verbose_name='下次复诊日期')),
                ('status', models.CharField(choices=[('ACTIVE', '进行中'), ('COMPLETED', '已完成'), ('CANCELLED', '已取消')], default='ACTIVE', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '复诊计划',
                'verbose_name_plural': '复诊计划',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicationReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=200, verbose_name='药品名称')),
                ('dosage', models.CharField(max_length=100, verbose_name='剂量')),
                ('frequency', models.CharField(choices=[('QD', '每日一次'), ('BID', '每日两次'), ('TID', '每日三次'), ('QID', '每日四次'), ('AC', '饭前'), ('PC', '饭后'), ('HS', '睡前'), ('PRN', '必要时')], max_length=20, verbose_name='服用频率')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '用药提醒',
                'verbose_name_plural': '用药提醒',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RescheduleReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('DOCTOR_ABSENT', '医生停诊'), ('PATIENT_REQUEST', '患者主动申请'), ('MEDICINE_SHORTAGE', '药品缺货'), ('OTHER', '其他原因')], max_length=30, verbose_name='改期分类')),
                ('name', models.CharField(max_length=100, verbose_name='改期原因')),
                ('description', models.TextField(blank=True, verbose_name='详细说明')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '改期原因',
                'verbose_name_plural': '改期原因',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WaitingQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_date', models.DateField(verbose_name='日期')),
                ('queue_number', models.IntegerField(verbose_name='排队号')),
                ('status', models.CharField(choices=[('WAITING', '等待中'), ('CALLED', '已叫号'), ('IN_PROGRESS', '就诊中'), ('COMPLETED', '已完成'), ('LEFT', '已离开')], default='WAITING', max_length=20, verbose_name='状态')),
                ('called_at', models.DateTimeField(blank=True, null=True, verbose_name='叫号时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('estimated_wait_time', models.IntegerField(blank=True, null=True, verbose_name='预计等待时间(分钟)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entry', to='appointments.appointment', verbose_name='预约记录')),
            ],
            options={
                'verbose_name': '候诊队列',
                'verbose_name_plural': '候诊队列',
                'ordering': ['queue_date', 'queue_number'],
            },
        ),
    ]
