# Generated by Django 4.2.7 on 2026-06-05 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('appointments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitingqueue',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_queue', to='doctors.doctorprofile', verbose_name='医生'),
        ),
        migrations.AddField(
            model_name='medicationreminder',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medication_reminders', to='appointments.appointment', verbose_name='关联预约'),
        ),
        migrations.AddField(
            model_name='medicationreminder',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reminders', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='medicationreminder',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_reminders', to='patients.patientprofile', verbose_name='患者'),
        ),
        migrations.AddField(
            model_name='followupplan',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_followup_plans', to=settings.AUTH_USER_MODEL, verbose_name='创建人(护士)'),
        ),
        migrations.AddField(
            model_name='followupplan',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='followup_plans', to='doctors.doctorprofile', verbose_name='负责医生'),
        ),
        migrations.AddField(
            model_name='followupplan',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followup_plans', to='patients.patientprofile', verbose_name='患者'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='daily_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='doctors.dailyslot', verbose_name='号源'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='doctors.doctorprofile', verbose_name='医生'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='followup_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='appointments.followupplan', verbose_name='关联复诊计划'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='original_appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescheduled_to', to='appointments.appointment', verbose_name='原预约记录'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patientprofile', verbose_name='患者'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reschedule_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='appointments.reschedulereason', verbose_name='改期原因'),
        ),
        migrations.AlterUniqueTogether(
            name='waitingqueue',
            unique_together={('doctor', 'queue_date', 'queue_number')},
        ),
    ]
