# Generated by Django 4.2.30 on 2026-06-05 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaultTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=200, verbose_name='故障标题')),
                ('description', models.TextField(verbose_name='故障描述')),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('critical', '紧急')], default='medium', max_length=20, verbose_name='优先级')),
                ('status', models.CharField(choices=[('open', '待处理'), ('in_progress', '处理中'), ('waiting_parts', '等待配件'), ('resolved', '已解决'), ('closed', '已关闭')], default='open', max_length=20, verbose_name='状态')),
                ('fault_type', models.CharField(blank=True, max_length=100, verbose_name='故障类型')),
                ('resolution', models.TextField(blank=True, verbose_name='解决方案')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='解决时间')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='预估费用')),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='实际费用')),
                ('assignee', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['technician', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_faults', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fault_tickets', to='equipment.equipment', verbose_name='设备')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_faults', to=settings.AUTH_USER_MODEL, verbose_name='上报人')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_faults', to=settings.AUTH_USER_MODEL, verbose_name='解决人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '故障单',
                'verbose_name_plural': '故障单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FaultComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('is_internal', models.BooleanField(default=False, verbose_name='内部评论')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='maintenance.faultticket', verbose_name='故障单')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fault_comments', to=settings.AUTH_USER_MODEL, verbose_name='评论人')),
            ],
            options={
                'verbose_name': '故障评论',
                'verbose_name_plural': '故障评论',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FaultAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='fault_attachments/', verbose_name='附件')),
                ('file_name', models.CharField(max_length=255, verbose_name='文件名')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='maintenance.faultticket', verbose_name='故障单')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'verbose_name': '故障附件',
                'verbose_name_plural': '故障附件',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=200, verbose_name='维护标题')),
                ('description', models.TextField(blank=True, verbose_name='维护描述')),
                ('scheduled_date', models.DateField(verbose_name='计划日期')),
                ('performed_date', models.DateField(blank=True, null=True, verbose_name='实际日期')),
                ('is_completed', models.BooleanField(default=False, verbose_name='已完成')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_schedules', to='equipment.equipment', verbose_name='设备')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_maintenance', to=settings.AUTH_USER_MODEL, verbose_name='执行人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '维护计划',
                'verbose_name_plural': '维护计划',
                'ordering': ['scheduled_date'],
                'indexes': [models.Index(fields=['equipment', 'is_completed'], name='maintenance_equipme_4490f6_idx'), models.Index(fields=['scheduled_date'], name='maintenance_schedul_003ebc_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='faultticket',
            index=models.Index(fields=['equipment', 'status'], name='maintenance_equipme_8bc5b2_idx'),
        ),
        migrations.AddIndex(
            model_name='faultticket',
            index=models.Index(fields=['reporter', 'status'], name='maintenance_reporte_abff08_idx'),
        ),
        migrations.AddIndex(
            model_name='faultticket',
            index=models.Index(fields=['assignee', 'status'], name='maintenance_assigne_6d31e4_idx'),
        ),
        migrations.AddIndex(
            model_name='faultticket',
            index=models.Index(fields=['status', 'priority'], name='maintenance_status_5a11dd_idx'),
        ),
        migrations.AddIndex(
            model_name='faultticket',
            index=models.Index(fields=['created_at'], name='maintenance_created_b7ea25_idx'),
        ),
    ]
