# Generated by Django 4.2.7 on 2026-06-05 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='班级名称')),
                ('grade', models.CharField(blank=True, default='', max_length=50, verbose_name='年级')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('teacher', models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_groups', to=settings.AUTH_USER_MODEL, verbose_name='主班教师')),
            ],
            options={
                'verbose_name': '班级',
                'verbose_name_plural': '班级',
                'db_table': 'children_classgroup',
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], default='M', max_length=1, verbose_name='性别')),
                ('birth_date', models.DateField(verbose_name='出生日期')),
                ('enrollment_date', models.DateField(blank=True, null=True, verbose_name='入园日期')),
                ('allergies', models.TextField(blank=True, default='', verbose_name='过敏信息')),
                ('medical_notes', models.TextField(blank=True, default='', verbose_name='医疗备注')),
                ('emergency_contact', models.CharField(blank=True, default='', max_length=50, verbose_name='紧急联系人')),
                ('emergency_phone', models.CharField(blank=True, default='', max_length=20, verbose_name='紧急联系电话')),
                ('is_active', models.BooleanField(default=True, verbose_name='在园')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('class_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='children.classgroup', verbose_name='所属班级')),
            ],
            options={
                'verbose_name': '儿童',
                'verbose_name_plural': '儿童',
                'db_table': 'children_child',
            },
        ),
        migrations.CreateModel(
            name='AuthorizedPickupPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('relation', models.CharField(blank=True, default='', max_length=30, verbose_name='与儿童关系')),
                ('id_number', models.CharField(blank=True, default='', max_length=18, verbose_name='身份证号')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='联系电话')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pickup_persons/', verbose_name='照片')),
                ('is_active', models.BooleanField(default=True, verbose_name='有效')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='添加人')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorized_pickups', to='children.child', verbose_name='儿童')),
            ],
            options={
                'verbose_name': '授权接送人',
                'verbose_name_plural': '授权接送人',
                'db_table': 'children_authorizedpickupperson',
            },
        ),
        migrations.CreateModel(
            name='ParentChildRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('father', '父亲'), ('mother', '母亲'), ('grandfather', '爷爷/外公'), ('grandmother', '奶奶/外婆'), ('other', '其他')], default='mother', max_length=20, verbose_name='关系')),
                ('is_primary', models.BooleanField(default=False, verbose_name='主要联系人')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_relations', to='children.child', verbose_name='儿童')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children_relations', to=settings.AUTH_USER_MODEL, verbose_name='家长')),
            ],
            options={
                'verbose_name': '家长-儿童关系',
                'verbose_name_plural': '家长-儿童关系',
                'db_table': 'children_parentchildrelation',
                'indexes': [models.Index(fields=['parent'], name='idx_pcr_parent'), models.Index(fields=['child'], name='idx_pcr_child')],
                'unique_together': {('parent', 'child')},
            },
        ),
        migrations.AddIndex(
            model_name='classgroup',
            index=models.Index(fields=['teacher'], name='idx_classgroup_teacher'),
        ),
        migrations.AddIndex(
            model_name='child',
            index=models.Index(fields=['class_group', 'is_active'], name='idx_child_class_active'),
        ),
        migrations.AddIndex(
            model_name='child',
            index=models.Index(fields=['name'], name='idx_child_name'),
        ),
        migrations.AddIndex(
            model_name='authorizedpickupperson',
            index=models.Index(fields=['child', 'is_active'], name='idx_pickup_child_active'),
        ),
    ]
