import { z } from "zod";
export const BatchCreateSchema = z.object({
    batchNo: z.string().min(1, "批次号不能为空"),
    sku: z.string().min(1, "SKU不能为空"),
    skuName: z.string().min(1, "SKU名称不能为空"),
    supplier: z.string().min(1, "供应商不能为空"),
    supplierBatchNo: z.string().optional(),
    productionDate: z.string().min(1, "生产日期不能为空"),
    expiryDate: z.string().min(1, "有效期不能为空"),
    quantity: z.number().positive("数量必须大于0"),
    unit: z.string().min(1, "单位不能为空"),
    temperatureZone: z.enum(["FROZEN", "CHILLED", "NORMAL"]),
    storageConditions: z.string().optional(),
    qualityReport: z.string().optional(),
    inboundOrderNo: z.string().optional(),
    operator: z.string().min(1, "操作人不能为空"),
    remark: z.string().optional(),
});
export const ScanInboundSchema = z.object({
    batchNo: z.string().min(1, "批次号不能为空"),
    sku: z.string().min(1, "SKU不能为空"),
    locationCode: z.string().min(1, "库位编码不能为空"),
    quantity: z.number().positive("入库数量必须大于0"),
    operator: z.string().min(1, "操作人不能为空"),
    reason: z.string().min(1, "入库原因不能为空"),
    inboundOrderNo: z.string().optional(),
    remark: z.string().optional(),
});
export const ScanOutboundSchema = z.object({
    batchNo: z.string().min(1, "批次号不能为空"),
    sku: z.string().min(1, "SKU不能为空"),
    locationCode: z.string().min(1, "库位编码不能为空"),
    quantity: z.number().positive("出库数量必须大于0"),
    operator: z.string().min(1, "操作人不能为空"),
    reason: z.string().min(1, "出库原因不能为空"),
    outboundOrderNo: z.string().optional(),
    remark: z.string().optional(),
});
export const TransferCreateSchema = z.object({
    type: z.enum(["ALLOCATION", "PURCHASE", "RETURN", "EMERGENCY"]),
    sku: z.string().min(1, "SKU不能为空"),
    skuName: z.string().min(1, "SKU名称不能为空"),
    batchNo: z.string().optional(),
    quantity: z.number().positive("数量必须大于0"),
    unit: z.string().min(1, "单位不能为空"),
    fromLocation: z.string().min(1, "来源库位不能为空"),
    toLocation: z.string().min(1, "目标库位不能为空"),
    supplier: z.string().optional(),
    plannedDate: z.string().min(1, "计划日期不能为空"),
    expectedDate: z.string().min(1, "预计到货日期不能为空"),
    applicant: z.string().min(1, "申请人不能为空"),
    remark: z.string().optional(),
    relatedSafetyStockId: z.string().optional(),
});
export const ReceiptDiffCreateSchema = z.object({
    inboundOrderNo: z.string().min(1, "入库单号不能为空"),
    batchNo: z.string().min(1, "批次号不能为空"),
    sku: z.string().min(1, "SKU不能为空"),
    skuName: z.string().min(1, "SKU名称不能为空"),
    diffType: z.enum(["QUANTITY", "QUALITY", "DOCUMENT", "OTHER"]),
    expectedQuantity: z.number().nonnegative(),
    actualQuantity: z.number().nonnegative(),
    description: z.string().min(1, "差异描述不能为空"),
    reporter: z.string().min(1, "报告人不能为空"),
    rootCause: z.string().optional(),
    relatedSafetyStockId: z.string().optional(),
    remark: z.string().optional(),
});
export const SafetyStockCreateSchema = z.object({
    sku: z.string().min(1, "SKU不能为空"),
    skuName: z.string().min(1, "SKU名称不能为空"),
    category: z.string().optional(),
    minQuantity: z.number().nonnegative("最小库存量不能为负"),
    maxQuantity: z.number().nonnegative().optional(),
    reorderPoint: z.number().nonnegative("再订货点不能为负"),
    reorderQuantity: z.number().positive("补货数量必须大于0"),
    unit: z.string().min(1, "单位不能为空"),
    supplier: z.string().optional(),
    leadTimeDays: z.number().positive("交期必须大于0天"),
    reviewPeriodDays: z.number().positive("检查周期必须大于0天"),
    responsiblePerson: z.string().min(1, "责任人不能为空"),
    remark: z.string().optional(),
});
export const LocationCreateSchema = z.object({
    code: z.string().min(1, "库位编码不能为空"),
    name: z.string().min(1, "库位名称不能为空"),
    zone: z.string().min(1, "库区不能为空"),
    aisle: z.string().min(1, "通道不能为空"),
    shelf: z.string().min(1, "货架不能为空"),
    layer: z.string().min(1, "层级不能为空"),
    position: z.string().min(1, "位置不能为空"),
    type: z.enum(["STORAGE", "PICKING", "RECEIVING", "SHIPPING", "PROCESSING", "RETURN"]),
    temperatureZone: z.enum(["FROZEN", "CHILLED", "NORMAL"]),
    maxCapacity: z.number().positive("最大容量必须大于0"),
    capacityUnit: z.string().min(1, "容量单位不能为空"),
    description: z.string().optional(),
});
export const StatusChangeSchema = z.object({
    toStatus: z.string().min(1, "目标状态不能为空"),
    reason: z.string().min(1, "状态变更原因不能为空"),
    operator: z.string().min(1, "操作人不能为空"),
});
//# sourceMappingURL=schemas.js.map