# Generated by Django 4.2.7 on 2026-06-05 18:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('member_no', models.CharField(max_length=20, unique=True, verbose_name='会员编号')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('gender', models.CharField(blank=True, choices=[('male', '男'), ('female', '女'), ('other', '其他')], max_length=10, verbose_name='性别')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='手机号')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='地址')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='member_avatars/', verbose_name='头像')),
                ('total_points', models.IntegerField(default=0, verbose_name='累计积分')),
                ('available_points', models.IntegerField(default=0, verbose_name='可用积分')),
                ('status', models.CharField(choices=[('active', '正常'), ('inactive', '停用'), ('blacklist', '黑名单')], default='active', max_length=20, verbose_name='状态')),
                ('register_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='注册时间')),
                ('expire_date', models.DateTimeField(blank=True, null=True, verbose_name='到期时间')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='core.user', verbose_name='创建人')),
            ],
            options={
                'verbose_name': '会员',
                'verbose_name_plural': '会员',
                'db_table': 'member',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PointsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('type', models.CharField(choices=[('earn', '获得积分'), ('consume', '消耗积分'), ('expire', '积分过期'), ('adjust', '人工调整')], max_length=20, verbose_name='类型')),
                ('points', models.IntegerField(verbose_name='积分数量')),
                ('balance_after', models.IntegerField(verbose_name='变更后余额')),
                ('source', models.CharField(blank=True, max_length=200, verbose_name='来源')),
                ('related_id', models.IntegerField(blank=True, null=True, verbose_name='关联ID')),
                ('expire_date', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='core.user', verbose_name='创建人')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_records', to='members.member', verbose_name='会员')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='core.user', verbose_name='更新人')),
            ],
            options={
                'verbose_name': '积分记录',
                'verbose_name_plural': '积分记录',
                'db_table': 'points_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemberLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('name', models.CharField(max_length=100, verbose_name='等级名称')),
                ('level', models.IntegerField(unique=True, verbose_name='等级')),
                ('min_points', models.IntegerField(default=0, verbose_name='最低积分')),
                ('discount', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='折扣率')),
                ('points_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='积分倍率')),
                ('benefits', models.TextField(blank=True, verbose_name='权益说明')),
                ('color', models.CharField(default='#000000', max_length=7, verbose_name='等级颜色')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='core.user', verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='core.user', verbose_name='更新人')),
            ],
            options={
                'verbose_name': '会员等级',
                'verbose_name_plural': '会员等级',
                'db_table': 'member_level',
                'ordering': ['level'],
            },
        ),
        migrations.AddField(
            model_name='member',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='members.memberlevel', verbose_name='会员等级'),
        ),
        migrations.AddField(
            model_name='member',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='core.user', verbose_name='更新人'),
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member', to='core.user', verbose_name='关联用户'),
        ),
        migrations.CreateModel(
            name='ArrivalNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('status', models.CharField(choices=[('pending', '待通知'), ('notified', '已通知'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='通知时间')),
                ('notify_method', models.CharField(default='sms', max_length=50, verbose_name='通知方式')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='books.book', verbose_name='图书')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='core.user', verbose_name='创建人')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='members.member', verbose_name='会员')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='core.user', verbose_name='更新人')),
            ],
            options={
                'verbose_name': '到货通知',
                'verbose_name_plural': '到货通知',
                'db_table': 'arrival_notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['member_no'], name='member_member__cb5c40_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['phone'], name='member_phone_c3a7e4_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['status'], name='member_status_76a97d_idx'),
        ),
    ]
