# Generated by Django 5.0.1 on 2026-06-11 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='规则名称')),
                ('rule_type', models.CharField(choices=[('keyword', '关键词'), ('regex', '正则表达式'), ('ai_detect', 'AI检测')], db_index=True, default='keyword', max_length=20, verbose_name='规则类型')),
                ('pattern', models.TextField(verbose_name='匹配模式')),
                ('risk_level', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('critical', '严重')], db_index=True, default='medium', max_length=20, verbose_name='风险等级')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '风险规则',
                'verbose_name_plural': '风险规则',
                'db_table': 'risk_rules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('risk_level', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('critical', '严重')], db_index=True, default='medium', max_length=20, verbose_name='风险等级')),
                ('risk_category', models.CharField(choices=[('sensitive_word', '敏感词'), ('privacy_leak', '隐私泄露'), ('misinformation', '错误信息'), ('compliance_risk', '合规风险'), ('other', '其他')], db_index=True, default='other', max_length=50, verbose_name='风险分类')),
                ('source', models.CharField(choices=[('ai_flag', 'AI标记'), ('manual', '人工录入'), ('review', '审核发现'), ('import', '批量导入')], db_index=True, default='manual', max_length=50, verbose_name='来源')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('confirmed', '已确认'), ('resolved', '已解决'), ('false_positive', '误报')], db_index=True, default='pending', max_length=20, verbose_name='状态')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('handle_comment', models.TextField(blank=True, verbose_name='处理意见')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_risks', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_samples', to='conversations.conversation', verbose_name='关联会话')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_risks', to=settings.AUTH_USER_MODEL, verbose_name='实际处理人')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_samples', to='conversations.message', verbose_name='关联消息')),
            ],
            options={
                'verbose_name': '风险样本',
                'verbose_name_plural': '风险样本',
                'db_table': 'risk_samples',
                'ordering': ['-created_at'],
            },
        ),
    ]
