# Generated by Django 5.2.15 on 2026-06-21 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('specification', models.CharField(blank=True, max_length=200, verbose_name='规格型号')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='单位')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='数量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='单价(元)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='金额(元)')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=13, max_digits=5, verbose_name='税率(%)')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='税额(元)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '发票明细',
                'verbose_name_plural': '发票明细',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=30, verbose_name='原状态')),
                ('to_status', models.CharField(max_length=30, verbose_name='新状态')),
                ('remark', models.TextField(blank=True, verbose_name='状态变更说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
            ],
            options={
                'verbose_name': '发票状态日志',
                'verbose_name_plural': '发票状态日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='发票号码')),
                ('invoice_code', models.CharField(blank=True, max_length=50, verbose_name='发票代码')),
                ('invoice_type', models.CharField(choices=[('vat_special', '增值税专用发票'), ('vat_general', '增值税普通发票'), ('electronic_special', '电子专用发票'), ('electronic_general', '电子普通发票')], max_length=30, verbose_name='发票类型')),
                ('invoice_date', models.DateField(verbose_name='开票日期')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='价税合计(元)')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='税额(元)')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=13, max_digits=5, verbose_name='税率(%)')),
                ('status', models.CharField(choices=[('draft', '待提交'), ('pending_review', '待审核'), ('reviewed', '已审核'), ('pending_payment', '待付款'), ('paid', '已付款'), ('rejected', '已驳回'), ('cancelled', '已作废')], default='draft', max_length=30, verbose_name='发票状态')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='到期付款日')),
                ('actual_payment_date', models.DateField(blank=True, null=True, verbose_name='实际付款日')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='付款方式')),
                ('invoice_file', models.FileField(blank=True, null=True, upload_to='invoice_files/%Y/%m/', verbose_name='发票文件')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='contracts.frameworkcontract', verbose_name='关联合同')),
            ],
            options={
                'verbose_name': '发票',
                'verbose_name_plural': '发票',
                'ordering': ['-invoice_date'],
            },
        ),
    ]
