export interface ClickHouseConfig {
  host: string
  port: number
  protocol: 'http' | 'https'
  database: string
  username: string
  password?: string
  timeout: number
  useCompression: boolean
}

export const DEFAULT_CLICKHOUSE_CONFIG: ClickHouseConfig = {
  host: import.meta.env.VITE_CLICKHOUSE_HOST || 'localhost',
  port: parseInt(import.meta.env.VITE_CLICKHOUSE_PORT || '8123', 10),
  protocol: (import.meta.env.VITE_CLICKHOUSE_PROTOCOL as 'http' | 'https') || 'http',
  database: import.meta.env.VITE_CLICKHOUSE_DATABASE || 'pharmacy_analytics',
  username: import.meta.env.VITE_CLICKHOUSE_USER || 'default',
  password: import.meta.env.VITE_CLICKHOUSE_PASSWORD,
  timeout: parseInt(import.meta.env.VITE_CLICKHOUSE_TIMEOUT || '30000', 10),
  useCompression: true,
}

export const CLICKHOUSE_TABLES = {
  member_events: 'pharmacy_analytics.member_events',
  orders: 'pharmacy_analytics.orders',
  members: 'pharmacy_analytics.members',
  coupon_redemptions: 'pharmacy_analytics.coupon_redemptions',
  prescriptions: 'pharmacy_analytics.prescriptions',
  store_dim: 'pharmacy_analytics.store_dim',
  medicine_dim: 'pharmacy_analytics.medicine_dim',
  activity_dim: 'pharmacy_analytics.activity_dim',
} as const

export interface QueryBuildOptions {
  storeIds?: string[]
  regionIds?: string[]
  chronicLabels?: string[]
  memberTiers?: string[]
  startDate?: string
  endDate?: string
  sampleThreshold?: number
}

export function buildWhereClause(options: QueryBuildOptions): {
  where: string
  params: Record<string, string | number | string[]>
} {
  const conditions: string[] = []
  const params: Record<string, string | number | string[]> = {}

  if (options.storeIds && options.storeIds.length > 0) {
    conditions.push('store_id IN {storeIds:Array(String)}')
    params.storeIds = options.storeIds
  }

  if (options.regionIds && options.regionIds.length > 0) {
    conditions.push('region_id IN {regionIds:Array(String)}')
    params.regionIds = options.regionIds
  }

  if (options.chronicLabels && options.chronicLabels.length > 0) {
    conditions.push('has(chronic_labels, {chronicLabel:String})')
    params.chronicLabel = options.chronicLabels[0]
  }

  if (options.memberTiers && options.memberTiers.length > 0) {
    conditions.push('member_tier IN {memberTiers:Array(String)}')
    params.memberTiers = options.memberTiers
  }

  if (options.startDate) {
    conditions.push('event_date >= {startDate:Date}')
    params.startDate = options.startDate
  }

  if (options.endDate) {
    conditions.push('event_date <= {endDate:Date}')
    params.endDate = options.endDate
  }

  return {
    where: conditions.length > 0 ? 'WHERE ' + conditions.join(' AND ') : '',
    params,
  }
}

export function buildCohortQuery(options: QueryBuildOptions & {
  cohortPeriod?: string
  retentionPeriods?: number
}): string {
  const { where } = buildWhereClause(options)
  const periods = options.retentionPeriods || 6

  return `
    -- Cohort Retention Analysis Query
    -- Generated by Pharmacy Analytics Platform
    SELECT
      cohort_month,
      retention_month,
      retention_rate,
      sample_size,
      sample_size < 10 AS low_sample
    FROM (
      SELECT
        toStartOfMonth(first_purchase_date) AS cohort_month,
        toUInt32(dateDiff('month', first_purchase_date, purchase_date)) AS retention_month,
        uniqExact(member_id) AS sample_size,
        round(uniqExact(member_id) * 100.0 / first_value(uniqExact(member_id)) OVER (PARTITION BY cohort_month ORDER BY retention_month), 2) AS retention_rate
      FROM (
        SELECT
          member_id,
          order_date AS purchase_date,
          min(order_date) OVER (PARTITION BY member_id) AS first_purchase_date
        FROM ${CLICKHOUSE_TABLES.orders}
        ${where}
      )
      WHERE retention_month <= ${periods}
      GROUP BY cohort_month, retention_month
    )
    ORDER BY cohort_month, retention_month
    SETTINGS max_threads = 4
  `
}

export function buildCoreMetricsQuery(options: QueryBuildOptions): string {
  const { where } = buildWhereClause(options)

  return `
    -- Core Business Metrics Query
    SELECT
      'active_members' AS metric_name,
      uniqExact(member_id) AS metric_value,
      count() AS sample_size,
      sample_size < 10 AS low_sample
    FROM ${CLICKHOUSE_TABLES.member_events}
    ${where}
    UNION ALL
    SELECT
      'repurchase_rate' AS metric_name,
      round(countIf(order_count >= 2) * 100.0 / count(), 2) AS metric_value,
      count() AS sample_size,
      sample_size < 10 AS low_sample
    FROM (
      SELECT member_id, count() AS order_count
      FROM ${CLICKHOUSE_TABLES.orders}
      ${where}
      GROUP BY member_id
    )
    UNION ALL
    SELECT
      'avg_order_value' AS metric_name,
      round(avg(total_amount), 2) AS metric_value,
      count() AS sample_size,
      sample_size < 10 AS low_sample
    FROM ${CLICKHOUSE_TABLES.orders}
    ${where}
  `
}

export const QUERY_TEMPLATES = {
  coreMetrics: buildCoreMetricsQuery,
  cohort: buildCohortQuery,
} as const
