# Generated by Django 4.2.7 on 2026-06-05 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '创建'), ('update', '更新'), ('delete', '删除'), ('verify', '核验'), ('approve', '审批'), ('reject', '拒绝'), ('login', '登录'), ('export', '导出')], max_length=20, verbose_name='操作')),
                ('model_name', models.CharField(max_length=100, verbose_name='模型名')),
                ('object_id', models.CharField(blank=True, default='', max_length=100, verbose_name='对象ID')),
                ('detail', models.TextField(blank=True, default='', verbose_name='详情')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'db_table': 'common_auditlog',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='idx_audit_user_time'), models.Index(fields=['model_name', 'action'], name='idx_audit_model_action'), models.Index(fields=['created_at'], name='idx_audit_time')],
            },
        ),
    ]
