import request from '../utils/request'

export const getStatsOverview = () => request.get('/stats/overview')
export const getOrderStatusStats = () => request.get('/stats/order-status')
export const getRetentionStats = () => request.get('/stats/retention-stats')
export const getRecentActivities = () => request.get('/stats/recent-activities')

export const getBrands = params => request.get('/brands', { params })
export const getBrand = id => request.get(`/brands/${id}`)
export const createBrand = data => request.post('/brands', data)
export const updateBrand = (id, data) => request.put(`/brands/${id}`, data)
export const deleteBrand = id => request.delete(`/brands/${id}`)

export const getOrders = params => request.get('/orders', { params })
export const getOrder = id => request.get(`/orders/${id}`)
export const createOrder = data => request.post('/orders', data)
export const updateOrder = (id, data) => request.put(`/orders/${id}`, data)
export const deleteOrder = id => request.delete(`/orders/${id}`)
export const confirmPhotoSelection = (id, data) => request.post(`/orders/${id}/confirm-selection`, data)
export const markFinalDelivery = id => request.post(`/orders/${id}/final-delivery`)

export const getSchedules = params => request.get('/schedules', { params })
export const getSchedule = id => request.get(`/schedules/${id}`)
export const createSchedule = data => request.post('/schedules', data)
export const updateSchedule = (id, data) => request.put(`/schedules/${id}`, data)
export const deleteSchedule = id => request.delete(`/schedules/${id}`)

export const getDeliveryNodes = params => request.get('/delivery-nodes', { params })
export const getDeliveryNode = id => request.get(`/delivery-nodes/${id}`)
export const createDeliveryNode = data => request.post('/delivery-nodes', data)
export const updateDeliveryNode = (id, data) => request.put(`/delivery-nodes/${id}`, data)
export const deleteDeliveryNode = id => request.delete(`/delivery-nodes/${id}`)

export const getBrandQuotes = params => request.get('/brand-quotes', { params })
export const getBrandQuote = id => request.get(`/brand-quotes/${id}`)
export const createBrandQuote = data => request.post('/brand-quotes', data)
export const updateBrandQuote = (id, data) => request.put(`/brand-quotes/${id}`, data)
export const deleteBrandQuote = id => request.delete(`/brand-quotes/${id}`)

export const getContracts = params => request.get('/contracts', { params })
export const getContract = id => request.get(`/contracts/${id}`)
export const createContract = data => request.post('/contracts', data)
export const updateContract = (id, data) => request.put(`/contracts/${id}`, data)
export const deleteContract = id => request.delete(`/contracts/${id}`)

export const getPayments = params => request.get('/payments', { params })
export const getPayment = id => request.get(`/payments/${id}`)
export const createPayment = data => request.post('/payments', data)
export const updatePayment = (id, data) => request.put(`/payments/${id}`, data)
export const deletePayment = id => request.delete(`/payments/${id}`)

export const getWorkAuthorizations = params => request.get('/work-authorizations', { params })
export const getWorkAuthorization = id => request.get(`/work-authorizations/${id}`)
export const createWorkAuthorization = data => request.post('/work-authorizations', data)
export const updateWorkAuthorization = (id, data) => request.put(`/work-authorizations/${id}`, data)
export const deleteWorkAuthorization = id => request.delete(`/work-authorizations/${id}`)

export const getSelectedPhotos = params => request.get('/selected-photos', { params })
export const createSelectedPhoto = data => request.post('/selected-photos', data)
export const updateSelectedPhoto = (id, data) => request.put(`/selected-photos/${id}`, data)
export const deleteSelectedPhoto = id => request.delete(`/selected-photos/${id}`)

export const getFinalPhotos = params => request.get('/final-photos', { params })
export const createFinalPhoto = data => request.post('/final-photos', data)
export const downloadFinalPhoto = id => request.post(`/final-photos/${id}/download`)
export const updateFinalPhoto = (id, data) => request.put(`/final-photos/${id}`, data)
export const deleteFinalPhoto = id => request.delete(`/final-photos/${id}`)

export const getMembers = params => request.get('/members', { params })
export const getMember = id => request.get(`/members/${id}`)
export const createMember = data => request.post('/members', data)
export const updateMember = (id, data) => request.put(`/members/${id}`, data)
export const deleteMember = id => request.delete(`/members/${id}`)

export const getSubscriptions = params => request.get('/subscriptions', { params })
export const getSubscription = id => request.get(`/subscriptions/${id}`)
export const createSubscription = data => request.post('/subscriptions', data)
export const updateSubscription = (id, data) => request.put(`/subscriptions/${id}`, data)
export const deleteSubscription = id => request.delete(`/subscriptions/${id}`)
export const renewSubscription = id => request.post(`/subscriptions/${id}/renew`)

export const getSponsorships = params => request.get('/sponsorships', { params })
export const getSponsorship = id => request.get(`/sponsorships/${id}`)
export const createSponsorship = data => request.post('/sponsorships', data)
export const updateSponsorship = (id, data) => request.put(`/sponsorships/${id}`, data)
export const deleteSponsorship = id => request.delete(`/sponsorships/${id}`)

export const getExceptionPools = params => request.get('/exception-pools', { params })
export const getExceptionPool = id => request.get(`/exception-pools/${id}`)
export const createExceptionPool = data => request.post('/exception-pools', data)
export const updateExceptionPool = (id, data) => request.put(`/exception-pools/${id}`, data)
export const deleteExceptionPool = id => request.delete(`/exception-pools/${id}`)
export const submitIllustratorConclusion = (id, data) => request.post(`/exception-pools/${id}/illustrator-conclusion`, data)
export const confirmBrandException = id => request.post(`/exception-pools/${id}/brand-confirm`)

export const getSyncLogs = params => request.get('/sync-logs', { params })
export const createSyncLog = data => request.post('/sync-logs', data)
