"""退出码常量定义。"""

SUCCESS = 0
GENERAL_ERROR = 1
LOCKFILE_PARSE_ERROR = 2
VERSION_COMPARE_ERROR = 3
CONFIG_ERROR = 4
OUTPUT_ERROR = 5
VALIDATION_ERROR = 6
HIGH_RISK_CHANGES = 10
CRITICAL_RISK_CHANGES = 11

EXIT_MESSAGES = {
    SUCCESS: "执行成功",
    GENERAL_ERROR: "发生未知错误",
    LOCKFILE_PARSE_ERROR: "锁文件解析失败",
    VERSION_COMPARE_ERROR: "版本对比失败",
    CONFIG_ERROR: "配置加载失败",
    OUTPUT_ERROR: "输出格式化失败",
    VALIDATION_ERROR: "参数校验失败",
    HIGH_RISK_CHANGES: "报告中包含高风险变更",
    CRITICAL_RISK_CHANGES: "报告中包含严重风险变更",
}
