/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TagsRouteImport } from './routes/tags'
import { Route as ScriptsRouteImport } from './routes/scripts'
import { Route as SchedulesRouteImport } from './routes/schedules'
import { Route as Materials_idRouteImport } from './routes/materials_$id'
import { Route as MaterialsRouteImport } from './routes/materials'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ExceptionsRouteImport } from './routes/exceptions'
import { Route as ConversionsRouteImport } from './routes/conversions'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MaterialsIdRouteImport } from './routes/materials.$id'

const TagsRoute = TagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const ScriptsRoute = ScriptsRouteImport.update({
  id: '/scripts',
  path: '/scripts',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulesRoute = SchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => rootRouteImport,
} as any)
const Materials_idRoute = Materials_idRouteImport.update({
  id: '/materials_$id',
  path: '/materials_$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsRoute = MaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ExceptionsRoute = ExceptionsRouteImport.update({
  id: '/exceptions',
  path: '/exceptions',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversionsRoute = ConversionsRouteImport.update({
  id: '/conversions',
  path: '/conversions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsIdRoute = MaterialsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MaterialsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conversions': typeof ConversionsRoute
  '/exceptions': typeof ExceptionsRoute
  '/history': typeof HistoryRoute
  '/materials': typeof MaterialsRouteWithChildren
  '/materials_$id': typeof Materials_idRoute
  '/schedules': typeof SchedulesRoute
  '/scripts': typeof ScriptsRoute
  '/tags': typeof TagsRoute
  '/materials/$id': typeof MaterialsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conversions': typeof ConversionsRoute
  '/exceptions': typeof ExceptionsRoute
  '/history': typeof HistoryRoute
  '/materials': typeof MaterialsRouteWithChildren
  '/materials_$id': typeof Materials_idRoute
  '/schedules': typeof SchedulesRoute
  '/scripts': typeof ScriptsRoute
  '/tags': typeof TagsRoute
  '/materials/$id': typeof MaterialsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conversions': typeof ConversionsRoute
  '/exceptions': typeof ExceptionsRoute
  '/history': typeof HistoryRoute
  '/materials': typeof MaterialsRouteWithChildren
  '/materials_$id': typeof Materials_idRoute
  '/schedules': typeof SchedulesRoute
  '/scripts': typeof ScriptsRoute
  '/tags': typeof TagsRoute
  '/materials/$id': typeof MaterialsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/conversions'
    | '/exceptions'
    | '/history'
    | '/materials'
    | '/materials_$id'
    | '/schedules'
    | '/scripts'
    | '/tags'
    | '/materials/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/conversions'
    | '/exceptions'
    | '/history'
    | '/materials'
    | '/materials_$id'
    | '/schedules'
    | '/scripts'
    | '/tags'
    | '/materials/$id'
  id:
    | '__root__'
    | '/'
    | '/conversions'
    | '/exceptions'
    | '/history'
    | '/materials'
    | '/materials_$id'
    | '/schedules'
    | '/scripts'
    | '/tags'
    | '/materials/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConversionsRoute: typeof ConversionsRoute
  ExceptionsRoute: typeof ExceptionsRoute
  HistoryRoute: typeof HistoryRoute
  MaterialsRoute: typeof MaterialsRouteWithChildren
  Materials_idRoute: typeof Materials_idRoute
  SchedulesRoute: typeof SchedulesRoute
  ScriptsRoute: typeof ScriptsRoute
  TagsRoute: typeof TagsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tags': {
      id: '/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof TagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scripts': {
      id: '/scripts'
      path: '/scripts'
      fullPath: '/scripts'
      preLoaderRoute: typeof ScriptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedules': {
      id: '/schedules'
      path: '/schedules'
      fullPath: '/schedules'
      preLoaderRoute: typeof SchedulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials_$id': {
      id: '/materials_$id'
      path: '/materials_$id'
      fullPath: '/materials_$id'
      preLoaderRoute: typeof Materials_idRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials': {
      id: '/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof MaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exceptions': {
      id: '/exceptions'
      path: '/exceptions'
      fullPath: '/exceptions'
      preLoaderRoute: typeof ExceptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversions': {
      id: '/conversions'
      path: '/conversions'
      fullPath: '/conversions'
      preLoaderRoute: typeof ConversionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials/$id': {
      id: '/materials/$id'
      path: '/$id'
      fullPath: '/materials/$id'
      preLoaderRoute: typeof MaterialsIdRouteImport
      parentRoute: typeof MaterialsRoute
    }
  }
}

interface MaterialsRouteChildren {
  MaterialsIdRoute: typeof MaterialsIdRoute
}

const MaterialsRouteChildren: MaterialsRouteChildren = {
  MaterialsIdRoute: MaterialsIdRoute,
}

const MaterialsRouteWithChildren = MaterialsRoute._addFileChildren(
  MaterialsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConversionsRoute: ConversionsRoute,
  ExceptionsRoute: ExceptionsRoute,
  HistoryRoute: HistoryRoute,
  MaterialsRoute: MaterialsRouteWithChildren,
  Materials_idRoute: Materials_idRoute,
  SchedulesRoute: SchedulesRoute,
  ScriptsRoute: ScriptsRoute,
  TagsRoute: TagsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
