/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const MembershipLazyRouteImport = createFileRoute('/membership')()
const ContentLazyRouteImport = createFileRoute('/content')()
const AdminLazyRouteImport = createFileRoute('/admin')()
const IndexLazyRouteImport = createFileRoute('/')()
const ContentIdLazyRouteImport = createFileRoute('/content/$id')()
const AdminSubscriptionsLazyRouteImport = createFileRoute(
  '/admin/subscriptions',
)()
const AdminRulesLazyRouteImport = createFileRoute('/admin/rules')()
const AdminRetentionLazyRouteImport = createFileRoute('/admin/retention')()
const AdminOrdersLazyRouteImport = createFileRoute('/admin/orders')()
const AdminMaterialsLazyRouteImport = createFileRoute('/admin/materials')()
const AdminFeaturesLazyRouteImport = createFileRoute('/admin/features')()
const AdminExceptionsLazyRouteImport = createFileRoute('/admin/exceptions')()
const AdminDashboardLazyRouteImport = createFileRoute('/admin/dashboard')()

const MembershipLazyRoute = MembershipLazyRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/membership.lazy').then((d) => d.Route))
const ContentLazyRoute = ContentLazyRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/content.lazy').then((d) => d.Route))
const AdminLazyRoute = AdminLazyRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/admin.lazy').then((d) => d.Route))
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const ContentIdLazyRoute = ContentIdLazyRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ContentLazyRoute,
} as any).lazy(() => import('./routes/content/$id.lazy').then((d) => d.Route))
const AdminSubscriptionsLazyRoute = AdminSubscriptionsLazyRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminLazyRoute,
} as any).lazy(() =>
  import('./routes/admin/subscriptions.lazy').then((d) => d.Route),
)
const AdminRulesLazyRoute = AdminRulesLazyRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => AdminLazyRoute,
} as any).lazy(() => import('./routes/admin/rules.lazy').then((d) => d.Route))
const AdminRetentionLazyRoute = AdminRetentionLazyRouteImport.update({
  id: '/retention',
  path: '/retention',
  getParentRoute: () => AdminLazyRoute,
} as any).lazy(() =>
  import('./routes/admin/retention.lazy').then((d) => d.Route),
)
const AdminOrdersLazyRoute = AdminOrdersLazyRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminLazyRoute,
} as any).lazy(() => import('./routes/admin/orders.lazy').then((d) => d.Route))
const AdminMaterialsLazyRoute = AdminMaterialsLazyRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => AdminLazyRoute,
} as any).lazy(() =>
  import('./routes/admin/materials.lazy').then((d) => d.Route),
)
const AdminFeaturesLazyRoute = AdminFeaturesLazyRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => AdminLazyRoute,
} as any).lazy(() =>
  import('./routes/admin/features.lazy').then((d) => d.Route),
)
const AdminExceptionsLazyRoute = AdminExceptionsLazyRouteImport.update({
  id: '/exceptions',
  path: '/exceptions',
  getParentRoute: () => AdminLazyRoute,
} as any).lazy(() =>
  import('./routes/admin/exceptions.lazy').then((d) => d.Route),
)
const AdminDashboardLazyRoute = AdminDashboardLazyRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminLazyRoute,
} as any).lazy(() =>
  import('./routes/admin/dashboard.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/admin': typeof AdminLazyRouteWithChildren
  '/content': typeof ContentLazyRouteWithChildren
  '/membership': typeof MembershipLazyRoute
  '/admin/dashboard': typeof AdminDashboardLazyRoute
  '/admin/exceptions': typeof AdminExceptionsLazyRoute
  '/admin/features': typeof AdminFeaturesLazyRoute
  '/admin/materials': typeof AdminMaterialsLazyRoute
  '/admin/orders': typeof AdminOrdersLazyRoute
  '/admin/retention': typeof AdminRetentionLazyRoute
  '/admin/rules': typeof AdminRulesLazyRoute
  '/admin/subscriptions': typeof AdminSubscriptionsLazyRoute
  '/content/$id': typeof ContentIdLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/admin': typeof AdminLazyRouteWithChildren
  '/content': typeof ContentLazyRouteWithChildren
  '/membership': typeof MembershipLazyRoute
  '/admin/dashboard': typeof AdminDashboardLazyRoute
  '/admin/exceptions': typeof AdminExceptionsLazyRoute
  '/admin/features': typeof AdminFeaturesLazyRoute
  '/admin/materials': typeof AdminMaterialsLazyRoute
  '/admin/orders': typeof AdminOrdersLazyRoute
  '/admin/retention': typeof AdminRetentionLazyRoute
  '/admin/rules': typeof AdminRulesLazyRoute
  '/admin/subscriptions': typeof AdminSubscriptionsLazyRoute
  '/content/$id': typeof ContentIdLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/admin': typeof AdminLazyRouteWithChildren
  '/content': typeof ContentLazyRouteWithChildren
  '/membership': typeof MembershipLazyRoute
  '/admin/dashboard': typeof AdminDashboardLazyRoute
  '/admin/exceptions': typeof AdminExceptionsLazyRoute
  '/admin/features': typeof AdminFeaturesLazyRoute
  '/admin/materials': typeof AdminMaterialsLazyRoute
  '/admin/orders': typeof AdminOrdersLazyRoute
  '/admin/retention': typeof AdminRetentionLazyRoute
  '/admin/rules': typeof AdminRulesLazyRoute
  '/admin/subscriptions': typeof AdminSubscriptionsLazyRoute
  '/content/$id': typeof ContentIdLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/content'
    | '/membership'
    | '/admin/dashboard'
    | '/admin/exceptions'
    | '/admin/features'
    | '/admin/materials'
    | '/admin/orders'
    | '/admin/retention'
    | '/admin/rules'
    | '/admin/subscriptions'
    | '/content/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/content'
    | '/membership'
    | '/admin/dashboard'
    | '/admin/exceptions'
    | '/admin/features'
    | '/admin/materials'
    | '/admin/orders'
    | '/admin/retention'
    | '/admin/rules'
    | '/admin/subscriptions'
    | '/content/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/content'
    | '/membership'
    | '/admin/dashboard'
    | '/admin/exceptions'
    | '/admin/features'
    | '/admin/materials'
    | '/admin/orders'
    | '/admin/retention'
    | '/admin/rules'
    | '/admin/subscriptions'
    | '/content/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AdminLazyRoute: typeof AdminLazyRouteWithChildren
  ContentLazyRoute: typeof ContentLazyRouteWithChildren
  MembershipLazyRoute: typeof MembershipLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content': {
      id: '/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof ContentLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/$id': {
      id: '/content/$id'
      path: '/$id'
      fullPath: '/content/$id'
      preLoaderRoute: typeof ContentIdLazyRouteImport
      parentRoute: typeof ContentLazyRoute
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsLazyRouteImport
      parentRoute: typeof AdminLazyRoute
    }
    '/admin/rules': {
      id: '/admin/rules'
      path: '/rules'
      fullPath: '/admin/rules'
      preLoaderRoute: typeof AdminRulesLazyRouteImport
      parentRoute: typeof AdminLazyRoute
    }
    '/admin/retention': {
      id: '/admin/retention'
      path: '/retention'
      fullPath: '/admin/retention'
      preLoaderRoute: typeof AdminRetentionLazyRouteImport
      parentRoute: typeof AdminLazyRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersLazyRouteImport
      parentRoute: typeof AdminLazyRoute
    }
    '/admin/materials': {
      id: '/admin/materials'
      path: '/materials'
      fullPath: '/admin/materials'
      preLoaderRoute: typeof AdminMaterialsLazyRouteImport
      parentRoute: typeof AdminLazyRoute
    }
    '/admin/features': {
      id: '/admin/features'
      path: '/features'
      fullPath: '/admin/features'
      preLoaderRoute: typeof AdminFeaturesLazyRouteImport
      parentRoute: typeof AdminLazyRoute
    }
    '/admin/exceptions': {
      id: '/admin/exceptions'
      path: '/exceptions'
      fullPath: '/admin/exceptions'
      preLoaderRoute: typeof AdminExceptionsLazyRouteImport
      parentRoute: typeof AdminLazyRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardLazyRouteImport
      parentRoute: typeof AdminLazyRoute
    }
  }
}

interface AdminLazyRouteChildren {
  AdminDashboardLazyRoute: typeof AdminDashboardLazyRoute
  AdminExceptionsLazyRoute: typeof AdminExceptionsLazyRoute
  AdminFeaturesLazyRoute: typeof AdminFeaturesLazyRoute
  AdminMaterialsLazyRoute: typeof AdminMaterialsLazyRoute
  AdminOrdersLazyRoute: typeof AdminOrdersLazyRoute
  AdminRetentionLazyRoute: typeof AdminRetentionLazyRoute
  AdminRulesLazyRoute: typeof AdminRulesLazyRoute
  AdminSubscriptionsLazyRoute: typeof AdminSubscriptionsLazyRoute
}

const AdminLazyRouteChildren: AdminLazyRouteChildren = {
  AdminDashboardLazyRoute: AdminDashboardLazyRoute,
  AdminExceptionsLazyRoute: AdminExceptionsLazyRoute,
  AdminFeaturesLazyRoute: AdminFeaturesLazyRoute,
  AdminMaterialsLazyRoute: AdminMaterialsLazyRoute,
  AdminOrdersLazyRoute: AdminOrdersLazyRoute,
  AdminRetentionLazyRoute: AdminRetentionLazyRoute,
  AdminRulesLazyRoute: AdminRulesLazyRoute,
  AdminSubscriptionsLazyRoute: AdminSubscriptionsLazyRoute,
}

const AdminLazyRouteWithChildren = AdminLazyRoute._addFileChildren(
  AdminLazyRouteChildren,
)

interface ContentLazyRouteChildren {
  ContentIdLazyRoute: typeof ContentIdLazyRoute
}

const ContentLazyRouteChildren: ContentLazyRouteChildren = {
  ContentIdLazyRoute: ContentIdLazyRoute,
}

const ContentLazyRouteWithChildren = ContentLazyRoute._addFileChildren(
  ContentLazyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AdminLazyRoute: AdminLazyRouteWithChildren,
  ContentLazyRoute: ContentLazyRouteWithChildren,
  MembershipLazyRoute: MembershipLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
