/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as MyRouteImport } from './routes/my'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIdRouteImport } from './routes/products.$id'
import { Route as MyProfileRouteImport } from './routes/my.profile'
import { Route as MyOrdersRouteImport } from './routes/my.orders'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminStatisticsRouteImport } from './routes/admin.statistics'
import { Route as AdminReachRouteImport } from './routes/admin.reach'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminMembersRouteImport } from './routes/admin.members'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminLevelsRouteImport } from './routes/admin.levels'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminLayoutRouteImport } from './routes/admin._layout'
import { Route as MyOrdersIdRouteImport } from './routes/my.orders.$id'
import { Route as AdminReachIdRouteImport } from './routes/admin.reach.$id'
import { Route as AdminProductsNewRouteImport } from './routes/admin.products.new'
import { Route as AdminProductsIdEditRouteImport } from './routes/admin.products.$id.edit'

const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const MyRoute = MyRouteImport.update({
  id: '/my',
  path: '/my',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProductsRoute,
} as any)
const MyProfileRoute = MyProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MyRoute,
} as any)
const MyOrdersRoute = MyOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => MyRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStatisticsRoute = AdminStatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReachRoute = AdminReachRouteImport.update({
  id: '/reach',
  path: '/reach',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLevelsRoute = AdminLevelsRouteImport.update({
  id: '/levels',
  path: '/levels',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => AdminRoute,
} as any)
const MyOrdersIdRoute = MyOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MyOrdersRoute,
} as any)
const AdminReachIdRoute = AdminReachIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminReachRoute,
} as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminProductsRoute,
} as any)
const AdminProductsIdEditRoute = AdminProductsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AdminProductsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/my': typeof MyRouteWithChildren
  '/products': typeof ProductsRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/levels': typeof AdminLevelsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/reach': typeof AdminReachRouteWithChildren
  '/admin/statistics': typeof AdminStatisticsRoute
  '/admin/users': typeof AdminUsersRoute
  '/my/orders': typeof MyOrdersRouteWithChildren
  '/my/profile': typeof MyProfileRoute
  '/products/$id': typeof ProductsIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/reach/$id': typeof AdminReachIdRoute
  '/my/orders/$id': typeof MyOrdersIdRoute
  '/admin/products/$id/edit': typeof AdminProductsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/my': typeof MyRouteWithChildren
  '/products': typeof ProductsRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/levels': typeof AdminLevelsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/reach': typeof AdminReachRouteWithChildren
  '/admin/statistics': typeof AdminStatisticsRoute
  '/admin/users': typeof AdminUsersRoute
  '/my/orders': typeof MyOrdersRouteWithChildren
  '/my/profile': typeof MyProfileRoute
  '/products/$id': typeof ProductsIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/reach/$id': typeof AdminReachIdRoute
  '/my/orders/$id': typeof MyOrdersIdRoute
  '/admin/products/$id/edit': typeof AdminProductsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/my': typeof MyRouteWithChildren
  '/products': typeof ProductsRouteWithChildren
  '/admin/_layout': typeof AdminLayoutRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/levels': typeof AdminLevelsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/reach': typeof AdminReachRouteWithChildren
  '/admin/statistics': typeof AdminStatisticsRoute
  '/admin/users': typeof AdminUsersRoute
  '/my/orders': typeof MyOrdersRouteWithChildren
  '/my/profile': typeof MyProfileRoute
  '/products/$id': typeof ProductsIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/reach/$id': typeof AdminReachIdRoute
  '/my/orders/$id': typeof MyOrdersIdRoute
  '/admin/products/$id/edit': typeof AdminProductsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/my'
    | '/products'
    | '/admin/dashboard'
    | '/admin/levels'
    | '/admin/login'
    | '/admin/logs'
    | '/admin/members'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reach'
    | '/admin/statistics'
    | '/admin/users'
    | '/my/orders'
    | '/my/profile'
    | '/products/$id'
    | '/admin/products/new'
    | '/admin/reach/$id'
    | '/my/orders/$id'
    | '/admin/products/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/my'
    | '/products'
    | '/admin/dashboard'
    | '/admin/levels'
    | '/admin/login'
    | '/admin/logs'
    | '/admin/members'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reach'
    | '/admin/statistics'
    | '/admin/users'
    | '/my/orders'
    | '/my/profile'
    | '/products/$id'
    | '/admin/products/new'
    | '/admin/reach/$id'
    | '/my/orders/$id'
    | '/admin/products/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/my'
    | '/products'
    | '/admin/_layout'
    | '/admin/dashboard'
    | '/admin/levels'
    | '/admin/login'
    | '/admin/logs'
    | '/admin/members'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reach'
    | '/admin/statistics'
    | '/admin/users'
    | '/my/orders'
    | '/my/profile'
    | '/products/$id'
    | '/admin/products/new'
    | '/admin/reach/$id'
    | '/my/orders/$id'
    | '/admin/products/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  MyRoute: typeof MyRouteWithChildren
  ProductsRoute: typeof ProductsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my': {
      id: '/my'
      path: '/my'
      fullPath: '/my'
      preLoaderRoute: typeof MyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/my/profile': {
      id: '/my/profile'
      path: '/profile'
      fullPath: '/my/profile'
      preLoaderRoute: typeof MyProfileRouteImport
      parentRoute: typeof MyRoute
    }
    '/my/orders': {
      id: '/my/orders'
      path: '/orders'
      fullPath: '/my/orders'
      preLoaderRoute: typeof MyOrdersRouteImport
      parentRoute: typeof MyRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/statistics': {
      id: '/admin/statistics'
      path: '/statistics'
      fullPath: '/admin/statistics'
      preLoaderRoute: typeof AdminStatisticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reach': {
      id: '/admin/reach'
      path: '/reach'
      fullPath: '/admin/reach'
      preLoaderRoute: typeof AdminReachRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/members': {
      id: '/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/levels': {
      id: '/admin/levels'
      path: '/levels'
      fullPath: '/admin/levels'
      preLoaderRoute: typeof AdminLevelsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/_layout': {
      id: '/admin/_layout'
      path: ''
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof AdminRoute
    }
    '/my/orders/$id': {
      id: '/my/orders/$id'
      path: '/$id'
      fullPath: '/my/orders/$id'
      preLoaderRoute: typeof MyOrdersIdRouteImport
      parentRoute: typeof MyOrdersRoute
    }
    '/admin/reach/$id': {
      id: '/admin/reach/$id'
      path: '/$id'
      fullPath: '/admin/reach/$id'
      preLoaderRoute: typeof AdminReachIdRouteImport
      parentRoute: typeof AdminReachRoute
    }
    '/admin/products/new': {
      id: '/admin/products/new'
      path: '/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/admin/products/$id/edit': {
      id: '/admin/products/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/products/$id/edit'
      preLoaderRoute: typeof AdminProductsIdEditRouteImport
      parentRoute: typeof AdminProductsRoute
    }
  }
}

interface AdminProductsRouteChildren {
  AdminProductsNewRoute: typeof AdminProductsNewRoute
  AdminProductsIdEditRoute: typeof AdminProductsIdEditRoute
}

const AdminProductsRouteChildren: AdminProductsRouteChildren = {
  AdminProductsNewRoute: AdminProductsNewRoute,
  AdminProductsIdEditRoute: AdminProductsIdEditRoute,
}

const AdminProductsRouteWithChildren = AdminProductsRoute._addFileChildren(
  AdminProductsRouteChildren,
)

interface AdminReachRouteChildren {
  AdminReachIdRoute: typeof AdminReachIdRoute
}

const AdminReachRouteChildren: AdminReachRouteChildren = {
  AdminReachIdRoute: AdminReachIdRoute,
}

const AdminReachRouteWithChildren = AdminReachRoute._addFileChildren(
  AdminReachRouteChildren,
)

interface AdminRouteChildren {
  AdminLayoutRoute: typeof AdminLayoutRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLevelsRoute: typeof AdminLevelsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminMembersRoute: typeof AdminMembersRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRouteWithChildren
  AdminReachRoute: typeof AdminReachRouteWithChildren
  AdminStatisticsRoute: typeof AdminStatisticsRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLayoutRoute: AdminLayoutRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLevelsRoute: AdminLevelsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminMembersRoute: AdminMembersRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRouteWithChildren,
  AdminReachRoute: AdminReachRouteWithChildren,
  AdminStatisticsRoute: AdminStatisticsRoute,
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MyOrdersRouteChildren {
  MyOrdersIdRoute: typeof MyOrdersIdRoute
}

const MyOrdersRouteChildren: MyOrdersRouteChildren = {
  MyOrdersIdRoute: MyOrdersIdRoute,
}

const MyOrdersRouteWithChildren = MyOrdersRoute._addFileChildren(
  MyOrdersRouteChildren,
)

interface MyRouteChildren {
  MyOrdersRoute: typeof MyOrdersRouteWithChildren
  MyProfileRoute: typeof MyProfileRoute
}

const MyRouteChildren: MyRouteChildren = {
  MyOrdersRoute: MyOrdersRouteWithChildren,
  MyProfileRoute: MyProfileRoute,
}

const MyRouteWithChildren = MyRoute._addFileChildren(MyRouteChildren)

interface ProductsRouteChildren {
  ProductsIdRoute: typeof ProductsIdRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsIdRoute: ProductsIdRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  MyRoute: MyRouteWithChildren,
  ProductsRoute: ProductsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
