/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
import { Route as rootRouteImport } from './routes/__root';
import { Route as TagsRouteImport } from './routes/tags';
import { Route as ScriptsRouteImport } from './routes/scripts';
import { Route as SchedulesRouteImport } from './routes/schedules';
import { Route as Materials_idRouteImport } from './routes/materials_$id';
import { Route as MaterialsRouteImport } from './routes/materials';
import { Route as HistoryRouteImport } from './routes/history';
import { Route as ExceptionsRouteImport } from './routes/exceptions';
import { Route as ConversionsRouteImport } from './routes/conversions';
import { Route as IndexRouteImport } from './routes/index';
import { Route as MaterialsIdRouteImport } from './routes/materials.$id';
const TagsRoute = TagsRouteImport.update({
    id: '/tags',
    path: '/tags',
    getParentRoute: () => rootRouteImport,
});
const ScriptsRoute = ScriptsRouteImport.update({
    id: '/scripts',
    path: '/scripts',
    getParentRoute: () => rootRouteImport,
});
const SchedulesRoute = SchedulesRouteImport.update({
    id: '/schedules',
    path: '/schedules',
    getParentRoute: () => rootRouteImport,
});
const Materials_idRoute = Materials_idRouteImport.update({
    id: '/materials_$id',
    path: '/materials_$id',
    getParentRoute: () => rootRouteImport,
});
const MaterialsRoute = MaterialsRouteImport.update({
    id: '/materials',
    path: '/materials',
    getParentRoute: () => rootRouteImport,
});
const HistoryRoute = HistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => rootRouteImport,
});
const ExceptionsRoute = ExceptionsRouteImport.update({
    id: '/exceptions',
    path: '/exceptions',
    getParentRoute: () => rootRouteImport,
});
const ConversionsRoute = ConversionsRouteImport.update({
    id: '/conversions',
    path: '/conversions',
    getParentRoute: () => rootRouteImport,
});
const IndexRoute = IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => rootRouteImport,
});
const MaterialsIdRoute = MaterialsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => MaterialsRoute,
});
const MaterialsRouteChildren = {
    MaterialsIdRoute: MaterialsIdRoute,
};
const MaterialsRouteWithChildren = MaterialsRoute._addFileChildren(MaterialsRouteChildren);
const rootRouteChildren = {
    IndexRoute: IndexRoute,
    ConversionsRoute: ConversionsRoute,
    ExceptionsRoute: ExceptionsRoute,
    HistoryRoute: HistoryRoute,
    MaterialsRoute: MaterialsRouteWithChildren,
    Materials_idRoute: Materials_idRoute,
    SchedulesRoute: SchedulesRoute,
    ScriptsRoute: ScriptsRoute,
    TagsRoute: TagsRoute,
};
export const routeTree = rootRouteImport
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes();
