# Generated by Django 5.0.1 on 2026-06-11 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='规则名称')),
                ('description', models.TextField(blank=True, verbose_name='规则描述')),
                ('rule_type', models.CharField(max_length=50, verbose_name='规则类型')),
                ('pattern', models.TextField(verbose_name='匹配规则')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('severity', models.CharField(default='medium', max_length=20, verbose_name='严重程度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '审核规则',
                'verbose_name_plural': '审核规则',
                'db_table': 'review_rules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_type', models.CharField(choices=[('content', '内容审核'), ('quality', '质量审核'), ('safety', '安全审核')], db_index=True, max_length=50, verbose_name='审核类型')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝'), ('flagged', '需关注')], db_index=True, default='pending', max_length=20, verbose_name='审核状态')),
                ('comment', models.TextField(blank=True, verbose_name='审核意见')),
                ('risk_level', models.CharField(blank=True, max_length=20, verbose_name='风险等级')),
                ('flagged_by_ai', models.BooleanField(default=False, verbose_name='AI标记')),
                ('sales_operation', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='销售运营分组')),
                ('prompt_version', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='提示词版本')),
                ('ai_model', models.CharField(blank=True, max_length=100, verbose_name='AI模型')),
                ('is_accurate', models.BooleanField(blank=True, db_index=True, null=True, verbose_name='是否准确')),
                ('inaccuracy_reason', models.CharField(blank=True, max_length=100, verbose_name='不准确原因')),
                ('risk_tags', models.JSONField(blank=True, default=list, verbose_name='风险标签')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='conversations.message', verbose_name='消息')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
            ],
            options={
                'verbose_name': '审核记录',
                'verbose_name_plural': '审核记录',
                'db_table': 'reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
