# Generated by Django 4.2.30 on 2026-06-17 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=200, verbose_name='报表名称')),
                ('report_type', models.CharField(choices=[('ticket_summary', '工单汇总报表'), ('ticket_detail', '工单明细报表'), ('quality_report', '质检报表'), ('agent_performance', '客服绩效报表'), ('knowledge_usage', '知识库使用报表'), ('custom', '自定义报表')], default='custom', max_length=30, verbose_name='报表类型')),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '禁用')], default='active', max_length=20, verbose_name='状态')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='报表配置')),
                ('columns', models.JSONField(blank=True, default=list, verbose_name='列配置')),
                ('filters', models.JSONField(blank=True, default=dict, verbose_name='默认筛选条件')),
                ('chart_config', models.JSONField(blank=True, default=dict, verbose_name='图表配置')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '报表模板',
                'verbose_name_plural': '报表模板',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=200, verbose_name='调度名称')),
                ('frequency', models.CharField(choices=[('daily', '每日'), ('weekly', '每周'), ('monthly', '每月'), ('quarterly', '每季度')], default='daily', max_length=20, verbose_name='执行频率')),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '禁用')], default='active', max_length=20, verbose_name='状态')),
                ('run_time', models.TimeField(verbose_name='执行时间')),
                ('day_of_week', models.IntegerField(blank=True, null=True, verbose_name='周几(0-6)')),
                ('day_of_month', models.IntegerField(blank=True, null=True, verbose_name='几号(1-31)')),
                ('recipients', models.JSONField(blank=True, default=list, verbose_name='接收人列表')),
                ('filters', models.JSONField(blank=True, default=dict, verbose_name='筛选条件')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='上次运行时间')),
                ('next_run_at', models.DateTimeField(blank=True, null=True, verbose_name='下次运行时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='reports.reporttemplate', verbose_name='报表模板')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '报表调度',
                'verbose_name_plural': '报表调度',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=200, verbose_name='报表名称')),
                ('report_type', models.CharField(max_length=30, verbose_name='报表类型')),
                ('status', models.CharField(choices=[('pending', '待生成'), ('generating', '生成中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='参数')),
                ('filters', models.JSONField(blank=True, default=dict, verbose_name='筛选条件')),
                ('summary_data', models.JSONField(blank=True, default=dict, verbose_name='汇总数据')),
                ('chart_data', models.JSONField(blank=True, default=dict, verbose_name='图表数据')),
                ('file_path', models.FileField(blank=True, null=True, upload_to='reports/', verbose_name='文件路径')),
                ('file_size', models.IntegerField(blank=True, null=True, verbose_name='文件大小(字节)')),
                ('record_count', models.IntegerField(blank=True, null=True, verbose_name='记录数')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('period_start', models.DateField(blank=True, null=True, verbose_name='统计开始日期')),
                ('period_end', models.DateField(blank=True, null=True, verbose_name='统计结束日期')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='reports.reportschedule', verbose_name='报表调度')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='reports.reporttemplate', verbose_name='报表模板')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '报表实例',
                'verbose_name_plural': '报表实例',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=200, verbose_name='组件名称')),
                ('widget_type', models.CharField(choices=[('card', '数值卡片'), ('chart_line', '折线图'), ('chart_bar', '柱状图'), ('chart_pie', '饼图'), ('table', '数据表格')], default='card', max_length=20, verbose_name='组件类型')),
                ('size', models.CharField(choices=[('small', '小'), ('medium', '中'), ('large', '大')], default='medium', max_length=20, verbose_name='尺寸')),
                ('data_source', models.CharField(max_length=200, verbose_name='数据源')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='组件配置')),
                ('position', models.IntegerField(default=0, verbose_name='排序位置')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('refresh_interval', models.IntegerField(default=300, verbose_name='刷新间隔(秒)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '仪表盘组件',
                'verbose_name_plural': '仪表盘组件',
                'ordering': ['position'],
            },
        ),
    ]
