# Generated by Django 4.2.7 on 2026-06-06 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('materials', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wastage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='报损数量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='报损金额')),
                ('reason', models.CharField(blank=True, choices=[('expired', '过期'), ('damaged', '损坏'), ('spoilage', '变质'), ('operation', '操作失误'), ('other', '其他')], max_length=20, verbose_name='报损原因')),
                ('shift', models.CharField(blank=True, choices=[('morning', '早班'), ('afternoon', '中班'), ('evening', '晚班'), ('all', '全天')], max_length=20, verbose_name='班次')),
                ('record_date', models.DateField(verbose_name='记录日期')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wastage_records', to='materials.material', verbose_name='原料')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wastage_records', to='organization.store', verbose_name='门店')),
            ],
            options={
                'verbose_name': '报损记录',
                'verbose_name_plural': '报损记录',
                'ordering': ['-record_date'],
            },
        ),
        migrations.CreateModel(
            name='Stocktake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('system_quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='系统库存')),
                ('actual_quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='实际库存')),
                ('diff_quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='差异数量')),
                ('diff_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='差异金额')),
                ('shift', models.CharField(blank=True, choices=[('morning', '早班'), ('afternoon', '中班'), ('evening', '晚班'), ('all', '全天')], max_length=20, verbose_name='班次')),
                ('record_date', models.DateField(verbose_name='盘点日期')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocktake_records', to='materials.material', verbose_name='原料')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocktake_records', to='organization.store', verbose_name='门店')),
            ],
            options={
                'verbose_name': '盘点记录',
                'verbose_name_plural': '盘点记录',
                'ordering': ['-record_date'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('product_name', models.CharField(max_length=100, verbose_name='产品名称')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='销售数量')),
                ('material_consume', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='原料消耗量')),
                ('sale_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='销售金额')),
                ('shift', models.CharField(blank=True, choices=[('morning', '早班'), ('afternoon', '中班'), ('evening', '晚班'), ('all', '全天')], max_length=20, verbose_name='班次')),
                ('sale_date', models.DateField(verbose_name='销售日期')),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_records', to='materials.material', verbose_name='关联原料')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_records', to='organization.store', verbose_name='门店')),
            ],
            options={
                'verbose_name': '销售记录',
                'verbose_name_plural': '销售记录',
                'ordering': ['-sale_date'],
            },
        ),
        migrations.CreateModel(
            name='MaterialUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='领用数量')),
                ('shift', models.CharField(blank=True, choices=[('morning', '早班'), ('afternoon', '中班'), ('evening', '晚班'), ('all', '全天')], max_length=20, verbose_name='班次')),
                ('record_date', models.DateField(verbose_name='记录日期')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='use_records', to='materials.material', verbose_name='原料')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='use_records', to='organization.store', verbose_name='门店')),
            ],
            options={
                'verbose_name': '原料领用',
                'verbose_name_plural': '原料领用',
                'ordering': ['-record_date'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='数量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='总金额')),
                ('record_date', models.DateField(verbose_name='记录日期')),
                ('batch_no', models.CharField(blank=True, max_length=50, verbose_name='批次号')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_records', to='materials.material', verbose_name='原料')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_records', to='organization.store', verbose_name='门店')),
            ],
            options={
                'verbose_name': '进货记录',
                'verbose_name_plural': '进货记录',
                'ordering': ['-record_date'],
            },
        ),
    ]
