# Generated by Django 4.2.30 on 2026-06-17 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('ticket_no', models.CharField(max_length=32, unique=True, verbose_name='工单编号')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('description', models.TextField(verbose_name='问题描述')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('escalated', '已升级'), ('resolved', '已解决'), ('closed', '已关闭')], default='pending', max_length=20, verbose_name='状态')),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('urgent', '紧急')], default='medium', max_length=20, verbose_name='优先级')),
                ('type', models.CharField(choices=[('refund', '退款'), ('exchange', '换货'), ('complaint', '投诉'), ('consult', '咨询'), ('other', '其他')], default='consult', max_length=20, verbose_name='工单类型')),
                ('order_no', models.CharField(blank=True, max_length=50, verbose_name='订单号')),
                ('product_name', models.CharField(blank=True, max_length=200, verbose_name='商品名称')),
                ('customer_name', models.CharField(max_length=100, verbose_name='客户姓名')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='客户电话')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='客户邮箱')),
                ('escalated_at', models.DateTimeField(blank=True, null=True, verbose_name='升级时间')),
                ('escalation_reason', models.TextField(blank=True, verbose_name='升级原因')),
                ('first_response_at', models.DateTimeField(blank=True, null=True, verbose_name='首次响应时间')),
                ('resolution', models.TextField(blank=True, verbose_name='处理结果')),
                ('sla_deadline', models.DateTimeField(verbose_name='SLA截止时间')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='解决时间')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='关闭时间')),
                ('satisfaction_score', models.IntegerField(blank=True, null=True, verbose_name='满意度评分')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tickets', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('escalated_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_tickets', to=settings.AUTH_USER_MODEL, verbose_name='升级对象')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '工单',
                'verbose_name_plural': '工单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('content', models.TextField(verbose_name='内容')),
                ('is_internal', models.BooleanField(default=False, verbose_name='是否内部备注')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='ticket_notes/', verbose_name='附件')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='tickets.ticket', verbose_name='工单')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '工单备注',
                'verbose_name_plural': '工单备注',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ticket'], name='tickets_tic_ticket__628abb_idx'), models.Index(fields=['is_internal'], name='tickets_tic_is_inte_280e07_idx'), models.Index(fields=['created_at'], name='tickets_tic_created_5c4505_idx')],
            },
        ),
        migrations.CreateModel(
            name='TicketHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('action', models.CharField(max_length=100, verbose_name='操作')),
                ('description', models.TextField(blank=True, verbose_name='操作描述')),
                ('old_value', models.TextField(blank=True, verbose_name='旧值')),
                ('new_value', models.TextField(blank=True, verbose_name='新值')),
                ('field_name', models.CharField(blank=True, max_length=50, verbose_name='字段名')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_actions', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tickets.ticket', verbose_name='工单')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '工单历史',
                'verbose_name_plural': '工单历史',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ticket'], name='tickets_tic_ticket__7caf7f_idx'), models.Index(fields=['actor'], name='tickets_tic_actor_i_1ad71b_idx'), models.Index(fields=['action'], name='tickets_tic_action_385164_idx'), models.Index(fields=['created_at'], name='tickets_tic_created_3b741b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['ticket_no'], name='tickets_tic_ticket__c7390a_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status'], name='tickets_tic_status_0e5646_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['priority'], name='tickets_tic_priorit_0bec9b_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['type'], name='tickets_tic_type_29dfeb_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['assignee'], name='tickets_tic_assigne_8f75bf_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['creator'], name='tickets_tic_creator_3210bf_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['created_at'], name='tickets_tic_created_5dd600_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['sla_deadline'], name='tickets_tic_sla_dea_506c6c_idx'),
        ),
    ]
