# Generated by Django 4.2.30 on 2026-06-17 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='escalation_reason',
            field=models.TextField(blank=True, null=True, verbose_name='升级原因'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='resolution',
            field=models.TextField(blank=True, null=True, verbose_name='处理结果'),
        ),
    ]
