# Generated by Django 4.2.30 on 2026-06-17 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0002_fix_null_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketnote',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ticket_notes', to=settings.AUTH_USER_MODEL, verbose_name='备注人'),
        ),
    ]
