# Generated by Django 4.2.7 on 2026-06-05 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChronicDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='疾病名称')),
                ('icd_code', models.CharField(blank=True, max_length=20, verbose_name='ICD编码')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '慢病类型',
                'verbose_name_plural': '慢病类型',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_no', models.CharField(max_length=50, unique=True, verbose_name='病历号')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女'), ('O', '其他')], max_length=10, verbose_name='性别')),
                ('birth_date', models.DateField(verbose_name='出生日期')),
                ('id_card', models.CharField(max_length=18, unique=True, verbose_name='身份证号')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='CN', verbose_name='手机号')),
                ('emergency_contact', models.CharField(max_length=100, verbose_name='紧急联系人')),
                ('emergency_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='CN', verbose_name='紧急联系人电话')),
                ('address', models.TextField(blank=True, verbose_name='住址')),
                ('marital_status', models.CharField(choices=[('SINGLE', '未婚'), ('MARRIED', '已婚'), ('DIVORCED', '离异'), ('WIDOWED', '丧偶')], default='SINGLE', max_length=20, verbose_name='婚姻状况')),
                ('allergies', models.TextField(blank=True, verbose_name='过敏史')),
                ('medical_history', models.TextField(blank=True, verbose_name='既往病史')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='身高(cm)')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='体重(kg)')),
                ('blood_type', models.CharField(blank=True, max_length=5, verbose_name='血型')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('no_show_count', models.IntegerField(default=0, verbose_name='爽约次数')),
                ('needs_confirmation', models.BooleanField(default=False, verbose_name='需要电话确认')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chronic_diseases', models.ManyToManyField(blank=True, related_name='patients', to='patients.chronicdisease', verbose_name='慢病')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_patients', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '患者档案',
                'verbose_name_plural': '患者档案',
                'ordering': ['-created_at'],
            },
        ),
    ]
