# Generated by Django 4.2.30 on 2026-06-05 20:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('purpose', models.TextField(verbose_name='使用目的')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已确认'), ('rejected', '已拒绝'), ('cancelled', '已取消'), ('in_progress', '使用中'), ('completed', '已完成'), ('no_show', '未到场')], default='pending', max_length=20, verbose_name='状态')),
                ('approval_notes', models.TextField(blank=True, verbose_name='审批备注')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('actual_start_time', models.DateTimeField(blank=True, null=True, verbose_name='实际开始时间')),
                ('actual_end_time', models.DateTimeField(blank=True, null=True, verbose_name='实际结束时间')),
                ('check_in_code', models.CharField(blank=True, max_length=10, verbose_name='签到码')),
                ('is_checked_in', models.BooleanField(default=False, verbose_name='已签到')),
                ('checked_in_at', models.DateTimeField(blank=True, null=True, verbose_name='签到时间')),
            ],
            options={
                'verbose_name': '设备预约',
                'verbose_name_plural': '设备预约',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='BookingConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_at', models.DateTimeField(auto_now_add=True, verbose_name='检测时间')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='bookings.booking', verbose_name='预约')),
                ('conflicting_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicting_with', to='bookings.booking', verbose_name='冲突预约')),
            ],
            options={
                'verbose_name': '预约冲突',
                'verbose_name_plural': '预约冲突',
            },
        ),
    ]
