# Generated by Django 4.2.7 on 2026-06-05 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('employee_no', models.CharField(max_length=50, unique=True, verbose_name='工号')),
                ('title', models.CharField(choices=[('INTERN', '实习医师'), ('RESIDENT', '住院医师'), ('ATTENDING', '主治医师'), ('ASSOCIATE', '副主任医师'), ('CHIEF', '主任医师')], default='RESIDENT', max_length=20, verbose_name='职称')),
                ('specialties', models.TextField(blank=True, verbose_name='擅长领域')),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='挂号费')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否在职')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctors', to='core.department', verbose_name='所属科室')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '医生档案',
                'verbose_name_plural': '医生档案',
                'ordering': ['department', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, '周一'), (1, '周二'), (2, '周三'), (3, '周四'), (4, '周五'), (5, '周六'), (6, '周日')], verbose_name='星期')),
                ('shift', models.CharField(choices=[('MORNING', '上午'), ('AFTERNOON', '下午'), ('EVENING', '晚间')], max_length=20, verbose_name='班次')),
                ('max_patients', models.IntegerField(default=20, verbose_name='最大接诊数')),
                ('start_time', models.TimeField(verbose_name='开始时间')),
                ('end_time', models.TimeField(verbose_name='结束时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='doctors.doctorprofile', verbose_name='医生')),
            ],
            options={
                'verbose_name': '医生排班',
                'verbose_name_plural': '医生排班',
                'ordering': ['day_of_week', 'shift'],
                'unique_together': {('doctor', 'day_of_week', 'shift')},
            },
        ),
        migrations.CreateModel(
            name='DailySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('shift', models.CharField(choices=[('MORNING', '上午'), ('AFTERNOON', '下午'), ('EVENING', '晚间')], max_length=20, verbose_name='班次')),
                ('max_patients', models.IntegerField(default=20, verbose_name='最大接诊数')),
                ('booked_count', models.IntegerField(default=0, verbose_name='已预约数')),
                ('status', models.CharField(choices=[('AVAILABLE', '可预约'), ('FULL', '已满'), ('CANCELLED', '停诊')], default='AVAILABLE', max_length=20, verbose_name='状态')),
                ('cancel_reason', models.TextField(blank=True, verbose_name='停诊原因')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_slots', to='doctors.doctorprofile', verbose_name='医生')),
            ],
            options={
                'verbose_name': '每日号源',
                'verbose_name_plural': '每日号源',
                'ordering': ['-date', 'shift'],
                'unique_together': {('doctor', 'date', 'shift')},
            },
        ),
    ]
