# Generated by Django 5.2.15 on 2026-06-21 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='供应商名称')),
                ('unified_social_credit_code', models.CharField(max_length=50, unique=True, verbose_name='统一社会信用代码')),
                ('legal_person', models.CharField(blank=True, max_length=50, verbose_name='法人代表')),
                ('contact_person', models.CharField(max_length=50, verbose_name='联系人')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='联系邮箱')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='地址')),
                ('registered_capital', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='注册资本(万元)')),
                ('establishment_date', models.DateField(blank=True, null=True, verbose_name='成立日期')),
                ('business_scope', models.TextField(blank=True, verbose_name='经营范围')),
                ('status', models.CharField(choices=[('active', '合作中'), ('suspended', '暂停合作'), ('blacklisted', '黑名单'), ('potential', '潜在供应商')], default='potential', max_length=20, verbose_name='合作状态')),
                ('credit_rating', models.CharField(blank=True, choices=[('aaa', 'AAA 优秀'), ('aa', 'AA 良好'), ('a', 'A 一般'), ('b', 'B 合格'), ('c', 'C 风险'), ('d', 'D 不合格')], max_length=10, verbose_name='信用评级')),
                ('bank_account', models.CharField(blank=True, max_length=100, verbose_name='银行账户')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='开户银行')),
                ('tax_number', models.CharField(blank=True, max_length=50, verbose_name='纳税人识别号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '供应商',
                'verbose_name_plural': '供应商',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_period', models.CharField(max_length=50, verbose_name='评估周期')),
                ('quality_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='质量评分')),
                ('delivery_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='交付评分')),
                ('price_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='价格评分')),
                ('service_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='服务评分')),
                ('overall_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='综合评分')),
                ('comments', models.TextField(blank=True, verbose_name='评价意见')),
                ('evaluation_date', models.DateField(auto_now_add=True, verbose_name='评估日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '供应商评估',
                'verbose_name_plural': '供应商评估',
                'ordering': ['-evaluation_date'],
            },
        ),
        migrations.CreateModel(
            name='SupplierRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_type', models.CharField(choices=[('financial', '财务风险'), ('operational', '经营风险'), ('legal', '法律风险'), ('quality', '质量风险'), ('delivery', '交付风险'), ('reputation', '声誉风险'), ('compliance', '合规风险')], max_length=30, verbose_name='风险类型')),
                ('risk_level', models.CharField(choices=[('critical', '严重'), ('high', '高'), ('medium', '中'), ('low', '低')], max_length=20, verbose_name='风险等级')),
                ('title', models.CharField(max_length=200, verbose_name='风险标题')),
                ('description', models.TextField(verbose_name='风险详情')),
                ('source', models.CharField(blank=True, max_length=100, verbose_name='风险来源')),
                ('discovered_date', models.DateField(verbose_name='发现日期')),
                ('expected_resolution_date', models.DateField(blank=True, null=True, verbose_name='预计解决日期')),
                ('actual_resolution_date', models.DateField(blank=True, null=True, verbose_name='实际解决日期')),
                ('status', models.CharField(choices=[('open', '待处理'), ('monitoring', '监控中'), ('resolved', '已解决'), ('closed', '已关闭')], default='open', max_length=20, verbose_name='处理状态')),
                ('mitigation_measures', models.TextField(blank=True, verbose_name='缓解措施')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '供应商风险',
                'verbose_name_plural': '供应商风险',
                'ordering': ['-risk_level', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierRiskEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='risk_evidences/%Y/%m/', verbose_name='证据文件')),
                ('file_name', models.CharField(max_length=255, verbose_name='文件名')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '风险证据',
                'verbose_name_plural': '风险证据',
                'ordering': ['-created_at'],
            },
        ),
    ]
