# Generated by Django 5.2.15 on 2026-06-21 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_suppliers', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='supplierevaluation',
            name='evaluated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='评估人'),
        ),
        migrations.AddField(
            model_name='supplierevaluation',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='suppliers.supplier', verbose_name='供应商'),
        ),
        migrations.AddField(
            model_name='supplierrisk',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_risks', to=settings.AUTH_USER_MODEL, verbose_name='处理人'),
        ),
        migrations.AddField(
            model_name='supplierrisk',
            name='identified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identified_risks', to=settings.AUTH_USER_MODEL, verbose_name='发现人'),
        ),
        migrations.AddField(
            model_name='supplierrisk',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='suppliers.supplier', verbose_name='供应商'),
        ),
        migrations.AddField(
            model_name='supplierriskevidence',
            name='risk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='suppliers.supplierrisk', verbose_name='风险记录'),
        ),
        migrations.AddField(
            model_name='supplierriskevidence',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='上传人'),
        ),
    ]
