# Generated by Django 4.2.7 on 2026-06-05 18:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('books', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='日期')),
                ('order_count', models.IntegerField(default=0, verbose_name='订单数')),
                ('member_count', models.IntegerField(default=0, verbose_name='会员订单数')),
                ('guest_count', models.IntegerField(default=0, verbose_name='散客订单数')),
                ('total_quantity', models.IntegerField(default=0, verbose_name='销售册数')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='销售总额')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='成本总额')),
                ('total_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='利润总额')),
                ('total_points_earned', models.IntegerField(default=0, verbose_name='发放积分')),
                ('total_points_used', models.IntegerField(default=0, verbose_name='使用积分')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='折扣总额')),
                ('refund_count', models.IntegerField(default=0, verbose_name='退款订单数')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='退款金额')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '日销售报表',
                'verbose_name_plural': '日销售报表',
                'db_table': 'daily_sales_report',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SaleOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('order_no', models.CharField(max_length=30, unique=True, verbose_name='订单号')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('confirmed', '已确认'), ('paid', '已支付'), ('completed', '已完成'), ('refunded', '已退款'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', '现金'), ('wechat', '微信支付'), ('alipay', '支付宝'), ('card', '银行卡'), ('points', '积分抵扣'), ('mixed', '混合支付')], max_length=20, verbose_name='支付方式')),
                ('total_quantity', models.IntegerField(default=0, verbose_name='商品总数')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='商品金额')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='折扣金额')),
                ('points_used', models.IntegerField(default=0, verbose_name='使用积分')),
                ('points_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='积分抵扣金额')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='应付金额')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='实付金额')),
                ('points_earned', models.IntegerField(default=0, verbose_name='获得积分')),
                ('sale_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='销售时间')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='core.user', verbose_name='创建人')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='members.member', verbose_name='会员')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='core.user', verbose_name='更新人')),
            ],
            options={
                'verbose_name': '销售订单',
                'verbose_name_plural': '销售订单',
                'db_table': 'sale_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('discount', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='折扣率')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='小计')),
                ('points_earned', models.IntegerField(default=0, verbose_name='获得积分')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='books.book', verbose_name='图书')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.saleorder', verbose_name='订单')),
            ],
            options={
                'verbose_name': '订单明细',
                'verbose_name_plural': '订单明细',
                'db_table': 'sale_order_item',
            },
        ),
        migrations.CreateModel(
            name='BookSalesRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quantity', models.IntegerField(default=0, verbose_name='总销量')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='总销售额')),
                ('rank', models.IntegerField(default=0, verbose_name='排名')),
                ('month_quantity', models.IntegerField(default=0, verbose_name='本月销量')),
                ('week_quantity', models.IntegerField(default=0, verbose_name='本周销量')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sales_rank', to='books.book', verbose_name='图书')),
            ],
            options={
                'verbose_name': '图书销量排行',
                'verbose_name_plural': '图书销量排行',
                'db_table': 'book_sales_rank',
                'ordering': ['rank'],
            },
        ),
        migrations.AddIndex(
            model_name='saleorder',
            index=models.Index(fields=['order_no'], name='sale_order_order_n_46327b_idx'),
        ),
        migrations.AddIndex(
            model_name='saleorder',
            index=models.Index(fields=['status'], name='sale_order_status_48a193_idx'),
        ),
        migrations.AddIndex(
            model_name='saleorder',
            index=models.Index(fields=['sale_date'], name='sale_order_sale_da_6792a5_idx'),
        ),
    ]
