# Generated by Django 4.2.7 on 2026-06-05 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('APPT_REMIND', '预约提醒'), ('CONFIRM', '确认通知'), ('MED_REMIND', '用药提醒'), ('CANCEL', '取消通知'), ('NO_SHOW', '爽约提醒'), ('FU_REMIND', '随访提醒')], max_length=30, verbose_name='消息类型')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='CN', verbose_name='手机号')),
                ('content', models.TextField(verbose_name='短信内容')),
                ('status', models.CharField(choices=[('PENDING', '待发送'), ('SENT', '已发送'), ('FAILED', '发送失败'), ('DELIVERED', '已送达')], default='PENDING', max_length=20, verbose_name='状态')),
                ('provider_message_id', models.CharField(blank=True, max_length=100, verbose_name='服务商消息ID')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='发送时间')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='送达时间')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('retry_count', models.IntegerField(default=0, verbose_name='重试次数')),
                ('scheduled_send_time', models.DateTimeField(blank=True, null=True, verbose_name='计划发送时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_messages', to='appointments.appointment', verbose_name='关联预约')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sms', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('medication_reminder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_messages', to='appointments.medicationreminder', verbose_name='关联用药提醒')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_messages', to='patients.patientprofile', verbose_name='患者')),
            ],
            options={
                'verbose_name': '短信记录',
                'verbose_name_plural': '短信记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('message', models.TextField(verbose_name='内容')),
                ('type', models.CharField(choices=[('INFO', '通知'), ('WARNING', '警告'), ('ALERT', '紧急')], default='INFO', max_length=20, verbose_name='类型')),
                ('status', models.CharField(choices=[('UNREAD', '未读'), ('READ', '已读')], default='UNREAD', max_length=20, verbose_name='状态')),
                ('related_url', models.CharField(blank=True, max_length=500, verbose_name='关联链接')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='阅读时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='接收用户')),
            ],
            options={
                'verbose_name': '系统通知',
                'verbose_name_plural': '系统通知',
                'ordering': ['-created_at'],
            },
        ),
    ]
