# Generated by Django 4.2.30 on 2026-06-05 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='模板名称')),
                ('type', models.CharField(choices=[('system', '系统通知'), ('booking', '预约通知'), ('training', '培训通知'), ('maintenance', '维护通知'), ('safety', '安全通知'), ('consumable', '耗材通知')], max_length=20, verbose_name='通知类型')),
                ('title_template', models.CharField(max_length=200, verbose_name='标题模板')),
                ('content_template', models.TextField(verbose_name='内容模板')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('variables', models.JSONField(blank=True, default=list, verbose_name='可用变量')),
            ],
            options={
                'verbose_name': '通知模板',
                'verbose_name_plural': '通知模板',
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True, verbose_name='邮件通知')),
                ('push_enabled', models.BooleanField(default=True, verbose_name='推送通知')),
                ('sms_enabled', models.BooleanField(default=False, verbose_name='短信通知')),
                ('muted_types', models.JSONField(blank=True, default=list, verbose_name='静音通知类型')),
                ('quiet_hours_start', models.TimeField(blank=True, null=True, verbose_name='免打扰开始时间')),
                ('quiet_hours_end', models.TimeField(blank=True, null=True, verbose_name='免打扰结束时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '通知偏好设置',
                'verbose_name_plural': '通知偏好设置',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('type', models.CharField(choices=[('system', '系统通知'), ('booking', '预约通知'), ('training', '培训通知'), ('maintenance', '维护通知'), ('safety', '安全通知'), ('consumable', '耗材通知')], default='system', max_length=20, verbose_name='通知类型')),
                ('priority', models.CharField(choices=[('low', '普通'), ('medium', '重要'), ('high', '紧急')], default='medium', max_length=20, verbose_name='优先级')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('is_read', models.BooleanField(default=False, verbose_name='已读')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='阅读时间')),
                ('object_id', models.UUIDField(blank=True, null=True, verbose_name='关联对象ID')),
                ('action_url', models.URLField(blank=True, max_length=500, verbose_name='操作链接')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='关联内容类型')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='接收人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='notificatio_recipie_684eac_idx'), models.Index(fields=['type', 'created_at'], name='notificatio_type_8e213d_idx'), models.Index(fields=['priority', 'created_at'], name='notificatio_priorit_f7c359_idx')],
            },
        ),
    ]
