INSERT INTO channels (id, name, total_samples, quality_score, pending_review, fast_answer_count, duplicate_submission_count, device_concentration_count, skip_abnormal_count, open_copy_count, updated_at) VALUES
('ch-001', '微信朋友圈', 856, 78, 12, 23, 8, 15, 18, 10, NOW()),
('ch-002', '抖音信息流', 1245, 72, 28, 45, 22, 31, 27, 19, NOW()),
('ch-003', '小红书种草', 632, 85, 6, 12, 3, 7, 9, 5, NOW()),
('ch-004', '百度SEM', 421, 68, 15, 18, 12, 14, 11, 8, NOW()),
('ch-005', '电商平台弹窗', 967, 82, 9, 19, 5, 11, 13, 7, NOW());

INSERT INTO samples (id, channel_id, channel_name, total_duration, device_id, ip_region, abnormal_types, status, question_group_durations, skip_pattern, open_answers, submitted_at) VALUES
('s-001', 'ch-001', '微信朋友圈', 42, 'dev-abc123', '广东省深圳市', ARRAY['fast_answer', 'open_copy']::varchar[], 'pending', '[{"groupName":"基本信息","duration":8},{"groupName":"消费习惯","duration":12},{"groupName":"品牌认知","duration":7},{"groupName":"购买意向","duration":10},{"groupName":"开放题","duration":5}]', '{}', '[{"question":"请描述您的使用体验","answer":"产品不错，值得购买","similarity":0.85}]', NOW() - INTERVAL '1 hour'),
('s-002', 'ch-001', '微信朋友圈', 156, 'dev-def456', '北京市朝阳区', ARRAY['skip_abnormal']::varchar[], 'approved', '[{"groupName":"基本信息","duration":15},{"groupName":"消费习惯","duration":28},{"groupName":"品牌认知","duration":22},{"groupName":"购买意向","duration":18},{"groupName":"开放题","duration":73}]', '{2}', '[{"question":"请描述您的使用体验","answer":"使用体验很好，推荐给朋友","similarity":0.1}]', NOW() - INTERVAL '2 hours'),
('s-003', 'ch-002', '抖音信息流', 38, 'dev-ghi789', '上海市浦东新区', ARRAY['fast_answer']::varchar[], 'pending', '[{"groupName":"基本信息","duration":5},{"groupName":"消费习惯","duration":8},{"groupName":"品牌认知","duration":6},{"groupName":"购买意向","duration":9},{"groupName":"开放题","duration":10}]', '{}', '[{"question":"请描述您的使用体验","answer":"很好","similarity":0.92}]', NOW() - INTERVAL '30 minutes'),
('s-004', 'ch-002', '抖音信息流', 450, 'dev-jkl012', '浙江省杭州市', ARRAY['duplicate_submission', 'device_concentration']::varchar[], 'pending', '[{"groupName":"基本信息","duration":42},{"groupName":"消费习惯","duration":68},{"groupName":"品牌认知","duration":55},{"groupName":"购买意向","duration":48},{"groupName":"开放题","duration":237}]', '{}', '[{"question":"请描述您的使用体验","answer":"产品功能齐全，满足我的需求","similarity":0.05}]', NOW() - INTERVAL '45 minutes'),
('s-005', 'ch-002', '抖音信息流', 452, 'dev-jkl012', '浙江省杭州市', ARRAY['duplicate_submission', 'device_concentration']::varchar[], 'pending', '[{"groupName":"基本信息","duration":40},{"groupName":"消费习惯","duration":70},{"groupName":"品牌认知","duration":52},{"groupName":"购买意向","duration":50},{"groupName":"开放题","duration":240}]', '{}', '[{"question":"请描述您的使用体验","answer":"产品功能齐全，满足我的需求","similarity":0.05}]', NOW() - INTERVAL '46 minutes'),
('s-006', 'ch-003', '小红书种草', 210, 'dev-mno345', '四川省成都市', ARRAY['device_concentration']::varchar[], 'rejected', '[{"groupName":"基本信息","duration":25},{"groupName":"消费习惯","duration":38},{"groupName":"品牌认知","duration":32},{"groupName":"购买意向","duration":28},{"groupName":"开放题","duration":87}]', '{}', '[{"question":"请描述您的使用体验","answer":"颜值很高，非常喜欢","similarity":0.15}]', NOW() - INTERVAL '3 hours'),
('s-007', 'ch-004', '百度SEM', 89, 'dev-pqr678', '江苏省南京市', ARRAY['fast_answer', 'skip_abnormal']::varchar[], 'pending', '[{"groupName":"基本信息","duration":10},{"groupName":"消费习惯","duration":15},{"groupName":"品牌认知","duration":12},{"groupName":"购买意向","duration":18},{"groupName":"开放题","duration":34}]', '{1,3}', '[{"question":"请描述您的使用体验","answer":"还可以","similarity":0.78}]', NOW() - INTERVAL '1.5 hours'),
('s-008', 'ch-005', '电商平台弹窗', 320, 'dev-stu901', '湖北省武汉市', ARRAY['open_copy']::varchar[], 'approved', '[{"groupName":"基本信息","duration":35},{"groupName":"消费习惯","duration":48},{"groupName":"品牌认知","duration":42},{"groupName":"购买意向","duration":38},{"groupName":"开放题","duration":157}]', '{}', '[{"question":"请描述您的使用体验","answer":"性价比很高，下次还会购买","similarity":0.2}]', NOW() - INTERVAL '5 hours');

INSERT INTO review_queue (id, sample_id, channel_id, channel_name, abnormal_types, marked_at, status) VALUES
('rq-001', 's-001', 'ch-001', '微信朋友圈', ARRAY['fast_answer', 'open_copy']::varchar[], NOW() - INTERVAL '1 hour', 'pending'),
('rq-002', 's-003', 'ch-002', '抖音信息流', ARRAY['fast_answer']::varchar[], NOW() - INTERVAL '30 minutes', 'pending'),
('rq-003', 's-004', 'ch-002', '抖音信息流', ARRAY['duplicate_submission', 'device_concentration']::varchar[], NOW() - INTERVAL '45 minutes', 'pending'),
('rq-004', 's-005', 'ch-002', '抖音信息流', ARRAY['duplicate_submission', 'device_concentration']::varchar[], NOW() - INTERVAL '46 minutes', 'pending'),
('rq-005', 's-007', 'ch-004', '百度SEM', ARRAY['fast_answer', 'skip_abnormal']::varchar[], NOW() - INTERVAL '1.5 hours', 'pending');
