# Generated by Django 4.2.7 on 2026-06-05 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('dropoff', '送园'), ('pickup', '接走')], max_length=10, verbose_name='方向')),
                ('actual_person_name', models.CharField(blank=True, default='', max_length=50, verbose_name='实际接送人姓名')),
                ('actual_person_id', models.CharField(blank=True, default='', max_length=18, verbose_name='实际接送人身份证')),
                ('status', models.CharField(choices=[('pending', '待核验'), ('verified', '已核验'), ('rejected', '已拒绝')], default='pending', max_length=10, verbose_name='状态')),
                ('pickup_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='接送时间')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('authorized_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_records', to='children.authorizedpickupperson', verbose_name='授权接送人')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_records', to='children.child', verbose_name='儿童')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_pickups', to=settings.AUTH_USER_MODEL, verbose_name='核验人')),
            ],
            options={
                'verbose_name': '接送记录',
                'verbose_name_plural': '接送记录',
                'db_table': 'pickup_pickuprecord',
                'indexes': [models.Index(fields=['child', 'pickup_time'], name='idx_pickup_child_time'), models.Index(fields=['status'], name='idx_pickup_status'), models.Index(fields=['pickup_time'], name='idx_pickup_time')],
            },
        ),
    ]
