# Generated by Django 4.2.30 on 2026-06-05 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingCourse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=200, verbose_name='课程名称')),
                ('description', models.TextField(verbose_name='课程描述')),
                ('prerequisites', models.TextField(blank=True, verbose_name='前置条件')),
                ('duration_hours', models.DecimalField(decimal_places=1, default=2.0, max_digits=4, verbose_name='时长(小时)')),
                ('max_participants', models.IntegerField(default=10, verbose_name='最大人数')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '已归档')], default='draft', max_length=20, verbose_name='状态')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='training/', verbose_name='封面图片')),
                ('materials', models.JSONField(blank=True, default=list, verbose_name='参考资料')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_courses', to='equipment.equipmentcategory', verbose_name='适用设备类别')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '培训课程',
                'verbose_name_plural': '培训课程',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('location', models.CharField(max_length=200, verbose_name='培训地点')),
                ('max_participants', models.IntegerField(verbose_name='最大人数')),
                ('current_participants', models.IntegerField(default=0, verbose_name='当前人数')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='training.trainingcourse', verbose_name='培训课程')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('trainer', models.ForeignKey(limit_choices_to={'role__in': ['trainer', 'admin']}, on_delete=django.db.models.deletion.PROTECT, related_name='training_sessions_as_trainer', to=settings.AUTH_USER_MODEL, verbose_name='培训师')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '培训场次',
                'verbose_name_plural': '培训场次',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='TrainingCertification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('issued_date', models.DateField(verbose_name='颁发日期')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='有效期至')),
                ('status', models.CharField(choices=[('valid', '有效'), ('expired', '已过期'), ('revoked', '已吊销')], default='valid', max_length=20, verbose_name='状态')),
                ('certificate_number', models.CharField(max_length=50, unique=True, verbose_name='证书编号')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='考核成绩')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='证书文件')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certifications', to='equipment.equipmentcategory', verbose_name='设备类别')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certifications', to='training.trainingcourse', verbose_name='培训课程')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_certifications', to=settings.AUTH_USER_MODEL, verbose_name='颁发人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to=settings.AUTH_USER_MODEL, verbose_name='持证人')),
            ],
            options={
                'verbose_name': '培训资格证书',
                'verbose_name_plural': '培训资格证书',
                'ordering': ['-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='TrainingApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝'), ('cancelled', '已取消'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='状态')),
                ('application_notes', models.TextField(blank=True, verbose_name='申请说明')),
                ('review_notes', models.TextField(blank=True, verbose_name='审核说明')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_reviews', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='training.trainingsession', verbose_name='培训场次')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_applications', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
            ],
            options={
                'verbose_name': '培训申请',
                'verbose_name_plural': '培训申请',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='trainingsession',
            index=models.Index(fields=['course', 'start_time'], name='training_tr_course__f54ede_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingsession',
            index=models.Index(fields=['trainer', 'start_time'], name='training_tr_trainer_0f5f7b_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingsession',
            index=models.Index(fields=['start_time'], name='training_tr_start_t_9ceea9_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingcourse',
            index=models.Index(fields=['name'], name='training_tr_name_0de591_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingcourse',
            index=models.Index(fields=['category'], name='training_tr_categor_ddcb1b_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingcourse',
            index=models.Index(fields=['status'], name='training_tr_status_3539fc_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingcertification',
            index=models.Index(fields=['user', 'status'], name='training_tr_user_id_b50310_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingcertification',
            index=models.Index(fields=['category', 'status'], name='training_tr_categor_cb3d64_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingcertification',
            index=models.Index(fields=['certificate_number'], name='training_tr_certifi_80a881_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingcertification',
            index=models.Index(fields=['expiry_date'], name='training_tr_expiry__825676_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingapplication',
            index=models.Index(fields=['user', 'status'], name='training_tr_user_id_91d65d_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingapplication',
            index=models.Index(fields=['session', 'status'], name='training_tr_session_617370_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingapplication',
            index=models.Index(fields=['status'], name='training_tr_status_72cae7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='trainingapplication',
            unique_together={('session', 'user')},
        ),
    ]
