# Generated by Django 5.0.1 on 2026-06-11 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='模板名称')),
                ('template', models.TextField(verbose_name='模板内容')),
                ('placeholders', models.JSONField(blank=True, default=list, verbose_name='占位符列表')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '提示词模板',
                'verbose_name_plural': '提示词模板',
                'db_table': 'prompt_templates',
            },
        ),
        migrations.CreateModel(
            name='PromptCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, verbose_name='分类描述')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='prompts.promptcategory', verbose_name='父分类')),
            ],
            options={
                'verbose_name': '提示词分类',
                'verbose_name_plural': '提示词分类',
                'db_table': 'prompt_categories',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('content', models.TextField(verbose_name='提示词内容')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('enabled', '启用'), ('disabled', '停用')], db_index=True, default='draft', max_length=20, verbose_name='状态')),
                ('version', models.CharField(db_index=True, max_length=50, verbose_name='版本号')),
                ('is_current_version', models.BooleanField(db_index=True, default=False, verbose_name='是否为当前版本')),
                ('gray_scale_percent', models.IntegerField(default=100, verbose_name='灰度百分比')),
                ('target_sales_operations', models.JSONField(blank=True, default=list, verbose_name='适用的销售运营分组')),
                ('accuracy_rate', models.FloatField(default=0, verbose_name='准确率')),
                ('usage_count', models.IntegerField(default=0, verbose_name='使用次数')),
                ('variables', models.JSONField(blank=True, default=dict, verbose_name='变量定义')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('parent_prompt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_versions', to='prompts.prompt', verbose_name='父版本')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompts', to='prompts.promptcategory', verbose_name='分类')),
            ],
            options={
                'verbose_name': '提示词',
                'verbose_name_plural': '提示词',
                'db_table': 'prompts',
                'ordering': ['-created_at'],
            },
        ),
    ]
